// ruoyi-front/src/views/monitor/logininfor/index.vue
<template>
   <div class="app-container">
      <!-- 搜索表单 -->
      <el-form :model="queryParams" ref="queryRef" :inline="true" v-show="showSearch" label-width="70px" class="search-form">
         <el-form-item label="登录地址" prop="ipaddr">
            <el-input
               v-model="queryParams.ipaddr"
               placeholder="请输入登录地址"
               clearable
               style="width: 200px"
               @keyup.enter="handleQuery"
            />
         </el-form-item>
         <el-form-item label="用户名称" prop="userName">
            <el-input
               v-model="queryParams.userName"
               placeholder="请输入用户名称"
               clearable
               style="width: 200px"
               @keyup.enter="handleQuery"
            />
         </el-form-item>
         <el-form-item label="状态" prop="status">
            <el-select
               v-model="queryParams.status"
               placeholder="登录状态"
               clearable
               style="width: 200px"
            >
               <el-option
                  v-for="dict in sys_common_status"
                  :key="dict.value"
                  :label="dict.label"
                  :value="dict.value"
               />
            </el-select>
         </el-form-item>
         <el-form-item label="登录时间">
            <el-date-picker
               v-model="dateRange"
               value-format="YYYY-MM-DD HH:mm:ss"
               type="daterange"
               range-separator="至"
               start-placeholder="开始日期"
               end-placeholder="结束日期"
               style="width: 240px"
               :default-time="[new Date(2000, 1, 1, 0, 0, 0), new Date(2000, 1, 1, 23, 59, 59)]"
            />
         </el-form-item>
         <el-form-item>
            <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
            <el-button icon="Refresh" @click="resetQuery">重置</el-button>
         </el-form-item>
      </el-form>

      <el-row :gutter="10" class="mb8">
         <el-col :span="1.5">
            <el-button
               type="danger"
               plain
               icon="Delete"
               :disabled="multiple"
               @click="handleDelete"
               v-hasPermi="['monitor:logininfor:remove']"
            >删除</el-button>
         </el-col>
         <el-col :span="1.5">
            <el-button
               type="danger"
               plain
               icon="Delete"
               @click="handleClean"
               v-hasPermi="['monitor:logininfor:remove']"
            >清空</el-button>
         </el-col>
         <el-col :span="1.5">
            <el-button
               type="primary"
               plain
               icon="Unlock"
               :disabled="single"
               @click="handleUnlock"
               v-hasPermi="['monitor:logininfor:unlock']"
            >解锁</el-button>
         </el-col>
         <el-col :span="1.5">
            <el-button
               type="warning"
               plain
               icon="Download"
               @click="handleExport"
               v-hasPermi="['monitor:logininfor:export']"
            >导出</el-button>
         </el-col>
         <right-toolbar v-model:showSearch="showSearch" @queryTable="getList"></right-toolbar>
      </el-row>

      <!-- 数据表格 -->
      <el-table 
         ref="logininforRef" 
         v-loading="loading" 
         :data="logininforList" 
         @selection-change="handleSelectionChange" 
         :default-sort="defaultSort" 
         @sort-change="handleSortChange"
         stripe
         style="width: 100%"
         class="logininfor-table"
      >
         <el-table-column type="selection" width="55" align="center" />
         <el-table-column label="访问编号" align="center" prop="infoId" width="100" />
         <el-table-column label="用户名称" align="left" prop="userName" min-width="120" :show-overflow-tooltip="true" sortable="custom" :sort-orders="['descending', 'ascending']" />
         <el-table-column label="地址" align="left" prop="ipaddr" min-width="130" :show-overflow-tooltip="true" />
         <el-table-column label="登录地点" align="left" prop="loginLocation" min-width="150" :show-overflow-tooltip="true" />
         <el-table-column label="操作系统" align="left" prop="os" min-width="120" :show-overflow-tooltip="true" />
         <el-table-column label="浏览器" align="left" prop="browser" min-width="150" :show-overflow-tooltip="true" />
         <el-table-column label="登录状态" align="center" prop="status" width="100">
            <template #default="scope">
               <dict-tag :options="sys_common_status" :value="scope.row.status" />
            </template>
         </el-table-column>
         <el-table-column label="描述" align="left" prop="msg" min-width="150" :show-overflow-tooltip="true" />
         <el-table-column label="访问时间" align="center" prop="loginTime" width="180" sortable="custom" :sort-orders="['descending', 'ascending']">
            <template #default="scope">
               <span>{{ parseTime(scope.row.loginTime) }}</span>
            </template>
         </el-table-column>
      </el-table>

      <pagination
         v-show="total > 0"
         :total="total"
         v-model:page="queryParams.pageNum"
         v-model:limit="queryParams.pageSize"
         @pagination="getList"
      />
   </div>
</template>

<script setup name="Logininfor">
import { list, delLogininfor, cleanLogininfor, unlockLogininfor } from "@/api/monitor/logininfor"

const { proxy } = getCurrentInstance()
const { sys_common_status } = proxy.useDict("sys_common_status")

const logininforList = ref([])
const loading = ref(true)
const showSearch = ref(true)
const ids = ref([])
const single = ref(true)
const multiple = ref(true)
const selectName = ref("")
const total = ref(0)
const dateRange = ref([])
const defaultSort = ref({ prop: "loginTime", order: "descending" })

// 查询参数
const queryParams = ref({
  pageNum: 1,
  pageSize: 10,
  ipaddr: undefined,
  userName: undefined,
  status: undefined,
  orderByColumn: undefined,
  isAsc: undefined
})

/** 查询登录日志列表 */
function getList() {
  loading.value = true
  list(proxy.addDateRange(queryParams.value, dateRange.value)).then(response => {
    logininforList.value = response.rows
    total.value = response.total
    loading.value = false
  })
}

/** 搜索按钮操作 */
function handleQuery() {
  queryParams.value.pageNum = 1
  getList()
}

/** 重置按钮操作 */
function resetQuery() {
  dateRange.value = []
  proxy.resetForm("queryRef")
  queryParams.value.pageNum = 1
  proxy.$refs["logininforRef"].sort(defaultSort.value.prop, defaultSort.value.order)
}

/** 多选框选中数据 */
function handleSelectionChange(selection) {
  ids.value = selection.map(item => item.infoId)
  multiple.value = !selection.length
  single.value = selection.length != 1
  selectName.value = selection.map(item => item.userName)
}

/** 排序触发事件 */
function handleSortChange(column, prop, order) {
  queryParams.value.orderByColumn = column.prop
  queryParams.value.isAsc = column.order
  getList()
}

/** 删除按钮操作 */
function handleDelete(row) {
  const infoIds = row.infoId || ids.value
  proxy.$modal.confirm('是否确认删除访问编号为"' + infoIds + '"的数据项?').then(function () {
    return delLogininfor(infoIds)
  }).then(() => {
    getList()
    proxy.$modal.msgSuccess("删除成功")
  }).catch(() => {})
}

/** 清空按钮操作 */
function handleClean() {
  proxy.$modal.confirm("是否确认清空所有登录日志数据项?").then(function () {
    return cleanLogininfor()
  }).then(() => {
    getList()
    proxy.$modal.msgSuccess("清空成功")
  }).catch(() => {})
}

/** 解锁按钮操作 */
function handleUnlock() {
  const username = selectName.value
  proxy.$modal.confirm('是否确认解锁用户"' + username + '"数据项?').then(function () {
    return unlockLogininfor(username)
  }).then(() => {
    proxy.$modal.msgSuccess("用户" + username + "解锁成功")
  }).catch(() => {})
}

/** 导出按钮操作 */
function handleExport() {
  proxy.download("monitor/logininfor/export", {
    ...queryParams.value,
  }, `logininfor_${new Date().getTime()}.xlsx`)
}

getList()
</script>

<style scoped lang="scss">
.search-form {
  margin-bottom: 16px;
  
  .el-form-item {
    margin-bottom: 16px;
  }
}

.logininfor-table {
  :deep(.el-table__row) {
    cursor: pointer;
    
    &:hover {
      background-color: var(--el-table-row-hover-bg-color);
    }
  }
}

:deep(.el-table) {
  .el-table__header {
    th {
      background-color: var(--el-table-header-bg-color);
      font-weight: 500;
    }
  }
}
</style>

// ruoyi-react-web/src/views/monitor/logininfor/index.jsx
import { useState, useEffect } from 'react'
import { Form, Input, Select, DatePicker, Button, Table, Modal, Space, Tooltip } from 'antd'
import { DeleteOutlined, ReloadOutlined, SearchOutlined, UnlockOutlined } from '@ant-design/icons'
import { list, delLogininfor, cleanLogininfor, unlockLogininfor } from '@/api/monitor/logininfor'
import { useDict } from '@/utils/dict'
import { addDateRange, parseTime } from '@/utils/ruoyi'
import dayjs from 'dayjs'
import modal from '@/plugins/modal'
import auth from '@/plugins/auth'
import Pagination from '@/components/Pagination'
import RightToolbar from '@/components/RightToolbar'
import DictTag from '@/components/DictTag'
import './index.scss'

const { RangePicker } = DatePicker

const Logininfor = () => {
  const [queryForm] = Form.useForm()

  const [data, setData] = useState([])
  const [loading, setLoading] = useState(true)
  const [showSearch, setShowSearch] = useState(true)
  const [selectedRowKeys, setSelectedRowKeys] = useState([])
  const [total, setTotal] = useState(0)
  const [dateRange, setDateRange] = useState([])

  const { sys_common_status } = useDict('sys_common_status')

  const [queryParams, setQueryParams] = useState({
    pageNum: 1,
    pageSize: 10,
    ipaddr: undefined,
    userName: undefined,
    status: undefined
  })

  useEffect(() => {
    getList()
  }, [queryParams, dateRange])

  // 查询登录日志
  const getList = async () => {
    setLoading(true)
    try {
      const params = addDateRange(queryParams, dateRange)
      const res = await list(params)
      setData(res.rows || [])
      setTotal(res.total || 0)
    } catch (error) {
      console.error('Failed to fetch logininfor:', error)
    } finally {
      setLoading(false)
    }
  }

  // 搜索
  const handleQuery = () => {
    const values = queryForm.getFieldsValue()
    setQueryParams(prev => ({
      ...prev,
      ...values,
      pageNum: 1
    }))
  }

  // 重置
  const resetQuery = () => {
    setDateRange([])
    queryForm.resetFields()
    setQueryParams({
      pageNum: 1,
      pageSize: 10,
      ipaddr: undefined,
      userName: undefined,
      status: undefined
    })
    getList()
  }

  // 分页
  const handlePagination = ({ page, limit }) => {
    setQueryParams(prev => ({
      ...prev,
      pageNum: page,
      pageSize: limit
    }))
  }

  // 表格选择
  const handleSelectionChange = (keys) => setSelectedRowKeys(keys)

  // 删除
  const handleDelete = (row) => {
    const infoIds = row?.infoId || selectedRowKeys
    if (!infoIds || (Array.isArray(infoIds) && infoIds.length === 0)) {
      modal.msgWarning('请选择要删除的记录')
      return
    }
    Modal.confirm({
      title: '提示',
      content: `是否确认删除登录日志编号为"${infoIds}"的数据项？`,
      onOk: async () => {
        try {
          await delLogininfor(infoIds)
          modal.msgSuccess('删除成功')
          getList()
          setSelectedRowKeys([])
        } catch (error) {
          console.error('Failed to delete logininfor:', error)
        }
      }
    })
  }

  // 清空
  const handleClean = () => {
    Modal.confirm({
      title: '提示',
      content: '是否确认清空所有登录日志？',
      onOk: async () => {
        try {
          await cleanLogininfor()
          modal.msgSuccess('清空成功')
          getList()
          setSelectedRowKeys([])
        } catch (error) {
          console.error('Failed to clean logininfor:', error)
        }
      }
    })
  }

  // 解锁
  const handleUnlock = (row) => {
    const userName = row?.userName
    if (!userName) {
      modal.msgWarning('未找到要解锁的用户')
      return
    }
    Modal.confirm({
      title: '提示',
      content: `是否确认解锁用户 "${userName}"？`,
      onOk: async () => {
        try {
          await unlockLogininfor(userName)
          modal.msgSuccess('解锁成功')
          getList()
        } catch (error) {
          console.error('Failed to unlock user:', error)
        }
      }
    })
  }

  const columns = [
    {
      title: '访问编号',
      dataIndex: 'infoId',
      key: 'infoId',
      width: 100
    },
    {
      title: '用户名称',
      dataIndex: 'userName',
      key: 'userName',
      ellipsis: true
    },
    {
      title: '登录地址',
      dataIndex: 'ipaddr',
      key: 'ipaddr',
      ellipsis: true
    },
    {
      title: '登录地点',
      dataIndex: 'loginLocation',
      key: 'loginLocation',
      ellipsis: true
    },
    {
      title: '浏览器',
      dataIndex: 'browser',
      key: 'browser',
      ellipsis: true
    },
    {
      title: '操作系统',
      dataIndex: 'os',
      key: 'os',
      ellipsis: true
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      width: 100,
      render: (text) => <DictTag options={sys_common_status} value={text} />
    },
    {
      title: '提示消息',
      dataIndex: 'msg',
      key: 'msg',
      ellipsis: true
    },
    {
      title: '访问时间',
      dataIndex: 'loginTime',
      key: 'loginTime',
      width: 180,
      render: (text) => parseTime(text)
    },
    {
      title: '操作',
      key: 'action',
      width: 120,
      render: (_, record) => (
        <Space size="small">
          {auth.hasPermiOr(['monitor:logininfor:unlock']) && (
            <Tooltip title="解锁">
              <Button
                type="link"
                icon={<UnlockOutlined />}
                size="small"
                onClick={() => handleUnlock(record)}
              />
            </Tooltip>
          )}
          {auth.hasPermiOr(['monitor:logininfor:remove']) && (
            <Tooltip title="删除">
              <Button
                type="link"
                danger
                icon={<DeleteOutlined />}
                size="small"
                onClick={() => handleDelete(record)}
              />
            </Tooltip>
          )}
        </Space>
      )
    }
  ]

  return (
    <div className="app-container logininfor-page">
      <Form
        form={queryForm}
        layout="inline"
        className="search-form"
        style={{ display: showSearch ? 'flex' : 'none', marginBottom: 16 }}
      >
        <Form.Item label="登录地址" name="ipaddr">
          <Input
            placeholder="请输入登录地址"
            style={{ width: 240 }}
            onPressEnter={handleQuery}
            allowClear
          />
        </Form.Item>
        <Form.Item label="用户名称" name="userName">
          <Input
            placeholder="请输入用户名称"
            style={{ width: 240 }}
            onPressEnter={handleQuery}
            allowClear
          />
        </Form.Item>
        <Form.Item label="状态" name="status">
          <Select
            placeholder="登录状态"
            style={{ width: 240 }}
            allowClear
          >
            {sys_common_status?.map(dict => (
              <Select.Option key={dict.value} value={dict.value}>
                {dict.label}
              </Select.Option>
            ))}
          </Select>
        </Form.Item>
        <Form.Item label="登录时间">
          <RangePicker
            value={dateRange.length ? [dayjs(dateRange[0]), dayjs(dateRange[1])] : null}
            onChange={(dates) => {
              setDateRange(dates ? [dates[0].format('YYYY-MM-DD'), dates[1].format('YYYY-MM-DD')] : [])
            }}
            format="YYYY-MM-DD"
          />
        </Form.Item>
        <Form.Item>
          <Button type="primary" icon={<SearchOutlined />} onClick={handleQuery}>
            搜索
          </Button>
          <Button icon={<ReloadOutlined />} onClick={resetQuery} style={{ marginLeft: 8 }}>
            重置
          </Button>
        </Form.Item>
      </Form>

      <div style={{ marginBottom: 16 }}>
        <Space>
          {auth.hasPermiOr(['monitor:logininfor:remove']) && (
            <Button
              type="default"
              danger
              icon={<DeleteOutlined />}
              disabled={!selectedRowKeys.length}
              onClick={() => handleDelete()}
            >
              删除
            </Button>
          )}
          {auth.hasPermiOr(['monitor:logininfor:remove']) && (
            <Button type="default" onClick={handleClean}>
              清空
            </Button>
          )}
          <RightToolbar
            showSearch={showSearch}
            columns={{}}
            onShowSearchChange={setShowSearch}
            onQueryTable={getList}
          />
        </Space>
      </div>

      <Table
        loading={loading}
        dataSource={data}
        columns={columns}
        rowSelection={{
          selectedRowKeys,
          onChange: handleSelectionChange
        }}
        rowKey="infoId"
        pagination={false}
      />

      <Pagination
        total={total}
        page={queryParams.pageNum}
        limit={queryParams.pageSize}
        onChange={handlePagination}
      />
    </div>
  )
}

export default Logininfor
