// ruoyi-front-vue/src/views/system/menu/index.vue
<template>
   <div class="app-container">
      <el-form :model="queryParams" ref="queryRef" :inline="true" v-show="showSearch" class="search-form">
         <el-form-item label="菜单名称" prop="menuName">
            <el-input
               v-model="queryParams.menuName"
               placeholder="请输入菜单名称"
               clearable
               style="width: 200px"
               @keyup.enter="handleQuery"
            />
         </el-form-item>
         <el-form-item label="状态" prop="status">
            <el-select v-model="queryParams.status" placeholder="菜单状态" clearable style="width: 200px">
               <el-option
                  v-for="dict in sys_normal_disable"
                  :key="dict.value"
                  :label="dict.label"
                  :value="dict.value"
               />
            </el-select>
         </el-form-item>
         <el-form-item>
            <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
            <el-button icon="Refresh" @click="resetQuery">重置</el-button>
         </el-form-item>
      </el-form>

      <el-row :gutter="10" class="mb8">
         <el-col :span="1.5">
            <el-button
               type="primary"
               plain
               icon="Plus"
               @click="handleAdd"
               v-hasPermi="['system:menu:add']"
            >新增</el-button>
         </el-col>
         <el-col :span="1.5">
            <el-button 
               type="info"
               plain
               icon="Sort"
               @click="toggleExpandAll"
            >展开/折叠</el-button>
         </el-col>
         <right-toolbar v-model:showSearch="showSearch" @queryTable="getList"></right-toolbar>
      </el-row>

      <el-table
         v-if="refreshTable"
         v-loading="loading"
         :data="menuList"
         row-key="menuId"
         :default-expand-all="isExpandAll"
         :tree-props="{ children: 'children', hasChildren: 'hasChildren' }"
         @row-dblclick="handleRowDblClick"
         @row-click="handleRowClick"
         stripe
         style="width: 100%"
         class="menu-table"
      >
         <el-table-column prop="menuName" label="菜单名称" :show-overflow-tooltip="true" width="160"></el-table-column>
         <el-table-column prop="icon" label="图标" align="center" width="100">
            <template #default="scope">
               <el-icon v-if="scope.row.icon">
                 <component :is="getIconComponent(scope.row.icon)" />
               </el-icon>
               <span v-else>-</span>
            </template>
         </el-table-column>
         <el-table-column prop="orderNum" label="排序" width="60"></el-table-column>
         <el-table-column prop="perms" label="权限标识" :show-overflow-tooltip="true"></el-table-column>
         <el-table-column prop="component" label="组件路径" :show-overflow-tooltip="true"></el-table-column>
         <el-table-column prop="status" label="状态" width="80">
            <template #default="scope">
               <dict-tag :options="sys_normal_disable" :value="scope.row.status" />
            </template>
         </el-table-column>
         <el-table-column label="创建时间" align="center" width="160" prop="createTime">
            <template #default="scope">
               <span>{{ parseTime(scope.row.createTime) }}</span>
            </template>
         </el-table-column>
         <el-table-column label="操作" align="center" width="210" fixed="right">
            <template #default="scope">
               <div class="action-buttons">
                  <el-button 
                     link 
                     type="primary" 
                     icon="Edit" 
                     size="small"
                     @click.stop="handleUpdate(scope.row)" 
                     v-hasPermi="['system:menu:edit']"
                  >修改</el-button>
                  <el-button 
                     link 
                     type="primary" 
                     icon="Plus" 
                     size="small"
                     @click.stop="handleAdd(scope.row)" 
                     v-hasPermi="['system:menu:add']"
                  >新增</el-button>
                  <el-button 
                     link 
                     type="danger" 
                     icon="Delete" 
                     size="small"
                     @click.stop="handleDelete(scope.row)" 
                     v-hasPermi="['system:menu:remove']"
                  >删除</el-button>
               </div>
            </template>
         </el-table-column>
      </el-table>

      <!-- 添加或修改菜单对话框 -->
      <el-dialog :title="title" v-model="open" width="680px" append-to-body :close-on-click-modal="false">
         <el-form ref="menuRef" :model="form" :rules="rules" label-width="100px">
            <el-row>
               <el-col :span="24">
                  <el-form-item label="上级菜单">
                     <el-tree-select
                        v-model="form.parentId"
                        :data="menuOptions"
                        :props="{ value: 'menuId', label: 'menuName', children: 'children' }"
                        value-key="menuId"
                        placeholder="选择上级菜单"
                        check-strictly
                     />
                  </el-form-item>
               </el-col>
               <el-col :span="24">
                  <el-form-item label="菜单类型" prop="menuType">
                     <el-radio-group v-model="form.menuType">
                        <el-radio value="M">目录</el-radio>
                        <el-radio value="C">菜单</el-radio>
                        <el-radio value="F">按钮</el-radio>
                     </el-radio-group>
                  </el-form-item>
               </el-col>
               <el-col :span="12" v-if="form.menuType != 'F'">
                  <el-form-item label="菜单图标" prop="icon">
                     <el-popover
                        placement="bottom-start"
                        :width="600"
                        trigger="click"
                        popper-class="icon-select-popover"
                     >
                        <template #reference>
                           <el-input v-model="form.icon" placeholder="点击选择图标" @blur="showSelectIcon" readonly>
                              <template #prefix>
                                 <el-icon v-if="form.icon" class="el-input__icon" style="height: 32px;width: 16px;">
                                   <component :is="getIconComponent(form.icon)" />
                                 </el-icon>
                                 <el-icon v-else style="height: 32px;width: 16px;"><Search /></el-icon>
                              </template>
                           </el-input>
                        </template>
                        <icon-select ref="iconSelectRef" @selected="selected" :active-icon="form.icon" />
                     </el-popover>
                  </el-form-item>
               </el-col>
               <el-col :span="12">
                  <el-form-item label="显示排序" prop="orderNum">
                     <el-input-number v-model="form.orderNum" controls-position="right" :min="0" />
                  </el-form-item>
               </el-col>
               <el-col :span="12">
                  <el-form-item label="菜单名称" prop="menuName">
                     <el-input v-model="form.menuName" placeholder="请输入菜单名称" />
                  </el-form-item>
               </el-col>
               <el-col :span="12" v-if="form.menuType == 'C'">
                  <el-form-item prop="routeName">
                     <template #label>
                        <span>
                           <el-tooltip content="默认不填则和路由地址相同：如地址为：`user`，则名称为`User`（注意：因为router会删除名称相同路由，为避免名字的冲突，特殊情况下请自定义，保证唯一性）" placement="top">
                              <el-icon><question-filled /></el-icon>
                           </el-tooltip>
                           路由名称
                        </span>
                     </template>
                     <el-input v-model="form.routeName" placeholder="请输入路由名称" />
                  </el-form-item>
               </el-col>
               <el-col :span="12" v-if="form.menuType != 'F'">
                  <el-form-item>
                     <template #label>
                        <span>
                           <el-tooltip content="选择是外链则路由地址需要以`http(s)://`开头" placement="top">
                              <el-icon><question-filled /></el-icon>
                           </el-tooltip>是否外链
                        </span>
                     </template>
                     <el-radio-group v-model="form.isFrame">
                        <el-radio value="0">是</el-radio>
                        <el-radio value="1">否</el-radio>
                     </el-radio-group>
                  </el-form-item>
               </el-col>
               <el-col :span="12" v-if="form.menuType != 'F'">
                  <el-form-item prop="path">
                     <template #label>
                        <span>
                           <el-tooltip content="访问的路由地址，如：`user`，如外网地址需内链访问则以`http(s)://`开头" placement="top">
                              <el-icon><question-filled /></el-icon>
                           </el-tooltip>
                           路由地址
                        </span>
                     </template>
                     <el-input v-model="form.path" placeholder="请输入路由地址" />
                  </el-form-item>
               </el-col>
               <el-col :span="12" v-if="form.menuType == 'C'">
                  <el-form-item prop="component">
                     <template #label>
                        <span>
                           <el-tooltip content="访问的组件路径，如：`system/user/index`，默认在`views`目录下" placement="top">
                              <el-icon><question-filled /></el-icon>
                           </el-tooltip>
                           组件路径
                        </span>
                     </template>
                     <el-input v-model="form.component" placeholder="请输入组件路径" />
                  </el-form-item>
               </el-col>
               <el-col :span="12" v-if="form.menuType != 'M'">
                  <el-form-item>
                     <el-input v-model="form.perms" placeholder="请输入权限标识" maxlength="100" />
                     <template #label>
                        <span>
                           <el-tooltip content="控制器中定义的权限字符，如：@PreAuthorize(`@ss.hasPermi('system:user:list')`)" placement="top">
                              <el-icon><question-filled /></el-icon>
                           </el-tooltip>
                           权限字符
                        </span>
                     </template>
                  </el-form-item>
               </el-col>
               <el-col :span="12" v-if="form.menuType == 'C'">
                  <el-form-item>
                     <el-input v-model="form.query" placeholder="请输入路由参数" maxlength="255" />
                     <template #label>
                        <span>
                           <el-tooltip content='访问路由的默认传递参数，如：`{"id": 1, "name": "ry"}`' placement="top">
                              <el-icon><question-filled /></el-icon>
                           </el-tooltip>
                           路由参数
                        </span>
                     </template>
                  </el-form-item>
               </el-col>
               <el-col :span="12" v-if="form.menuType == 'C'">
                  <el-form-item>
                     <template #label>
                        <span>
                           <el-tooltip content="选择是则会被`keep-alive`缓存，需要匹配组件的`name`和地址保持一致" placement="top">
                              <el-icon><question-filled /></el-icon>
                           </el-tooltip>
                           是否缓存
                        </span>
                     </template>
                     <el-radio-group v-model="form.isCache">
                        <el-radio value="0">缓存</el-radio>
                        <el-radio value="1">不缓存</el-radio>
                     </el-radio-group>
                  </el-form-item>
               </el-col>
               <el-col :span="12" v-if="form.menuType != 'F'">
                  <el-form-item>
                     <template #label>
                        <span>
                           <el-tooltip content="选择隐藏则路由将不会出现在侧边栏，但仍然可以访问" placement="top">
                              <el-icon><question-filled /></el-icon>
                           </el-tooltip>
                           显示状态
                        </span>
                     </template>
                     <el-radio-group v-model="form.visible">
                        <el-radio
                           v-for="dict in sys_show_hide"
                           :key="dict.value"
                           :value="dict.value"
                        >{{ dict.label }}</el-radio>
                     </el-radio-group>
                  </el-form-item>
               </el-col>
               <el-col :span="12">
                  <el-form-item>
                     <template #label>
                        <span>
                           <el-tooltip content="选择停用则路由将不会出现在侧边栏，也不能被访问" placement="top">
                              <el-icon><question-filled /></el-icon>
                           </el-tooltip>
                           菜单状态
                        </span>
                     </template>
                     <el-radio-group v-model="form.status">
                        <el-radio
                           v-for="dict in sys_normal_disable"
                           :key="dict.value"
                           :value="dict.value"
                        >{{ dict.label }}</el-radio>
                     </el-radio-group>
                  </el-form-item>
               </el-col>
            </el-row>
         </el-form>
         <template #footer>
            <div class="dialog-footer">
               <el-button @click="cancel">取 消</el-button>
               <el-button type="primary" @click="submitForm">确 定</el-button>
            </div>
         </template>
      </el-dialog>
   </div>
</template>

<script setup name="Menu">
import { addMenu, delMenu, getMenu, listMenu, updateMenu } from "@/api/system/menu"
import SvgIcon from "@/components/SvgIcon"
import IconSelect from "@/components/IconSelect"
import { getIconComponent } from '@/utils/icon'
import { Search } from '@element-plus/icons-vue'

const { proxy } = getCurrentInstance()
const { sys_show_hide, sys_normal_disable } = proxy.useDict("sys_show_hide", "sys_normal_disable")

const menuList = ref([])
const open = ref(false)
const loading = ref(true)
const showSearch = ref(true)
const title = ref("")
const menuOptions = ref([])
const isExpandAll = ref(false)
const refreshTable = ref(true)
const iconSelectRef = ref(null)

const data = reactive({
  form: {},
  queryParams: {
    menuName: undefined,
    visible: undefined
  },
  rules: {
    menuName: [{ required: true, message: "菜单名称不能为空", trigger: "blur" }],
    orderNum: [{ required: true, message: "菜单顺序不能为空", trigger: "blur" }],
    path: [{ required: true, message: "路由地址不能为空", trigger: "blur" }]
  },
})

const { queryParams, form, rules } = toRefs(data)

/** 查询菜单列表 */
function getList() {
  loading.value = true
  listMenu(queryParams.value).then(response => {
    menuList.value = proxy.handleTree(response.data, "menuId")
    loading.value = false
  })
}

/** 查询菜单下拉树结构 */
function getTreeselect() {
  menuOptions.value = []
  listMenu().then(response => {
    const menu = { menuId: 0, menuName: "主类目", children: [] }
    menu.children = proxy.handleTree(response.data, "menuId")
    menuOptions.value.push(menu)
  })
}

/** 取消按钮 */
function cancel() {
  open.value = false
  reset()
}

/** 表单重置 */
function reset() {
  form.value = {
    menuId: undefined,
    parentId: 0,
    menuName: undefined,
    icon: undefined,
    menuType: "M",
    orderNum: undefined,
    isFrame: "1",
    isCache: "0",
    visible: "0",
    status: "0"
  }
  proxy.resetForm("menuRef")
}

/** 展示下拉图标 */
function showSelectIcon() {
  iconSelectRef.value.reset()
}

/** 选择图标 */
function selected(name) {
  form.value.icon = name
}

/** 搜索按钮操作 */
function handleQuery() {
  getList()
}

/** 重置按钮操作 */
function resetQuery() {
  proxy.resetForm("queryRef")
  handleQuery()
}

/** 新增按钮操作 */
function handleAdd(row) {
  reset()
  getTreeselect()
  if (row != null && row.menuId) {
    form.value.parentId = row.menuId
  } else {
    form.value.parentId = 0
  }
  open.value = true
  title.value = "添加菜单"
}

/** 展开/折叠操作 */
function toggleExpandAll() {
  refreshTable.value = false
  isExpandAll.value = !isExpandAll.value
  nextTick(() => {
    refreshTable.value = true
  })
}

/** 单击行操作（用于选中） */
function handleRowClick(row, column, event) {
  if (event?.target?.closest('.action-buttons')) {
    return
  }
}

/** 双击行操作 */
function handleRowDblClick(row, column, event) {
  if (event?.target?.closest('.action-buttons')) {
    return
  }
  if (proxy.hasPermi(['system:menu:edit'])) {
    handleUpdate(row)
  }
}

/** 修改按钮操作 */
async function handleUpdate(row) {
  reset()
  if (!row || !row.menuId) {
    proxy.$modal.msgWarning("请选择要修改的菜单")
    return
  }
  
  await getTreeselect()
  getMenu(row.menuId).then(response => {
    form.value = response.data
    open.value = true
    title.value = "修改菜单"
  }).catch(error => {
    console.error("获取菜单信息失败:", error)
    proxy.$modal.msgError("获取菜单信息失败")
  })
}

/** 提交按钮 */
function submitForm() {
  proxy.$refs["menuRef"].validate(valid => {
    if (valid) {
      if (form.value.menuId != undefined) {
        updateMenu(form.value).then(response => {
          proxy.$modal.msgSuccess("修改成功")
          open.value = false
          getList()
        })
      } else {
        addMenu(form.value).then(response => {
          proxy.$modal.msgSuccess("新增成功")
          open.value = false
          getList()
        })
      }
    }
  })
}

/** 删除按钮操作 */
function handleDelete(row) {
  proxy.$modal.confirm('是否确认删除名称为"' + row.menuName + '"的数据项?').then(function() {
    return delMenu(row.menuId)
  }).then(() => {
    getList()
    proxy.$modal.msgSuccess("删除成功")
  }).catch(() => {})
}

getList()
</script>

<style scoped lang="scss">
.search-form {
  margin-bottom: 16px;
  
  .el-form-item {
    margin-bottom: 16px;
  }
}

.action-buttons {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  white-space: nowrap;
  
  .el-button {
    padding: 0 8px;
  }
}

.menu-table {
  :deep(.el-table__row) {
    cursor: pointer;
    
    &:hover {
      background-color: var(--el-table-row-hover-bg-color);
    }
  }
}

.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
}

:deep(.el-table) {
  .el-table__header {
    th {
      background-color: var(--el-table-header-bg-color);
      font-weight: 500;
    }
  }
}

:deep(.el-dialog__body) {
  padding: 24px 28px;
}

:deep(.el-dialog__header) {
  padding: 20px 28px 16px;
  border-bottom: 1px solid var(--el-border-color-lighter);
}

:deep(.el-dialog__footer) {
  padding: 16px 28px 20px;
  border-top: 1px solid var(--el-border-color-lighter);
}
</style>

// ruoyi-front-react/src/views/system/menu/index.jsx
import { useState, useEffect, useRef } from 'react'
import { Form, Input, InputNumber, Select, Button, Table, Modal, Radio, Popover, Tooltip, Space } from 'antd'
import { PlusOutlined, EditOutlined, DeleteOutlined, SearchOutlined, ReloadOutlined, SortAscendingOutlined, QuestionCircleOutlined } from '@ant-design/icons'
import { listMenu, getMenu, addMenu, updateMenu, delMenu } from '@/api/system/menu'
import { useDict } from '@/utils/dict'
import { parseTime, handleTree } from '@/utils/ruoyi'
import { getIconComponent } from '@/utils/icon'
import modal from '@/plugins/modal'
import auth from '@/plugins/auth'
import RightToolbar from '@/components/RightToolbar'
import IconSelect from '@/components/IconSelect'
import { TreeSelect } from 'antd'
import './index.scss'

const { TextArea } = Input

const Menu = () => {
  const [form] = Form.useForm()
  const [queryForm] = Form.useForm()
  const iconSelectRef = useRef(null)

  const [menuList, setMenuList] = useState([])
  const [loading, setLoading] = useState(true)
  const [showSearch, setShowSearch] = useState(true)
  const [open, setOpen] = useState(false)
  const [title, setTitle] = useState('')
  const [menuOptions, setMenuOptions] = useState([])
  const [isExpandAll, setIsExpandAll] = useState(false)
  const [refreshTable, setRefreshTable] = useState(true)

  const sys_show_hide = useDict('sys_show_hide')
  const sys_normal_disable = useDict('sys_normal_disable')

  const [queryParams, setQueryParams] = useState({
    menuName: undefined,
    visible: undefined
  })

  useEffect(() => {
    getList()
  }, [queryParams])

  // 查询菜单列表
  const getList = async () => {
    setLoading(true)
    try {
      const response = await listMenu(queryParams)
      const treeData = handleTree(response.data, 'menuId')
      setMenuList(treeData || [])
    } catch (error) {
      console.error('Failed to get menu list:', error)
    } finally {
      setLoading(false)
    }
  }

  // 查询菜单下拉树结构
  const getTreeselect = async () => {
    try {
      const response = await listMenu()
      const menu = { menuId: 0, menuName: '主类目', children: [] }
      menu.children = handleTree(response.data, 'menuId')
      setMenuOptions([menu])
    } catch (error) {
      console.error('Failed to get menu tree:', error)
    }
  }

  // 搜索
  const handleQuery = () => {
    const values = queryForm.getFieldsValue()
    setQueryParams(prev => ({
      ...prev,
      ...values
    }))
  }

  // 重置
  const resetQuery = () => {
    queryForm.resetFields()
    setQueryParams({
      menuName: undefined,
      visible: undefined
    })
    getList()
  }

  // 新增
  const handleAdd = async (row) => {
    reset()
    await getTreeselect()
    if (row != null && row.menuId) {
      form.setFieldValue('parentId', row.menuId)
    } else {
      form.setFieldValue('parentId', 0)
    }
    setOpen(true)
    setTitle('添加菜单')
  }

  // 修改
  const handleUpdate = async (row) => {
    reset()
    if (!row || !row.menuId) {
      modal.msgWarning('请选择要修改的菜单')
      return
    }

    await getTreeselect()
    try {
      const response = await getMenu(row.menuId)
      form.setFieldsValue(response.data)
      setOpen(true)
      setTitle('修改菜单')
    } catch (error) {
      console.error('Failed to get menu:', error)
      modal.msgError('获取菜单信息失败')
    }
  }

  // 删除
  const handleDelete = (row) => {
    Modal.confirm({
      title: '提示',
      content: `是否确认删除名称为"${row.menuName}"的数据项?`,
      onOk: async () => {
        try {
          await delMenu(row.menuId)
          modal.msgSuccess('删除成功')
          getList()
        } catch (error) {
          console.error('Failed to delete menu:', error)
        }
      }
    })
  }

  // 展开/折叠
  const toggleExpandAll = () => {
    setRefreshTable(false)
    setIsExpandAll(!isExpandAll)
    setTimeout(() => {
      setRefreshTable(true)
    }, 100)
  }

  // 表单重置
  const reset = () => {
    form.resetFields()
    form.setFieldsValue({
      menuId: undefined,
      parentId: 0,
      menuName: undefined,
      icon: undefined,
      menuType: 'M',
      orderNum: undefined,
      isFrame: '1',
      isCache: '0',
      visible: '0',
      status: '0'
    })
    if (iconSelectRef.current) {
      iconSelectRef.current.reset()
    }
  }

  // 取消
  const cancel = () => {
    setOpen(false)
    reset()
  }

  // 提交表单
  const submitForm = async () => {
    try {
      const values = await form.validateFields()
      if (values.menuId !== undefined) {
        await updateMenu(values)
        modal.msgSuccess('修改成功')
      } else {
        await addMenu(values)
        modal.msgSuccess('新增成功')
      }
      setOpen(false)
      getList()
    } catch (error) {
      console.error('Validation failed:', error)
    }
  }

  // 选择图标
  const selectedIcon = (name) => {
    form.setFieldValue('icon', name)
  }

  // 展示下拉图标
  const showSelectIcon = () => {
    if (iconSelectRef.current) {
      iconSelectRef.current.reset()
    }
  }

  // 双击行
  const handleRowDblClick = (row) => {
    if (auth.hasPermiOr(['system:menu:edit'])) {
      handleUpdate(row)
    }
  }

  // 表格列定义
  const columns = [
    {
      title: '菜单名称',
      dataIndex: 'menuName',
      key: 'menuName',
      ellipsis: true,
      width: 160
    },
    {
      title: '图标',
      dataIndex: 'icon',
      key: 'icon',
      align: 'center',
      width: 100,
      render: (icon) => {
        if (!icon || icon === '#') return '-'
        const IconComponent = getIconComponent(icon)
        return IconComponent ? <IconComponent /> : '-'
      }
    },
    {
      title: '排序',
      dataIndex: 'orderNum',
      key: 'orderNum',
      width: 60
    },
    {
      title: '权限标识',
      dataIndex: 'perms',
      key: 'perms',
      ellipsis: true
    },
    {
      title: '组件路径',
      dataIndex: 'component',
      key: 'component',
      ellipsis: true
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      width: 80,
      render: (status) => {
        const dict = sys_normal_disable.sys_normal_disable?.find(d => d.value === status)
        return dict ? dict.label : '-'
      }
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      key: 'createTime',
      align: 'center',
      width: 160,
      render: (text) => parseTime(text)
    },
    {
      title: '操作',
      key: 'action',
      align: 'center',
      fixed: 'right',
      width: 210,
      render: (_, record) => (
        <Space size="small">
          {auth.hasPermiOr(['system:menu:edit']) && (
            <Button
              type="link"
              icon={<EditOutlined />}
              size="small"
              onClick={(e) => {
                e.stopPropagation()
                handleUpdate(record)
              }}
            >
              修改
            </Button>
          )}
          {auth.hasPermiOr(['system:menu:add']) && (
            <Button
              type="link"
              icon={<PlusOutlined />}
              size="small"
              onClick={(e) => {
                e.stopPropagation()
                handleAdd(record)
              }}
            >
              新增
            </Button>
          )}
          {auth.hasPermiOr(['system:menu:remove']) && (
            <Button
              type="link"
              danger
              icon={<DeleteOutlined />}
              size="small"
              onClick={(e) => {
                e.stopPropagation()
                handleDelete(record)
              }}
            >
              删除
            </Button>
          )}
        </Space>
      )
    }
  ]

  return (
    <div className="app-container">
      <Form
        form={queryForm}
        layout="inline"
        className="search-form"
        style={{ display: showSearch ? 'flex' : 'none', marginBottom: 16 }}
      >
        <Form.Item label="菜单名称" name="menuName">
          <Input
            placeholder="请输入菜单名称"
            style={{ width: 200 }}
            onPressEnter={handleQuery}
            allowClear
          />
        </Form.Item>
        <Form.Item label="状态" name="visible">
          <Select
            placeholder="菜单状态"
            style={{ width: 200 }}
            allowClear
          >
            {sys_show_hide.sys_show_hide?.map(dict => (
              <Select.Option key={dict.value} value={dict.value}>
                {dict.label}
              </Select.Option>
            ))}
          </Select>
        </Form.Item>
        <Form.Item>
          <Button type="primary" icon={<SearchOutlined />} onClick={handleQuery}>
            搜索
          </Button>
          <Button icon={<ReloadOutlined />} onClick={resetQuery} style={{ marginLeft: 8 }}>
            重置
          </Button>
        </Form.Item>
      </Form>

      <div style={{ marginBottom: 16 }}>
        <Space>
          {auth.hasPermiOr(['system:menu:add']) && (
            <Button type="primary" icon={<PlusOutlined />} onClick={() => handleAdd()}>
              新增
            </Button>
          )}
          <Button type="default" icon={<SortAscendingOutlined />} onClick={toggleExpandAll}>
            展开/折叠
          </Button>
          <RightToolbar
            showSearch={showSearch}
            columns={{}}
            onShowSearchChange={setShowSearch}
            onQueryTable={getList}
          />
        </Space>
      </div>

      {refreshTable && (
        <Table
          loading={loading}
          dataSource={menuList}
          columns={columns}
          rowKey="menuId"
          defaultExpandAllRows={isExpandAll}
          onRow={(record) => ({
            onDoubleClick: () => handleRowDblClick(record)
          })}
          pagination={false}
        />
      )}

      {/* 添加或修改菜单对话框 */}
      <Modal
        title={title}
        open={open}
        onCancel={cancel}
        onOk={submitForm}
        width={680}
        destroyOnHidden
      >
        <Form
          form={form}
          labelCol={{ span: 6 }}
          wrapperCol={{ span: 18 }}
        >
          <Form.Item label="上级菜单" name="parentId">
            <TreeSelect
              treeData={menuOptions}
              fieldNames={{ label: 'menuName', value: 'menuId', children: 'children' }}
              placeholder="选择上级菜单"
              treeDefaultExpandAll
              allowClear
            />
          </Form.Item>
          <Form.Item
            label="菜单类型"
            name="menuType"
            rules={[{ required: true, message: '菜单类型不能为空' }]}
          >
            <Radio.Group>
              <Radio value="M">目录</Radio>
              <Radio value="C">菜单</Radio>
              <Radio value="F">按钮</Radio>
            </Radio.Group>
          </Form.Item>
          {form.getFieldValue('menuType') !== 'F' && (
            <Form.Item label="菜单图标" name="icon">
              <Popover
                placement="bottom"
                title="选择图标"
                content={
                  <IconSelect
                    ref={iconSelectRef}
                    activeIcon={form.getFieldValue('icon')}
                    onSelected={selectedIcon}
                  />
                }
                trigger="click"
              >
                <Input
                  value={form.getFieldValue('icon')}
                  placeholder="点击选择图标"
                  readOnly
                  onFocus={showSelectIcon}
                  prefix={
                    form.getFieldValue('icon') ? (
                      (() => {
                        const IconComponent = getIconComponent(form.getFieldValue('icon'))
                        return IconComponent ? <IconComponent /> : <SearchOutlined />
                      })()
                    ) : (
                      <SearchOutlined />
                    )
                  }
                />
              </Popover>
            </Form.Item>
          )}
          <Form.Item
            label="显示排序"
            name="orderNum"
            rules={[{ required: true, message: '菜单顺序不能为空' }]}
          >
            <InputNumber min={0} style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item
            label="菜单名称"
            name="menuName"
            rules={[{ required: true, message: '菜单名称不能为空' }]}
          >
            <Input placeholder="请输入菜单名称" />
          </Form.Item>
          {form.getFieldValue('menuType') === 'C' && (
            <Form.Item
              label={
                <span>
                  <Tooltip title="默认不填则和路由地址相同：如地址为：`user`，则名称为`User`（注意：因为router会删除名称相同路由，为避免名字的冲突，特殊情况下请自定义，保证唯一性）">
                    <QuestionCircleOutlined style={{ marginRight: 4 }} />
                  </Tooltip>
                  路由名称
                </span>
              }
              name="routeName"
            >
              <Input placeholder="请输入路由名称" />
            </Form.Item>
          )}
          {form.getFieldValue('menuType') !== 'F' && (
            <Form.Item
              label={
                <span>
                  <Tooltip title="选择是外链则路由地址需要以`http(s)://`开头">
                    <QuestionCircleOutlined style={{ marginRight: 4 }} />
                  </Tooltip>
                  是否外链
                </span>
              }
              name="isFrame"
            >
              <Radio.Group>
                <Radio value="0">是</Radio>
                <Radio value="1">否</Radio>
              </Radio.Group>
            </Form.Item>
          )}
          {form.getFieldValue('menuType') !== 'F' && (
            <Form.Item
              label={
                <span>
                  <Tooltip title="访问的路由地址，如：`user`，如外网地址需内链访问则以`http(s)://`开头">
                    <QuestionCircleOutlined style={{ marginRight: 4 }} />
                  </Tooltip>
                  路由地址
                </span>
              }
              name="path"
              rules={[{ required: true, message: '路由地址不能为空' }]}
            >
              <Input placeholder="请输入路由地址" />
            </Form.Item>
          )}
          {form.getFieldValue('menuType') === 'C' && (
            <Form.Item
              label={
                <span>
                  <Tooltip title="访问的组件路径，如：`system/user/index`，默认在`views`目录下">
                    <QuestionCircleOutlined style={{ marginRight: 4 }} />
                  </Tooltip>
                  组件路径
                </span>
              }
              name="component"
            >
              <Input placeholder="请输入组件路径" />
            </Form.Item>
          )}
          {form.getFieldValue('menuType') !== 'M' && (
            <Form.Item
              label={
                <span>
                  <Tooltip title="控制器中定义的权限字符，如：@PreAuthorize(`@ss.hasPermi('system:user:list')`)">
                    <QuestionCircleOutlined style={{ marginRight: 4 }} />
                  </Tooltip>
                  权限字符
                </span>
              }
              name="perms"
            >
              <Input placeholder="请输入权限标识" maxLength={100} />
            </Form.Item>
          )}
          {form.getFieldValue('menuType') === 'C' && (
            <Form.Item
              label={
                <span>
                  <Tooltip title='访问路由的默认传递参数，如：`{"id": 1, "name": "ry"}`'>
                    <QuestionCircleOutlined style={{ marginRight: 4 }} />
                  </Tooltip>
                  路由参数
                </span>
              }
              name="query"
            >
              <Input placeholder="请输入路由参数" maxLength={255} />
            </Form.Item>
          )}
          {form.getFieldValue('menuType') === 'C' && (
            <Form.Item
              label={
                <span>
                  <Tooltip title="选择是则会被`keep-alive`缓存，需要匹配组件的`name`和地址保持一致">
                    <QuestionCircleOutlined style={{ marginRight: 4 }} />
                  </Tooltip>
                  是否缓存
                </span>
              }
              name="isCache"
            >
              <Radio.Group>
                <Radio value="0">缓存</Radio>
                <Radio value="1">不缓存</Radio>
              </Radio.Group>
            </Form.Item>
          )}
          {form.getFieldValue('menuType') !== 'F' && (
            <Form.Item
              label={
                <span>
                  <Tooltip title="选择隐藏则路由将不会出现在侧边栏，但仍然可以访问">
                    <QuestionCircleOutlined style={{ marginRight: 4 }} />
                  </Tooltip>
                  显示状态
                </span>
              }
              name="visible"
            >
              <Radio.Group>
                {sys_show_hide.sys_show_hide?.map(dict => (
                  <Radio key={dict.value} value={dict.value}>
                    {dict.label}
                  </Radio>
                ))}
              </Radio.Group>
            </Form.Item>
          )}
          <Form.Item
            label={
              <span>
                <Tooltip title="选择停用则路由将不会出现在侧边栏，也不能被访问">
                  <QuestionCircleOutlined style={{ marginRight: 4 }} />
                </Tooltip>
                菜单状态
              </span>
            }
            name="status"
          >
            <Radio.Group>
              {sys_normal_disable.sys_normal_disable?.map(dict => (
                <Radio key={dict.value} value={dict.value}>
                  {dict.label}
                </Radio>
              ))}
            </Radio.Group>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

export default Menu
