// ruoyi-front-react/src/layout/components/Sidebar/SidebarItem.jsx
import { useMemo } from 'react'
import { useLocation } from 'react-router-dom'
import { Menu } from 'antd'
import { getIconComponent } from '@/utils/icon'
import { isExternal } from '@/utils/validate'
import { getNormalPath } from '@/utils/ruoyi'
import AppLink from './Link'
import './SidebarItem.scss'

const SidebarItem = ({ item, isNest = false, basePath = '' }) => {
  const location = useLocation()

  if (item.hidden) {
    return null
  }

  const onlyOneChild = useMemo(() => {
    let child = {}
    const hasOneShowingChild = (children = [], parent) => {
      if (!children) {
        children = []
      }
      const showingChildren = children.filter(item => {
        if (item.hidden) {
          return false
        }
        child = item
        return true
      })

      if (showingChildren.length === 1) {
        return true
      }

      if (showingChildren.length === 0) {
        child = { ...parent, path: '', noShowingChildren: true }
        return true
      }

      return false
    }

    hasOneShowingChild(item.children, item)
    return child
  }, [item])

  const resolvePath = (routePath, routeQuery) => {
    if (isExternal(routePath)) {
      return routePath
    }
    if (isExternal(basePath)) {
      return basePath
    }
    if (routeQuery) {
      let query = JSON.parse(routeQuery)
      return { path: getNormalPath(basePath + '/' + routePath), query: query }
    }
    return getNormalPath(basePath + '/' + routePath)
  }

  const hasOneShowing = useMemo(() => {
    if (!item.children || item.children.length === 0) {
      return false
    }
    const showingChildren = item.children.filter(child => !child.hidden)
    return showingChildren.length === 1 && (!onlyOneChild.children || onlyOneChild.noShowingChildren) && !item.alwaysShow
  }, [item, onlyOneChild])

  if (hasOneShowing && onlyOneChild.meta) {
    const path = resolvePath(onlyOneChild.path, onlyOneChild.query)
    const icon = onlyOneChild.meta.icon || (item.meta && item.meta.icon)
    const IconComponent = icon ? getIconComponent(icon) : null

    return (
      <Menu.Item key={typeof path === 'string' ? path : path.path}>
        <AppLink to={path}>
          {IconComponent && <IconComponent />}
          <span className="menu-title">{onlyOneChild.meta.title}</span>
        </AppLink>
      </Menu.Item>
    )
  }

  const path = resolvePath(item.path)
  const icon = item.meta && item.meta.icon
  const IconComponent = icon ? getIconComponent(icon) : null

  return (
    <Menu.SubMenu
      key={typeof path === 'string' ? path : path.path}
      title={
        <>
          {IconComponent && <IconComponent />}
          <span className="menu-title">{item.meta?.title}</span>
        </>
      }
      className={isNest ? 'nest-menu' : ''}
    >
      {item.children?.map((child, index) => (
        <SidebarItem
          key={child.path + index}
          item={child}
          isNest={true}
          basePath={resolvePath(child.path)}
        />
      ))}
    </Menu.SubMenu>
  )
}

export default SidebarItem

// ruoyi-front-vue/src/layout/components/Sidebar/SidebarItem.vue
<template>
  <div v-if="!item.hidden">
    <template v-if="hasOneShowingChild(item.children, item) && (!onlyOneChild.children || onlyOneChild.noShowingChildren) && !item.alwaysShow">
      <app-link v-if="onlyOneChild.meta" :to="resolvePath(onlyOneChild.path, onlyOneChild.query)">
        <el-menu-item :index="resolvePath(onlyOneChild.path)" :class="{ 'submenu-title-noDropdown': !isNest }">
          <el-icon v-if="onlyOneChild.meta.icon || (item.meta && item.meta.icon)">
            <component :is="getIconComponent(onlyOneChild.meta.icon || (item.meta && item.meta.icon))" />
          </el-icon>
          <template #title><span class="menu-title" :title="hasTitle(onlyOneChild.meta.title)">{{ onlyOneChild.meta.title }}</span></template>
        </el-menu-item>
      </app-link>
    </template>

    <el-sub-menu v-else ref="subMenu" :index="resolvePath(item.path)" teleported>
      <template v-if="item.meta" #title>
        <el-icon v-if="item.meta && item.meta.icon">
          <component :is="getIconComponent(item.meta.icon)" />
        </el-icon>
        <span class="menu-title" :title="hasTitle(item.meta.title)">{{ item.meta.title }}</span>
      </template>

      <sidebar-item
        v-for="(child, index) in item.children"
        :key="child.path + index"
        :is-nest="true"
        :item="child"
        :base-path="resolvePath(child.path)"
        class="nest-menu"
      />
    </el-sub-menu>
  </div>
</template>

<script setup>
import { isExternal } from '@/utils/validate'
import AppLink from './Link'
import { getNormalPath } from '@/utils/ruoyi'
import { getIconComponent } from '@/utils/icon'

const props = defineProps({
  // route object
  item: {
    type: Object,
    required: true
  },
  isNest: {
    type: Boolean,
    default: false
  },
  basePath: {
    type: String,
    default: ''
  }
})

const onlyOneChild = ref({})

function hasOneShowingChild(children = [], parent) {
  if (!children) {
    children = []
  }
  const showingChildren = children.filter(item => {
    if (item.hidden) {
      return false
    }
    onlyOneChild.value = item
    return true
  })

  // When there is only one child router, the child router is displayed by default
  if (showingChildren.length === 1) {
    return true
  }

  // Show parent if there are no child router to display
  if (showingChildren.length === 0) {
    onlyOneChild.value = { ...parent, path: '', noShowingChildren: true }
    return true
  }

  return false
}

function resolvePath(routePath, routeQuery) {
  if (isExternal(routePath)) {
    return routePath
  }
  if (isExternal(props.basePath)) {
    return props.basePath
  }
  if (routeQuery) {
    let query = JSON.parse(routeQuery)
    return { path: getNormalPath(props.basePath + '/' + routePath), query: query }
  }
  return getNormalPath(props.basePath + '/' + routePath)
}

function hasTitle(title){
  if (title.length > 5) {
    return title
  } else {
    return ""
  }
}
</script>
