// ruoyi-react-web/src/views/monitor/operlog/index.jsx
import { useState, useEffect } from 'react'
import { Form, Input, Select, DatePicker, Button, Table, Modal, Space, Tooltip } from 'antd'
import { DeleteOutlined, DownloadOutlined, ReloadOutlined, SearchOutlined, EyeOutlined } from '@ant-design/icons'
import { list, delOperlog, cleanOperlog } from '@/api/monitor/operlog'
import { useDict } from '@/utils/dict'
import { parseTime, addDateRange } from '@/utils/ruoyi'
import { download } from '@/utils/request'
import dayjs from 'dayjs'
import modal from '@/plugins/modal'
import auth from '@/plugins/auth'
import Pagination from '@/components/Pagination'
import RightToolbar from '@/components/RightToolbar'
import DictTag from '@/components/DictTag'
import './index.scss'

const { RangePicker } = DatePicker

const Operlog = () => {
  const [queryForm] = Form.useForm()

  const [operlogList, setOperlogList] = useState([])
  const [loading, setLoading] = useState(true)
  const [showSearch, setShowSearch] = useState(true)
  const [selectedRowKeys, setSelectedRowKeys] = useState([])
  const [total, setTotal] = useState(0)
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState({})
  const [dateRange, setDateRange] = useState([])

  const { sys_oper_type = [], sys_common_status = [] } = useDict('sys_oper_type', 'sys_common_status')

  const [queryParams, setQueryParams] = useState({
    pageNum: 1,
    pageSize: 10,
    operIp: undefined,
    title: undefined,
    operName: undefined,
    businessType: undefined,
    status: undefined,
    orderByColumn: 'operTime',
    isAsc: 'desc'
  })

  useEffect(() => {
    getList()
  }, [queryParams, dateRange])

  // 查询操作日志列表
  const getList = async () => {
    setLoading(true)
    try {
      const params = addDateRange(queryParams, dateRange)
      const response = await list(params)
      setOperlogList(response.rows || [])
      setTotal(response.total || 0)
    } catch (error) {
      console.error('Failed to get operlog list:', error)
    } finally {
      setLoading(false)
    }
  }

  // 搜索
  const handleQuery = () => {
    const values = queryForm.getFieldsValue()
    setQueryParams(prev => ({
      ...prev,
      ...values,
      pageNum: 1
    }))
  }

  // 重置
  const resetQuery = () => {
    setDateRange([])
    queryForm.resetFields()
    setQueryParams(prev => ({
      ...prev,
      operIp: undefined,
      title: undefined,
      operName: undefined,
      businessType: undefined,
      status: undefined,
      orderByColumn: 'operTime',
      isAsc: 'desc',
      pageNum: 1
    }))
    getList()
  }

  // 分页变化
  const handlePagination = ({ page, limit }) => {
    setQueryParams(prev => ({
      ...prev,
      pageNum: page,
      pageSize: limit
    }))
  }

  // 表格选择变化
  const handleSelectionChange = (selectedRowKeys) => {
    setSelectedRowKeys(selectedRowKeys)
  }

  // 排序变化
  const handleTableChange = (pagination, filters, sorter) => {
    if (sorter.field) {
      setQueryParams(prev => ({
        ...prev,
        orderByColumn: sorter.field,
        isAsc: sorter.order === 'ascend' ? 'asc' : 'desc'
      }))
    }
  }

  // 详细
  const handleView = (row) => {
    setForm(row)
    setOpen(true)
  }

  // 删除
  const handleDelete = (row) => {
    const operIds = row?.operId || selectedRowKeys
    Modal.confirm({
      title: '提示',
      content: `是否确认删除日志编号为"${operIds}"的数据项?`,
      onOk: async () => {
        try {
          await delOperlog(operIds)
          modal.msgSuccess('删除成功')
          getList()
        } catch (error) {
          console.error('Failed to delete operlog:', error)
        }
      }
    })
  }

  // 清空
  const handleClean = () => {
    Modal.confirm({
      title: '提示',
      content: '是否确认清空所有操作日志数据项?',
      onOk: async () => {
        try {
          await cleanOperlog()
          modal.msgSuccess('清空成功')
          getList()
        } catch (error) {
          console.error('Failed to clean operlog:', error)
        }
      }
    })
  }

  // 导出
  const handleExport = () => {
    download('monitor/operlog/export', queryParams, `config_${new Date().getTime()}.xlsx`)
  }

  // 操作日志类型字典翻译
  const typeFormat = (row) => {
    const dict = sys_oper_type.sys_oper_type?.find(d => d.value === row.businessType)
    return dict ? dict.label : '-'
  }

  // 表格列定义
  const columns = [
    {
      title: '日志编号',
      dataIndex: 'operId',
      key: 'operId',
      align: 'center',
      width: 100
    },
    {
      title: '系统模块',
      dataIndex: 'title',
      key: 'title',
      align: 'left',
      ellipsis: true,
      minWidth: 150
    },
    {
      title: '操作类型',
      dataIndex: 'businessType',
      key: 'businessType',
      align: 'center',
      width: 120,
      render: (businessType) => (
        <DictTag options={sys_oper_type} value={businessType} />
      )
    },
    {
      title: '操作人员',
      dataIndex: 'operName',
      key: 'operName',
      align: 'left',
      ellipsis: true,
      minWidth: 120,
      sorter: true
    },
    {
      title: '操作地址',
      dataIndex: 'operIp',
      key: 'operIp',
      align: 'left',
      ellipsis: true,
      minWidth: 130
    },
    {
      title: '操作状态',
      dataIndex: 'status',
      key: 'status',
      align: 'center',
      width: 100,
      render: (status) => (
        <DictTag options={sys_common_status} value={status} />
      )
    },
    {
      title: '操作日期',
      dataIndex: 'operTime',
      key: 'operTime',
      align: 'center',
      width: 180,
      sorter: true,
      render: (text) => parseTime(text)
    },
    {
      title: '消耗时间',
      dataIndex: 'costTime',
      key: 'costTime',
      align: 'center',
      width: 110,
      ellipsis: true,
      sorter: true,
      render: (text) => `${text}毫秒`
    },
    {
      title: '操作',
      key: 'action',
      align: 'center',
      width: 100,
      fixed: 'right',
      render: (_, record) => (
        <Space size="small">
          {auth.hasPermiOr(['monitor:operlog:query']) && (
            <Tooltip title="详细">
              <Button
                type="link"
                icon={<EyeOutlined />}
                size="small"
                onClick={() => handleView(record)}
              >
                详细
              </Button>
            </Tooltip>
          )}
        </Space>
      )
    }
  ]

  const rowSelection = {
    selectedRowKeys,
    onChange: handleSelectionChange
  }

  return (
    <div className="app-container">
      <Form
        form={queryForm}
        layout="inline"
        className="search-form"
        style={{ display: showSearch ? 'flex' : 'none', marginBottom: 16 }}
      >
        <Form.Item label="操作地址" name="operIp">
          <Input
            placeholder="请输入操作地址"
            style={{ width: 200 }}
            onPressEnter={handleQuery}
            allowClear
          />
        </Form.Item>
        <Form.Item label="系统模块" name="title">
          <Input
            placeholder="请输入系统模块"
            style={{ width: 200 }}
            onPressEnter={handleQuery}
            allowClear
          />
        </Form.Item>
        <Form.Item label="操作人员" name="operName">
          <Input
            placeholder="请输入操作人员"
            style={{ width: 200 }}
            onPressEnter={handleQuery}
            allowClear
          />
        </Form.Item>
        <Form.Item label="类型" name="businessType">
          <Select
            placeholder="操作类型"
            style={{ width: 200 }}
            allowClear
          >
            {sys_oper_type.sys_oper_type?.map(dict => (
              <Select.Option key={dict.value} value={dict.value}>
                {dict.label}
              </Select.Option>
            ))}
          </Select>
        </Form.Item>
        <Form.Item label="状态" name="status">
          <Select
            placeholder="操作状态"
            style={{ width: 200 }}
            allowClear
          >
            {sys_common_status.map(dict => (
              <Select.Option key={dict.value} value={dict.value}>
                {dict.label}
              </Select.Option>
            ))}
          </Select>
        </Form.Item>
        <Form.Item label="操作时间">
          <RangePicker
            value={dateRange.length ? [dayjs(dateRange[0]), dayjs(dateRange[1])] : null}
            onChange={(dates) => {
              setDateRange(dates ? [dates[0].format('YYYY-MM-DD'), dates[1].format('YYYY-MM-DD')] : [])
            }}
            format="YYYY-MM-DD"
            style={{ width: 240 }}
          />
        </Form.Item>
        <Form.Item>
          <Button type="primary" icon={<SearchOutlined />} onClick={handleQuery}>
            搜索
          </Button>
          <Button icon={<ReloadOutlined />} onClick={resetQuery} style={{ marginLeft: 8 }}>
            重置
          </Button>
        </Form.Item>
      </Form>

      <div style={{ marginBottom: 16 }}>
        <Space>
          {auth.hasPermiOr(['monitor:operlog:remove']) && (
            <Button
              type="default"
              danger
              icon={<DeleteOutlined />}
              disabled={!selectedRowKeys.length}
              onClick={() => handleDelete()}
            >
              删除
            </Button>
          )}
          {auth.hasPermiOr(['monitor:operlog:remove']) && (
            <Button
              type="default"
              danger
              icon={<DeleteOutlined />}
              onClick={handleClean}
            >
              清空
            </Button>
          )}
          {auth.hasPermiOr(['monitor:operlog:export']) && (
            <Button type="default" icon={<DownloadOutlined />} onClick={handleExport}>
              导出
            </Button>
          )}
          <RightToolbar
            showSearch={showSearch}
            columns={{}}
            onShowSearchChange={setShowSearch}
            onQueryTable={getList}
          />
        </Space>
      </div>

      <Table
        loading={loading}
        dataSource={operlogList}
        columns={columns}
        rowSelection={rowSelection}
        rowKey="operId"
        onChange={handleTableChange}
        pagination={false}
      />

      <Pagination
        total={total}
        page={queryParams.pageNum}
        limit={queryParams.pageSize}
        onChange={handlePagination}
      />

      {/* 操作日志详细 */}
      <Modal
        title="操作日志详细"
        open={open}
        onCancel={() => setOpen(false)}
        footer={[
          <Button key="close" onClick={() => setOpen(false)}>
            关闭
          </Button>
        ]}
        width={800}
      >
        <Form labelCol={{ span: 6 }} wrapperCol={{ span: 18 }}>
          <Form.Item label="操作模块">
            {form.title} / {typeFormat(form)}
          </Form.Item>
          <Form.Item label="登录信息">
            {form.operName} / {form.operIp} / {form.operLocation}
          </Form.Item>
          <Form.Item label="请求地址">
            {form.operUrl}
          </Form.Item>
          <Form.Item label="请求方式">
            {form.requestMethod}
          </Form.Item>
          <Form.Item label="操作方法">
            {form.method}
          </Form.Item>
          <Form.Item label="请求参数">
            {form.operParam}
          </Form.Item>
          <Form.Item label="返回参数">
            {form.jsonResult}
          </Form.Item>
          <Form.Item label="操作状态">
            {form.status === 0 ? '正常' : form.status === 1 ? '失败' : '-'}
          </Form.Item>
          <Form.Item label="消耗时间">
            {form.costTime}毫秒
          </Form.Item>
          <Form.Item label="操作时间">
            {parseTime(form.operTime)}
          </Form.Item>
          {form.status === 1 && (
            <Form.Item label="异常信息">
              {form.errorMsg}
            </Form.Item>
          )}
        </Form>
      </Modal>
    </div>
  )
}

export default Operlog

// ruoyi-front/src/views/monitor/operlog/index.vue
<template>
   <div class="app-container">
      <!-- 搜索表单 -->
      <el-form :model="queryParams" ref="queryRef" :inline="true" v-show="showSearch" label-width="70px" class="search-form">
         <el-form-item label="操作地址" prop="operIp">
            <el-input
               v-model="queryParams.operIp"
               placeholder="请输入操作地址"
               clearable
               style="width: 200px"
               @keyup.enter="handleQuery"
            />
         </el-form-item>
         <el-form-item label="系统模块" prop="title">
            <el-input
               v-model="queryParams.title"
               placeholder="请输入系统模块"
               clearable
               style="width: 200px"
               @keyup.enter="handleQuery"
            />
         </el-form-item>
         <el-form-item label="操作人员" prop="operName">
            <el-input
               v-model="queryParams.operName"
               placeholder="请输入操作人员"
               clearable
               style="width: 200px"
               @keyup.enter="handleQuery"
            />
         </el-form-item>
         <el-form-item label="类型" prop="businessType">
            <el-select
               v-model="queryParams.businessType"
               placeholder="操作类型"
               clearable
               style="width: 200px"
            >
               <el-option
                  v-for="dict in sys_oper_type"
                  :key="dict.value"
                  :label="dict.label"
                  :value="dict.value"
               />
            </el-select>
         </el-form-item>
         <el-form-item label="状态" prop="status">
            <el-select
               v-model="queryParams.status"
               placeholder="操作状态"
               clearable
               style="width: 200px"
            >
               <el-option
                  v-for="dict in sys_common_status"
                  :key="dict.value"
                  :label="dict.label"
                  :value="dict.value"
               />
            </el-select>
         </el-form-item>
         <el-form-item label="操作时间">
            <el-date-picker
               v-model="dateRange"
               value-format="YYYY-MM-DD HH:mm:ss"
               type="daterange"
               range-separator="至"
               start-placeholder="开始日期"
               end-placeholder="结束日期"
               style="width: 240px"
               :default-time="[new Date(2000, 1, 1, 0, 0, 0), new Date(2000, 1, 1, 23, 59, 59)]"
            />
         </el-form-item>
         <el-form-item>
            <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
            <el-button icon="Refresh" @click="resetQuery">重置</el-button>
         </el-form-item>
      </el-form>

      <el-row :gutter="10" class="mb8">
         <el-col :span="1.5">
            <el-button
               type="danger"
               plain
               icon="Delete"
               :disabled="multiple"
               @click="handleDelete"
               v-hasPermi="['monitor:operlog:remove']"
            >删除</el-button>
         </el-col>
         <el-col :span="1.5">
            <el-button
               type="danger"
               plain
               icon="Delete"
               @click="handleClean"
               v-hasPermi="['monitor:operlog:remove']"
            >清空</el-button>
         </el-col>
         <el-col :span="1.5">
            <el-button
               type="warning"
               plain
               icon="Download"
               @click="handleExport"
               v-hasPermi="['monitor:operlog:export']"
            >导出</el-button>
         </el-col>
         <right-toolbar v-model:showSearch="showSearch" @queryTable="getList"></right-toolbar>
      </el-row>

      <!-- 数据表格 -->
      <el-table 
         ref="operlogRef" 
         v-loading="loading" 
         :data="operlogList" 
         @selection-change="handleSelectionChange" 
         :default-sort="defaultSort" 
         @sort-change="handleSortChange"
         stripe
         style="width: 100%"
         class="operlog-table"
      >
         <el-table-column type="selection" width="55" align="center" />
         <el-table-column label="日志编号" align="center" prop="operId" width="100" />
         <el-table-column label="系统模块" align="left" prop="title" min-width="150" :show-overflow-tooltip="true" />
         <el-table-column label="操作类型" align="center" prop="businessType" width="120">
            <template #default="scope">
               <dict-tag :options="sys_oper_type" :value="scope.row.businessType" />
            </template>
         </el-table-column>
         <el-table-column label="操作人员" align="left" prop="operName" min-width="120" :show-overflow-tooltip="true" sortable="custom" :sort-orders="['descending', 'ascending']" />
         <el-table-column label="操作地址" align="left" prop="operIp" min-width="130" :show-overflow-tooltip="true" />
         <el-table-column label="操作状态" align="center" prop="status" width="100">
            <template #default="scope">
               <dict-tag :options="sys_common_status" :value="scope.row.status" />
            </template>
         </el-table-column>
         <el-table-column label="操作日期" align="center" prop="operTime" width="180" sortable="custom" :sort-orders="['descending', 'ascending']">
            <template #default="scope">
               <span>{{ parseTime(scope.row.operTime) }}</span>
            </template>
         </el-table-column>
         <el-table-column label="消耗时间" align="center" prop="costTime" width="110" :show-overflow-tooltip="true" sortable="custom" :sort-orders="['descending', 'ascending']">
            <template #default="scope">
               <span>{{ scope.row.costTime }}毫秒</span>
            </template>
         </el-table-column>
         <el-table-column label="操作" align="center" width="100" fixed="right">
            <template #default="scope">
               <div class="action-buttons">
                  <el-button 
                     link 
                     type="primary" 
                     icon="View" 
                     size="small"
                     @click.stop="handleView(scope.row, scope.index)" 
                     v-hasPermi="['monitor:operlog:query']"
                  >详细</el-button>
               </div>
            </template>
         </el-table-column>
      </el-table>

      <pagination
         v-show="total > 0"
         :total="total"
         v-model:page="queryParams.pageNum"
         v-model:limit="queryParams.pageSize"
         @pagination="getList"
      />

      <!-- 操作日志详细 -->
      <el-dialog title="操作日志详细" v-model="open" width="800px" append-to-body :close-on-click-modal="false">
         <el-form :model="form" label-width="100px" class="operlog-form">
            <el-row>
               <el-col :span="12">
                  <el-form-item label="操作模块：">{{ form.title }} / {{ typeFormat(form) }}</el-form-item>
                  <el-form-item label="登录信息：">{{ form.operName }} / {{ form.operIp }} / {{ form.operLocation }}</el-form-item>
               </el-col>
               <el-col :span="12">
                  <el-form-item label="请求地址：">{{ form.operUrl }}</el-form-item>
                  <el-form-item label="请求方式：">{{ form.requestMethod }}</el-form-item>
               </el-col>
               <el-col :span="24">
                  <el-form-item label="操作方法：">{{ form.method }}</el-form-item>
               </el-col>
               <el-col :span="24">
                  <el-form-item label="请求参数：">{{ form.operParam }}</el-form-item>
               </el-col>
               <el-col :span="24">
                  <el-form-item label="返回参数：">{{ form.jsonResult }}</el-form-item>
               </el-col>
               <el-col :span="8">
                  <el-form-item label="操作状态：">
                     <div v-if="form.status === 0">正常</div>
                     <div v-else-if="form.status === 1">失败</div>
                  </el-form-item>
               </el-col>
               <el-col :span="8">
                  <el-form-item label="消耗时间：">{{ form.costTime }}毫秒</el-form-item>
               </el-col>
               <el-col :span="8">
                  <el-form-item label="操作时间：">{{ parseTime(form.operTime) }}</el-form-item>
               </el-col>
               <el-col :span="24">
                  <el-form-item label="异常信息：" v-if="form.status === 1">{{ form.errorMsg }}</el-form-item>
               </el-col>
            </el-row>
         </el-form>
         <template #footer>
            <div class="dialog-footer">
               <el-button @click="open = false">关 闭</el-button>
            </div>
         </template>
      </el-dialog>
   </div>
</template>

<script setup name="Operlog">
import { list, delOperlog, cleanOperlog } from "@/api/monitor/operlog"

const { proxy } = getCurrentInstance()
const { sys_oper_type, sys_common_status } = proxy.useDict("sys_oper_type", "sys_common_status")

const operlogList = ref([])
const open = ref(false)
const loading = ref(true)
const showSearch = ref(true)
const ids = ref([])
const single = ref(true)
const multiple = ref(true)
const total = ref(0)
const title = ref("")
const dateRange = ref([])
const defaultSort = ref({ prop: "operTime", order: "descending" })

const data = reactive({
  form: {},
  queryParams: {
    pageNum: 1,
    pageSize: 10,
    operIp: undefined,
    title: undefined,
    operName: undefined,
    businessType: undefined,
    status: undefined
  }
})

const { queryParams, form } = toRefs(data)

/** 查询登录日志 */
function getList() {
  loading.value = true
  list(proxy.addDateRange(queryParams.value, dateRange.value)).then(response => {
    operlogList.value = response.rows
    total.value = response.total
    loading.value = false
  })
}

/** 操作日志类型字典翻译 */
function typeFormat(row, column) {
  return proxy.selectDictLabel(sys_oper_type.value, row.businessType)
}

/** 搜索按钮操作 */
function handleQuery() {
  queryParams.value.pageNum = 1
  getList()
}

/** 重置按钮操作 */
function resetQuery() {
  dateRange.value = []
  proxy.resetForm("queryRef")
  queryParams.value.pageNum = 1
  proxy.$refs["operlogRef"].sort(defaultSort.value.prop, defaultSort.value.order)
}

/** 多选框选中数据 */
function handleSelectionChange(selection) {
  ids.value = selection.map(item => item.operId)
  multiple.value = !selection.length
}

/** 排序触发事件 */
function handleSortChange(column, prop, order) {
  queryParams.value.orderByColumn = column.prop
  queryParams.value.isAsc = column.order
  getList()
}

/** 详细按钮操作 */
function handleView(row) {
  open.value = true
  form.value = row
}

/** 删除按钮操作 */
function handleDelete(row) {
  const operIds = row.operId || ids.value
  proxy.$modal.confirm('是否确认删除日志编号为"' + operIds + '"的数据项?').then(function () {
    return delOperlog(operIds)
  }).then(() => {
    getList()
    proxy.$modal.msgSuccess("删除成功")
  }).catch(() => {})
}

/** 清空按钮操作 */
function handleClean() {
  proxy.$modal.confirm("是否确认清空所有操作日志数据项?").then(function () {
    return cleanOperlog()
  }).then(() => {
    getList()
    proxy.$modal.msgSuccess("清空成功")
  }).catch(() => {})
}

/** 导出按钮操作 */
function handleExport() {
  proxy.download("monitor/operlog/export",{
    ...queryParams.value,
  }, `config_${new Date().getTime()}.xlsx`)
}

getList()
</script>

<style scoped lang="scss">
.search-form {
  margin-bottom: 16px;
  
  .el-form-item {
    margin-bottom: 16px;
  }
}

.action-buttons {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  white-space: nowrap;
  
  .el-button {
    padding: 0 8px;
  }
}

.operlog-table {
  :deep(.el-table__row) {
    cursor: pointer;
    
    &:hover {
      background-color: var(--el-table-row-hover-bg-color);
    }
  }
}

.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
}

.operlog-form {
  :deep(.el-form-item) {
    margin-bottom: 22px;
  }
}

:deep(.el-table) {
  .el-table__header {
    th {
      background-color: var(--el-table-header-bg-color);
      font-weight: 500;
    }
  }
}

:deep(.el-dialog__body) {
  padding: 24px 28px;
}

:deep(.el-dialog__header) {
  padding: 20px 28px 16px;
  border-bottom: 1px solid var(--el-border-color-lighter);
}

:deep(.el-dialog__footer) {
  padding: 16px 28px 20px;
  border-top: 1px solid var(--el-border-color-lighter);
}
</style>
