// ruoyi-front-vue/src/views/system/dept/index.vue
<template>
   <div class="app-container">
      <el-form :model="queryParams" ref="queryRef" :inline="true" v-show="showSearch" class="search-form">
         <el-form-item label="部门名称" prop="deptName">
            <el-input
               v-model="queryParams.deptName"
               placeholder="请输入部门名称"
               clearable
               style="width: 200px"
               @keyup.enter="handleQuery"
            />
         </el-form-item>
         <el-form-item label="状态" prop="status">
            <el-select v-model="queryParams.status" placeholder="部门状态" clearable style="width: 200px">
               <el-option
                  v-for="dict in sys_normal_disable"
                  :key="dict.value"
                  :label="dict.label"
                  :value="dict.value"
               />
            </el-select>
         </el-form-item>
         <el-form-item>
            <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
            <el-button icon="Refresh" @click="resetQuery">重置</el-button>
         </el-form-item>
      </el-form>

      <el-row :gutter="10" class="mb8">
         <el-col :span="1.5">
            <el-button
               type="primary"
               plain
               icon="Plus"
               @click="handleAdd"
               v-hasPermi="['system:dept:add']"
            >新增</el-button>
         </el-col>
         <el-col :span="1.5">
            <el-button
               type="info"
               plain
               icon="Sort"
               @click="toggleExpandAll"
            >展开/折叠</el-button>
         </el-col>
         <right-toolbar v-model:showSearch="showSearch" @queryTable="getList"></right-toolbar>
      </el-row>

      <el-table
         v-if="refreshTable"
         v-loading="loading"
         :data="deptList"
         row-key="deptId"
         :default-expand-all="isExpandAll"
         :tree-props="{ children: 'children', hasChildren: 'hasChildren' }"
         @row-dblclick="handleRowDblClick"
         @row-click="handleRowClick"
         stripe
         style="width: 100%"
         class="dept-table"
      >
         <el-table-column prop="deptName" label="部门名称" min-width="200" :show-overflow-tooltip="true"></el-table-column>
         <el-table-column prop="orderNum" label="排序" align="center" width="100"></el-table-column>
         <el-table-column prop="status" label="状态" align="center" width="100">
            <template #default="scope">
               <dict-tag :options="sys_normal_disable" :value="scope.row.status" />
            </template>
         </el-table-column>
         <el-table-column label="创建时间" align="center" prop="createTime" width="180">
            <template #default="scope">
               <span>{{ parseTime(scope.row.createTime) }}</span>
            </template>
         </el-table-column>
         <el-table-column label="操作" align="center" fixed="right" width="210">
            <template #default="scope">
               <div class="action-buttons">
                  <el-button 
                     link 
                     type="primary" 
                     icon="Edit" 
                     size="small"
                     @click.stop="handleUpdate(scope.row)" 
                     v-hasPermi="['system:dept:edit']"
                  >修改</el-button>
                  <el-button 
                     link 
                     type="primary" 
                     icon="Plus" 
                     size="small"
                     @click.stop="handleAdd(scope.row)" 
                     v-hasPermi="['system:dept:add']"
                  >新增</el-button>
                  <el-button 
                     v-if="scope.row.parentId != 0" 
                     link 
                     type="danger" 
                     icon="Delete" 
                     size="small"
                     @click.stop="handleDelete(scope.row)" 
                     v-hasPermi="['system:dept:remove']"
                  >删除</el-button>
               </div>
            </template>
         </el-table-column>
      </el-table>

      <!-- 添加或修改部门对话框 -->
      <el-dialog :title="title" v-model="open" width="600px" append-to-body :close-on-click-modal="false">
         <el-form ref="deptRef" :model="form" :rules="rules" label-width="80px" class="dept-form">
            <el-row>
               <el-col :span="24" v-if="form.parentId !== 0">
                  <el-form-item label="上级部门" prop="parentId">
                     <el-tree-select
                        v-model="form.parentId"
                        :data="deptOptions"
                        :props="{ value: 'deptId', label: 'deptName', children: 'children' }"
                        value-key="deptId"
                        placeholder="选择上级部门"
                        check-strictly
                     />
                  </el-form-item>
               </el-col>
               <el-col :span="12">
                  <el-form-item label="部门名称" prop="deptName">
                     <el-input v-model="form.deptName" placeholder="请输入部门名称" />
                  </el-form-item>
               </el-col>
               <el-col :span="12">
                  <el-form-item label="显示排序" prop="orderNum">
                     <el-input-number v-model="form.orderNum" controls-position="right" :min="0" />
                  </el-form-item>
               </el-col>
               <el-col :span="12">
                  <el-form-item label="负责人" prop="leader">
                     <el-input v-model="form.leader" placeholder="请输入负责人" maxlength="20" />
                  </el-form-item>
               </el-col>
               <el-col :span="12">
                  <el-form-item label="联系电话" prop="phone">
                     <el-input v-model="form.phone" placeholder="请输入联系电话" maxlength="11" />
                  </el-form-item>
               </el-col>
               <el-col :span="12">
                  <el-form-item label="邮箱" prop="email">
                     <el-input v-model="form.email" placeholder="请输入邮箱" maxlength="50" />
                  </el-form-item>
               </el-col>
               <el-col :span="12">
                  <el-form-item label="部门状态">
                     <el-radio-group v-model="form.status">
                        <el-radio
                           v-for="dict in sys_normal_disable"
                           :key="dict.value"
                           :value="dict.value"
                        >{{ dict.label }}</el-radio>
                     </el-radio-group>
                  </el-form-item>
               </el-col>
            </el-row>
         </el-form>
         <template #footer>
            <div class="dialog-footer">
               <el-button @click="cancel">取 消</el-button>
               <el-button type="primary" @click="submitForm">确 定</el-button>
            </div>
         </template>
      </el-dialog>
   </div>
</template>

<script setup name="Dept">
import { listDept, getDept, delDept, addDept, updateDept, listDeptExcludeChild } from "@/api/system/dept"

const { proxy } = getCurrentInstance()
const { sys_normal_disable } = proxy.useDict("sys_normal_disable")

const deptList = ref([])
const open = ref(false)
const loading = ref(true)
const showSearch = ref(true)
const title = ref("")
const deptOptions = ref([])
const isExpandAll = ref(true)
const refreshTable = ref(true)

const data = reactive({
  form: {},
  queryParams: {
    deptName: undefined,
    status: undefined
  },
  rules: {
    parentId: [{ required: true, message: "上级部门不能为空", trigger: "blur" }],
    deptName: [{ required: true, message: "部门名称不能为空", trigger: "blur" }],
    orderNum: [{ required: true, message: "显示排序不能为空", trigger: "blur" }],
    email: [{ type: "email", message: "请输入正确的邮箱地址", trigger: ["blur", "change"] }],
    phone: [{ pattern: /^1[3|4|5|6|7|8|9][0-9]\d{8}$/, message: "请输入正确的手机号码", trigger: "blur" }]
  },
})

const { queryParams, form, rules } = toRefs(data)

/** 查询部门列表 */
function getList() {
  loading.value = true
  listDept(queryParams.value).then(response => {
    deptList.value = proxy.handleTree(response.data, "deptId")
    loading.value = false
  })
}

/** 取消按钮 */
function cancel() {
  open.value = false
  reset()
}

/** 表单重置 */
function reset() {
  form.value = {
    deptId: undefined,
    parentId: undefined,
    deptName: undefined,
    orderNum: 0,
    leader: undefined,
    phone: undefined,
    email: undefined,
    status: "0"
  }
  proxy.resetForm("deptRef")
}

/** 搜索按钮操作 */
function handleQuery() {
  getList()
}

/** 重置按钮操作 */
function resetQuery() {
  proxy.resetForm("queryRef")
  handleQuery()
}

/** 新增按钮操作 */
function handleAdd(row) {
  reset()
  listDept().then(response => {
    deptOptions.value = proxy.handleTree(response.data, "deptId")
  })
  if (row != undefined) {
    form.value.parentId = row.deptId
  }
  open.value = true
  title.value = "添加部门"
}

/** 展开/折叠操作 */
function toggleExpandAll() {
  refreshTable.value = false
  isExpandAll.value = !isExpandAll.value
  nextTick(() => {
    refreshTable.value = true
  })
}

/** 单击行操作（用于选中） */
function handleRowClick(row, column, event) {
  if (event?.target?.closest('.action-buttons')) {
    return
  }
}

/** 双击行操作 */
function handleRowDblClick(row, column, event) {
  if (event?.target?.closest('.action-buttons')) {
    return
  }
  if (proxy.hasPermi(['system:dept:edit'])) {
    handleUpdate(row)
  }
}

/** 修改按钮操作 */
function handleUpdate(row) {
  reset()
  if (!row || !row.deptId) {
    proxy.$modal.msgWarning("请选择要修改的部门")
    return
  }
  
  listDeptExcludeChild(row.deptId).then(response => {
    deptOptions.value = proxy.handleTree(response.data, "deptId")
  })
  getDept(row.deptId).then(response => {
    form.value = response.data
    open.value = true
    title.value = "修改部门"
  }).catch(error => {
    console.error("获取部门信息失败:", error)
    proxy.$modal.msgError("获取部门信息失败")
  })
}

/** 提交按钮 */
function submitForm() {
  proxy.$refs["deptRef"].validate(valid => {
    if (valid) {
      if (form.value.deptId != undefined) {
        updateDept(form.value).then(response => {
          proxy.$modal.msgSuccess("修改成功")
          open.value = false
          getList()
        })
      } else {
        addDept(form.value).then(response => {
          proxy.$modal.msgSuccess("新增成功")
          open.value = false
          getList()
        })
      }
    }
  })
}

/** 删除按钮操作 */
function handleDelete(row) {
  proxy.$modal.confirm('是否确认删除名称为"' + row.deptName + '"的数据项?').then(function() {
    return delDept(row.deptId)
  }).then(() => {
    getList()
    proxy.$modal.msgSuccess("删除成功")
  }).catch(() => {})
}

getList()
</script>

<style scoped lang="scss">
.search-form {
  margin-bottom: 16px;
  
  .el-form-item {
    margin-bottom: 16px;
  }
}

.action-buttons {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  white-space: nowrap;
  
  .el-button {
    padding: 0 8px;
  }
}

.dept-table {
  :deep(.el-table__row) {
    cursor: pointer;
    
    &:hover {
      background-color: var(--el-table-row-hover-bg-color);
    }
  }
}

.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
}

.dept-form {
  :deep(.el-form-item) {
    margin-bottom: 22px;
  }
}

:deep(.el-table) {
  .el-table__header {
    th {
      background-color: var(--el-table-header-bg-color);
      font-weight: 500;
    }
  }
}

:deep(.el-dialog__body) {
  padding: 24px 28px;
}

:deep(.el-dialog__header) {
  padding: 20px 28px 16px;
  border-bottom: 1px solid var(--el-border-color-lighter);
}

:deep(.el-dialog__footer) {
  padding: 16px 28px 20px;
  border-top: 1px solid var(--el-border-color-lighter);
}
</style>

// ruoyi-react-web/src/views/system/dept/index.jsx
import { useState, useEffect } from 'react'
import { Form, Input, InputNumber, Select, Button, Table, Modal, Radio, Space } from 'antd'
import { PlusOutlined, EditOutlined, DeleteOutlined, SearchOutlined, ReloadOutlined, SortAscendingOutlined } from '@ant-design/icons'
import { listDept, getDept, addDept, updateDept, delDept, listDeptExcludeChild } from '@/api/system/dept'
import { useDict } from '@/utils/dict'
import { parseTime, handleTree } from '@/utils/ruoyi'
import modal from '@/plugins/modal'
import auth from '@/plugins/auth'
import RightToolbar from '@/components/RightToolbar'
import { TreeSelect } from 'antd'
import './index.scss'

const Dept = () => {
  const [form] = Form.useForm()
  const [queryForm] = Form.useForm()

  const [deptList, setDeptList] = useState([])
  const [loading, setLoading] = useState(true)
  const [showSearch, setShowSearch] = useState(true)
  const [open, setOpen] = useState(false)
  const [title, setTitle] = useState('')
  const [deptOptions, setDeptOptions] = useState([])
  const [isExpandAll, setIsExpandAll] = useState(true)
  const [refreshTable, setRefreshTable] = useState(true)

  const sys_normal_disable = useDict('sys_normal_disable')

  const [queryParams, setQueryParams] = useState({
    deptName: undefined,
    status: undefined
  })

  useEffect(() => {
    getList()
  }, [queryParams])

  // 查询部门列表
  const getList = async () => {
    setLoading(true)
    try {
      const response = await listDept(queryParams)
      const treeData = handleTree(response.data, 'deptId')
      setDeptList(treeData || [])
    } catch (error) {
      console.error('Failed to get dept list:', error)
    } finally {
      setLoading(false)
    }
  }

  // 搜索
  const handleQuery = () => {
    const values = queryForm.getFieldsValue()
    setQueryParams(prev => ({
      ...prev,
      ...values
    }))
  }

  // 重置
  const resetQuery = () => {
    queryForm.resetFields()
    setQueryParams({
      deptName: undefined,
      status: undefined
    })
    getList()
  }

  // 新增
  const handleAdd = async (row) => {
    reset()
    try {
      const response = await listDept()
      const treeData = handleTree(response.data, 'deptId')
      setDeptOptions(treeData || [])
    } catch (error) {
      console.error('Failed to get dept tree:', error)
    }
    
    if (row != undefined) {
      form.setFieldValue('parentId', row.deptId)
    } else {
      // 根部门默认 parentId=0，避免后端 parentId 为 null
      form.setFieldValue('parentId', 0)
    }
    setOpen(true)
    setTitle('添加部门')
  }

  // 修改
  const handleUpdate = async (row) => {
    reset()
    if (!row || !row.deptId) {
      modal.msgWarning('请选择要修改的部门')
      return
    }

    try {
      const excludeResponse = await listDeptExcludeChild(row.deptId)
      const treeData = handleTree(excludeResponse.data, 'deptId')
      setDeptOptions(treeData || [])
      
      const deptResponse = await getDept(row.deptId)
      form.setFieldsValue(deptResponse.data)
      setOpen(true)
      setTitle('修改部门')
    } catch (error) {
      console.error('Failed to get dept:', error)
      modal.msgError('获取部门信息失败')
    }
  }

  // 删除
  const handleDelete = (row) => {
    Modal.confirm({
      title: '提示',
      content: `是否确认删除名称为"${row.deptName}"的数据项?`,
      onOk: async () => {
        try {
          await delDept(row.deptId)
          modal.msgSuccess('删除成功')
          getList()
        } catch (error) {
          console.error('Failed to delete dept:', error)
        }
      }
    })
  }

  // 展开/折叠
  const toggleExpandAll = () => {
    setRefreshTable(false)
    setIsExpandAll(!isExpandAll)
    setTimeout(() => {
      setRefreshTable(true)
    }, 100)
  }

  // 表单重置
  const reset = () => {
    form.resetFields()
    form.setFieldsValue({
      deptId: undefined,
      // 默认根节点
      parentId: 0,
      deptName: undefined,
      orderNum: 0,
      leader: undefined,
      phone: undefined,
      email: undefined,
      status: '0'
    })
  }

  // 取消
  const cancel = () => {
    setOpen(false)
    reset()
  }

  // 提交表单
  const submitForm = async () => {
    try {
      const values = await form.validateFields()
      if (values.deptId !== undefined && values.deptId !== null && values.deptId !== '') {
        await updateDept(values)
        modal.msgSuccess('修改成功')
      } else {
        await addDept(values)
        modal.msgSuccess('新增成功')
      }
      setOpen(false)
      getList()
    } catch (error) {
      console.error('Validation failed:', error)
    }
  }

  // 双击行
  const handleRowDblClick = (row) => {
    if (auth.hasPermiOr(['system:dept:edit'])) {
      handleUpdate(row)
    }
  }

  // 表格列定义
  const columns = [
    {
      title: '部门名称',
      dataIndex: 'deptName',
      key: 'deptName',
      ellipsis: true,
      minWidth: 200
    },
    {
      title: '排序',
      dataIndex: 'orderNum',
      key: 'orderNum',
      align: 'center',
      width: 100
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      align: 'center',
      width: 100,
      render: (status) => {
        const dict = sys_normal_disable.sys_normal_disable?.find(d => d.value === status)
        return dict ? dict.label : '-'
      }
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      key: 'createTime',
      align: 'center',
      width: 180,
      render: (text) => parseTime(text)
    },
    {
      title: '操作',
      key: 'action',
      align: 'center',
      fixed: 'right',
      width: 210,
      render: (_, record) => (
        <Space size="small">
          {auth.hasPermiOr(['system:dept:edit']) && (
            <Button
              type="link"
              icon={<EditOutlined />}
              size="small"
              onClick={(e) => {
                e.stopPropagation()
                handleUpdate(record)
              }}
            >
              修改
            </Button>
          )}
          {auth.hasPermiOr(['system:dept:add']) && (
            <Button
              type="link"
              icon={<PlusOutlined />}
              size="small"
              onClick={(e) => {
                e.stopPropagation()
                handleAdd(record)
              }}
            >
              新增
            </Button>
          )}
          {record.parentId != 0 && auth.hasPermiOr(['system:dept:remove']) && (
            <Button
              type="link"
              danger
              icon={<DeleteOutlined />}
              size="small"
              onClick={(e) => {
                e.stopPropagation()
                handleDelete(record)
              }}
            >
              删除
            </Button>
          )}
        </Space>
      )
    }
  ]

  return (
    <div className="app-container">
      <Form
        form={queryForm}
        layout="inline"
        className="search-form"
        style={{ display: showSearch ? 'flex' : 'none', marginBottom: 16 }}
      >
        <Form.Item label="部门名称" name="deptName">
          <Input
            placeholder="请输入部门名称"
            style={{ width: 200 }}
            onPressEnter={handleQuery}
            allowClear
          />
        </Form.Item>
        <Form.Item label="状态" name="status">
          <Select
            placeholder="部门状态"
            style={{ width: 200 }}
            allowClear
          >
            {sys_normal_disable.sys_normal_disable?.map(dict => (
              <Select.Option key={dict.value} value={dict.value}>
                {dict.label}
              </Select.Option>
            ))}
          </Select>
        </Form.Item>
        <Form.Item>
          <Button type="primary" icon={<SearchOutlined />} onClick={handleQuery}>
            搜索
          </Button>
          <Button icon={<ReloadOutlined />} onClick={resetQuery} style={{ marginLeft: 8 }}>
            重置
          </Button>
        </Form.Item>
      </Form>

      <div style={{ marginBottom: 16 }}>
        <Space>
          {auth.hasPermiOr(['system:dept:add']) && (
            <Button type="primary" icon={<PlusOutlined />} onClick={() => handleAdd()}>
              新增
            </Button>
          )}
          <Button type="default" icon={<SortAscendingOutlined />} onClick={toggleExpandAll}>
            展开/折叠
          </Button>
          <RightToolbar
            showSearch={showSearch}
            columns={{}}
            onShowSearchChange={setShowSearch}
            onQueryTable={getList}
          />
        </Space>
      </div>

      {refreshTable && (
        <Table
          loading={loading}
          dataSource={deptList}
          columns={columns}
          rowKey="deptId"
          defaultExpandAllRows={isExpandAll}
          onRow={(record) => ({
            onDoubleClick: () => handleRowDblClick(record)
          })}
          pagination={false}
        />
      )}

      {/* 添加或修改部门对话框 */}
      <Modal
        title={title}
        open={open}
        onCancel={cancel}
        onOk={submitForm}
        width={600}
        destroyOnHidden
      >
        <Form
          form={form}
          labelCol={{ span: 6 }}
          wrapperCol={{ span: 18 }}
        >
          {/* 关键：编辑时需要带上 deptId，否则 submitForm 会误判为新增 */}
          <Form.Item name="deptId" hidden>
            <Input />
          </Form.Item>

          {form.getFieldValue('parentId') !== 0 && (
            <Form.Item
              label="上级部门"
              name="parentId"
              rules={[{ required: true, message: '上级部门不能为空' }]}
            >
              <TreeSelect
                treeData={deptOptions}
                fieldNames={{ label: 'deptName', value: 'deptId', children: 'children' }}
                placeholder="选择上级部门"
                treeDefaultExpandAll
                allowClear
              />
            </Form.Item>
          )}
          <Form.Item
            label="部门名称"
            name="deptName"
            rules={[{ required: true, message: '部门名称不能为空' }]}
          >
            <Input placeholder="请输入部门名称" />
          </Form.Item>
          <Form.Item
            label="显示排序"
            name="orderNum"
            rules={[{ required: true, message: '显示排序不能为空' }]}
          >
            <InputNumber min={0} style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item label="负责人" name="leader">
            <Input placeholder="请输入负责人" maxLength={20} />
          </Form.Item>
          <Form.Item
            label="联系电话"
            name="phone"
            rules={[
              { pattern: /^1[3|4|5|6|7|8|9][0-9]\d{8}$/, message: '请输入正确的手机号码' }
            ]}
          >
            <Input placeholder="请输入联系电话" maxLength={11} />
          </Form.Item>
          <Form.Item
            label="邮箱"
            name="email"
            rules={[{ type: 'email', message: '请输入正确的邮箱地址' }]}
          >
            <Input placeholder="请输入邮箱" maxLength={50} />
          </Form.Item>
          <Form.Item label="部门状态" name="status">
            <Radio.Group>
              {sys_normal_disable.sys_normal_disable?.map(dict => (
                <Radio key={dict.value} value={dict.value}>
                  {dict.label}
                </Radio>
              ))}
            </Radio.Group>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

export default Dept
