// ruoyi-front-vue/src/views/system/user/profile/resetPwd.vue
<template>
   <el-form ref="pwdRef" :model="user" :rules="rules" label-width="100px" class="reset-pwd-form">
      <el-form-item label="旧密码" prop="oldPassword">
         <el-input 
            v-model="user.oldPassword" 
            placeholder="请输入旧密码" 
            type="password" 
            show-password 
            clearable
         />
      </el-form-item>
      <el-form-item label="新密码" prop="newPassword">
         <el-input 
            v-model="user.newPassword" 
            placeholder="请输入新密码（6-20个字符）" 
            type="password" 
            show-password 
            clearable
         />
         <div class="form-tip">密码长度必须在 6 到 20 个字符之间</div>
      </el-form-item>
      <el-form-item label="确认密码" prop="confirmPassword">
         <el-input 
            v-model="user.confirmPassword" 
            placeholder="请再次输入新密码" 
            type="password" 
            show-password
            clearable
         />
      </el-form-item>
      <el-form-item>
         <div class="form-actions">
            <el-button @click="close">取 消</el-button>
            <el-button type="primary" @click="submit">保 存</el-button>
         </div>
      </el-form-item>
   </el-form>
</template>

<script setup>
import { updateUserPwd } from "@/api/system/user"

const { proxy } = getCurrentInstance()

const user = reactive({
  oldPassword: undefined,
  newPassword: undefined,
  confirmPassword: undefined
})

const equalToPassword = (rule, value, callback) => {
  if (user.newPassword !== value) {
    callback(new Error("两次输入的密码不一致"))
  } else {
    callback()
  }
}

const rules = ref({
  oldPassword: [{ required: true, message: "旧密码不能为空", trigger: "blur" }],
  newPassword: [{ required: true, message: "新密码不能为空", trigger: "blur" }, { min: 6, max: 20, message: "长度在 6 到 20 个字符", trigger: "blur" }, { pattern: /^[^<>"'|\\]+$/, message: "不能包含非法字符：< > \" ' \\\ |", trigger: "blur" }],
  confirmPassword: [{ required: true, message: "确认密码不能为空", trigger: "blur" }, { required: true, validator: equalToPassword, trigger: "blur" }]
})

/** 提交按钮 */
function submit() {
  proxy.$refs.pwdRef.validate(valid => {
    if (valid) {
      updateUserPwd(user.oldPassword, user.newPassword).then(response => {
        proxy.$modal.msgSuccess("修改成功")
      })
    }
  })
}

/** 关闭按钮 */
function close() {
  proxy.$tab.closePage()
}
</script>

<style scoped lang="scss">
.reset-pwd-form {
  :deep(.el-form-item) {
    margin-bottom: 22px;
  }
  
  .form-tip {
    font-size: 12px;
    color: var(--el-text-color-secondary);
    margin-top: 4px;
    line-height: 1.4;
  }
  
  .form-actions {
    display: flex;
    justify-content: flex-end;
    gap: 12px;
    padding-top: 8px;
  }
}
</style>

// ruoyi-react-web/src/views/system/user/profile/resetPwd.jsx
import { useState } from 'react'
import { Form, Input, Button } from 'antd'
import { updateUserPwd } from '@/api/system/user'
import modal from '@/plugins/modal'
import { useTagsViewStore } from '@/store/tagsViewStore'
import './index.scss'

const ResetPwd = () => {
  const [form] = Form.useForm()
  const tagsViewStore = useTagsViewStore()

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields()
      await updateUserPwd(values.oldPassword, values.newPassword)
      modal.msgSuccess('修改成功')
      form.resetFields()
    } catch (error) {
      console.error('Validation failed:', error)
    }
  }

  const handleClose = () => {
    tagsViewStore.delView(tagsViewStore.visitedViews.find(v => v.path === '/user/profile'))
  }

  return (
    <Form
      form={form}
      layout="vertical"
      className="reset-pwd-form"
      labelCol={{ span: 6 }}
      wrapperCol={{ span: 18 }}
    >
      <Form.Item
        label="旧密码"
        name="oldPassword"
        rules={[
          { required: true, message: '旧密码不能为空' }
        ]}
      >
        <Input.Password
          placeholder="请输入旧密码"
        />
      </Form.Item>
      <Form.Item
        label="新密码"
        name="newPassword"
        rules={[
          { required: true, message: '新密码不能为空' },
          { min: 6, max: 20, message: '长度在 6 到 20 个字符' },
          { pattern: /^[^<>"'|\\]+$/, message: '不能包含非法字符：< > " \' \\ |' }
        ]}
      >
        <Input.Password
          placeholder="请输入新密码（6-20个字符）"
        />
      </Form.Item>
      <div className="form-tip">密码长度必须在 6 到 20 个字符之间</div>
      <Form.Item
        label="确认密码"
        name="confirmPassword"
        dependencies={['newPassword']}
        rules={[
          { required: true, message: '确认密码不能为空' },
          ({ getFieldValue }) => ({
            validator(_, value) {
              if (!value || getFieldValue('newPassword') === value) {
                return Promise.resolve()
              }
              return Promise.reject(new Error('两次输入的密码不一致'))
            }
          })
        ]}
      >
        <Input.Password
          placeholder="请再次输入新密码"
        />
      </Form.Item>
      <Form.Item>
        <div className="form-actions">
          <Button onClick={handleClose}>取 消</Button>
          <Button type="primary" onClick={handleSubmit}>保 存</Button>
        </div>
      </Form.Item>
    </Form>
  )
}

export default ResetPwd
