// ruoyi-react-web/src/views/system/user/index.jsx
import { useState, useEffect, useRef } from 'react'
import { Row, Col, Form, Input, Select, DatePicker, Button, Table, Switch, Modal, Space, Tooltip } from 'antd'
import { PlusOutlined, EditOutlined, DeleteOutlined, UploadOutlined, DownloadOutlined, KeyOutlined, CheckCircleOutlined, SearchOutlined, ReloadOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import dayjs from 'dayjs'
import { 
  listUser, 
  getUser, 
  addUser, 
  updateUser, 
  delUser, 
  resetUserPwd, 
  changeUserStatus, 
  deptTreeSelect 
} from '@/api/system/user'
import { getConfigKey } from '@/api/system/config'
import { useDict } from '@/utils/dict'
import { useAppStore } from '@/store/appStore'
import auth from '@/plugins/auth'
import { parseTime, addDateRange } from '@/utils/ruoyi'
import { download } from '@/utils/request'
import { getToken } from '@/utils/auth'
import modal from '@/plugins/modal'
import Pagination from '@/components/Pagination'
import RightToolbar from '@/components/RightToolbar'
import UserFormModal from './UserFormModal'
import UserImportModal from './UserImportModal'
import { Tree, Input as TreeInput } from 'antd'
import './index.scss'

const { RangePicker } = DatePicker

const User = () => {
  const navigate = useNavigate()
  const appStore = useAppStore()
  const [form] = Form.useForm()
  const [queryForm] = Form.useForm()
  const deptTreeRef = useRef(null)

  const [userList, setUserList] = useState([])
  const [loading, setLoading] = useState(true)
  const [showSearch, setShowSearch] = useState(true)
  const [selectedRowKeys, setSelectedRowKeys] = useState([])
  const [total, setTotal] = useState(0)
  const [open, setOpen] = useState(false)
  const [isEdit, setIsEdit] = useState(false)
  const [title, setTitle] = useState('')
  const [dateRange, setDateRange] = useState([])
  const [deptName, setDeptName] = useState('')
  const [deptOptions, setDeptOptions] = useState([])
  const [enabledDeptOptions, setEnabledDeptOptions] = useState([])
  const [initPassword, setInitPassword] = useState('')
  const [postOptions, setPostOptions] = useState([])
  const [roleOptions, setRoleOptions] = useState([])
  const [uploadOpen, setUploadOpen] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [updateSupport, setUpdateSupport] = useState(0)
  const [selectedFile, setSelectedFile] = useState(null)

  const sys_normal_disable = useDict('sys_normal_disable')
  const sys_user_sex = useDict('sys_user_sex')

  const [columns, setColumns] = useState({
    userId: { label: '用户编号', visible: true },
    userName: { label: '用户名称', visible: true },
    nickName: { label: '用户昵称', visible: true },
    deptName: { label: '部门', visible: true },
    phonenumber: { label: '手机号码', visible: true },
    status: { label: '状态', visible: true },
    createTime: { label: '创建时间', visible: true }
  })

  const [queryParams, setQueryParams] = useState({
    pageNum: 1,
    pageSize: 10,
    userName: undefined,
    phonenumber: undefined,
    status: undefined,
    deptId: undefined
  })

  useEffect(() => {
    getDeptTree()
    getList()
    getConfigKey('sys.user.initPassword').then(response => {
      setInitPassword(response.msg)
    })
  }, [])

  useEffect(() => {
    getList()
  }, [queryParams])

  // 过滤禁用的部门
  const filterDisabledDept = (deptList) => {
    return deptList.filter(dept => {
      if (dept.disabled) {
        return false
      }
      if (dept.children && dept.children.length) {
        dept.children = filterDisabledDept(dept.children)
      }
      return true
    })
  }

  // 查询部门下拉树结构
  const getDeptTree = async () => {
    try {
      const response = await deptTreeSelect()
      setDeptOptions(response.data || [])
      setEnabledDeptOptions(filterDisabledDept(JSON.parse(JSON.stringify(response.data || []))))
    } catch (error) {
      console.error('Failed to get dept tree:', error)
    }
  }

  // 查询用户列表
  const getList = async () => {
    setLoading(true)
    try {
      const params = addDateRange(queryParams, dateRange)
      const response = await listUser(params)
      setUserList(response.rows || [])
      setTotal(response.total || 0)
    } catch (error) {
      console.error('Failed to get user list:', error)
    } finally {
      setLoading(false)
    }
  }

  // 部门树过滤
  const filterNode = (node) => {
    if (!deptName) return true
    return node.label.indexOf(deptName) !== -1
  }

  // 部门树节点点击
  const handleNodeClick = (selectedKeys, info) => {
    if (info.node) {
      setQueryParams(prev => ({
        ...prev,
        deptId: info.node.id,
        pageNum: 1
      }))
    }
  }

  // 搜索
  const handleQuery = () => {
    const values = queryForm.getFieldsValue()
    setQueryParams(prev => ({
      ...prev,
      ...values,
      pageNum: 1
    }))
  }

  // 重置
  const resetQuery = () => {
    setDateRange([])
    queryForm.resetFields()
    setQueryParams(prev => ({
      ...prev,
      userName: undefined,
      phonenumber: undefined,
      status: undefined,
      deptId: undefined,
      pageNum: 1
    }))
    if (deptTreeRef.current) {
      deptTreeRef.current.setSelectedKeys([])
    }
    getList()
  }

  // 分页变化
  const handlePagination = ({ page, limit }) => {
    setQueryParams(prev => ({
      ...prev,
      pageNum: page,
      pageSize: limit
    }))
  }

  // 表格选择变化
  const handleSelectionChange = (selectedRowKeys) => {
    setSelectedRowKeys(selectedRowKeys)
  }

  // 新增
  const handleAdd = async () => {
    reset()
    try {
      const response = await getUser()
      setPostOptions(response.posts || [])
      setRoleOptions(response.roles || [])
      setOpen(true)
      setTitle('添加用户')
      setIsEdit(false)
      form.setFieldsValue({
        password: initPassword,
        status: '0'
      })
    } catch (error) {
      console.error('Failed to get user data:', error)
    }
  }

  // 修改
  const handleUpdate = async (row) => {
    reset()
    const userId = row?.userId || (selectedRowKeys.length === 1 ? selectedRowKeys[0] : null)
    
    if (!userId) {
      modal.msgWarning('请选择要修改的用户')
      return
    }

    try {
      const response = await getUser(userId)
      form.setFieldsValue({
        ...response.data,
        postIds: response.postIds || [],
        roleIds: response.roleIds || []
      })
      setPostOptions(response.posts || [])
      setRoleOptions(response.roles || [])
      setOpen(true)
      setTitle('修改用户')
      setIsEdit(true)
      form.setFieldValue('password', '')
    } catch (error) {
      console.error('Failed to get user:', error)
      modal.msgError('获取用户信息失败')
    }
  }

  // 删除
  const handleDelete = (row) => {
    const userIds = row?.userId || selectedRowKeys
    Modal.confirm({
      title: '提示',
      content: `是否确认删除用户编号为"${userIds}"的数据项？`,
      onOk: async () => {
        try {
          await delUser(userIds)
          modal.msgSuccess('删除成功')
          getList()
        } catch (error) {
          console.error('Failed to delete user:', error)
        }
      }
    })
  }

  // 状态修改
  const handleStatusChange = (row) => {
    const text = row.status === '0' ? '启用' : '停用'
    Modal.confirm({
      title: '提示',
      content: `确认要"${text}""${row.userName}"用户吗?`,
      onOk: async () => {
        try {
          await changeUserStatus(row.userId, row.status)
          modal.msgSuccess(`${text}成功`)
          getList()
        } catch (error) {
          setUserList(prev => prev.map(u =>
            u.userId === row.userId ? { ...u, status: u.status === '0' ? '1' : '0' } : u
          ))
          console.error('Failed to change status:', error)
        }
      },
      onCancel: () => {
        setUserList(prev => prev.map(u =>
          u.userId === row.userId ? { ...u, status: u.status === '0' ? '1' : '0' } : u
        ))
      }
    })
  }

  // 重置密码
  const handleResetPwd = (row) => {
    Modal.confirm({
      title: '重置密码',
      content: (
        <Input.Password
          placeholder={`请输入"${row.userName}"的新密码`}
          id="resetPwdInput"
        />
      ),
      onOk: async () => {
        const input = document.getElementById('resetPwdInput')
        const password = input?.value
        if (!password || password.length < 5 || password.length > 20) {
          modal.msgError('用户密码长度必须介于 5 和 20 之间')
          return Promise.reject()
        }
        if (/<|>|"|'|\||\\/.test(password)) {
          modal.msgError('不能包含非法字符：< > " \' \\ |')
          return Promise.reject()
        }
        try {
          await resetUserPwd(row.userId, password)
          modal.msgSuccess(`修改成功，新密码是：${password}`)
        } catch (error) {
          console.error('Failed to reset password:', error)
          return Promise.reject()
        }
      }
    })
  }

  // 分配角色
  const handleAuthRole = (row) => {
    navigate(`/system/user-auth/role/${row.userId}`)
  }

  // 导出
  const handleExport = () => {
    download('system/user/export', queryParams, `user_${new Date().getTime()}.xlsx`)
  }

  // 导入
  const handleImport = () => {
    setUploadOpen(true)
    setSelectedFile(null)
  }

  // 下载模板
  const importTemplate = () => {
    download('system/user/importTemplate', {}, `user_template_${new Date().getTime()}.xlsx`)
  }

  // 文件上传前
  const beforeUpload = (file) => {
    const isExcel = file.name.toLowerCase().endsWith('.xls') || file.name.toLowerCase().endsWith('.xlsx')
    if (!isExcel) {
      modal.msgError('仅允许导入xls、xlsx格式文件')
      return false
    }
    setSelectedFile(file)
    return false
  }

  // 文件上传
  const handleUpload = async () => {
    if (!selectedFile) {
      modal.msgError('请选择后缀为 "xls"或"xlsx" 的文件')
      return
    }
    
    setUploading(true)
    const formData = new FormData()
    formData.append('file', selectedFile)
    
    try {
      const response = await fetch(`${import.meta.env.VITE_APP_BASE_API || '/dev-api'}/system/user/importData?updateSupport=${updateSupport}`, {
        method: 'POST',
        headers: {
          'Authorization': 'Bearer ' + getToken()
        },
        body: formData
      })
      
      const result = await response.json()
      setUploadOpen(false)
      setUploading(false)
      setSelectedFile(null)
      
      Modal.info({
        title: '导入结果',
        content: result.msg,
        width: 600
      })
      
      getList()
    } catch (error) {
      console.error('Failed to upload:', error)
      modal.msgError('上传失败')
      setUploading(false)
    }
  }

  // 表单重置
  const reset = () => {
    form.resetFields()
    form.setFieldsValue({
      // 这里不要用 undefined：Antd Form 对 undefined 赋值有时会被忽略，导致上一次编辑的值“残留”
      userId: null,
      deptId: null,
      userName: '',
      nickName: '',
      password: '',
      phonenumber: '',
      email: '',
      sex: null,
      status: '0',
      remark: '',
      postIds: [],
      roleIds: []
    })
  }

  // 取消
  const cancel = () => {
    setOpen(false)
    reset()
  }

  // 提交表单
  const submitForm = async () => {
    try {
      const values = await form.validateFields()
      // 统一做下 trim，避免“看起来没改但带空格”触发后端唯一性校验
      const normalized = {
        ...values,
        userName: typeof values.userName === 'string' ? values.userName.trim() : values.userName,
        nickName: typeof values.nickName === 'string' ? values.nickName.trim() : values.nickName,
        phonenumber: typeof values.phonenumber === 'string' ? values.phonenumber.trim() : values.phonenumber,
        email: typeof values.email === 'string' ? values.email.trim() : values.email,
        remark: typeof values.remark === 'string' ? values.remark.trim() : values.remark
      }
      if (normalized.userId !== undefined && normalized.userId !== null && normalized.userId !== '') {
        // 修改：不提交 password 字段（编辑时表单也不显示该字段）
        // 兼容后端对 password 的不同处理策略
        // eslint-disable-next-line no-unused-vars
        const { password, ...payload } = normalized
        await updateUser(payload)
        modal.msgSuccess('修改成功')
      } else {
        await addUser(normalized)
        modal.msgSuccess('新增成功')
      }
      setOpen(false)
      getList()
    } catch (error) {
      console.error('Validation failed:', error)
    }
  }

  // 双击行
  const handleRowDblClick = (row) => {
    if (row.userId === 1) {
      modal.msgWarning('不允许修改管理员用户')
      return
    }
    handleUpdate(row)
  }

  // 表格列定义
  const tableColumns = [
    {
      title: '用户编号',
      dataIndex: 'userId',
      key: 'userId',
      align: 'center',
      width: 80,
      hidden: !columns.userId.visible
    },
    {
      title: '用户名称',
      dataIndex: 'userName',
      key: 'userName',
      align: 'center',
      ellipsis: true,
      hidden: !columns.userName.visible
    },
    {
      title: '用户昵称',
      dataIndex: 'nickName',
      key: 'nickName',
      align: 'center',
      ellipsis: true,
      hidden: !columns.nickName.visible
    },
    {
      title: '部门',
      dataIndex: ['dept', 'deptName'],
      key: 'deptName',
      align: 'center',
      ellipsis: true,
      hidden: !columns.deptName.visible
    },
    {
      title: '手机号码',
      dataIndex: 'phonenumber',
      key: 'phonenumber',
      align: 'center',
      width: 120,
      hidden: !columns.phonenumber.visible
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      align: 'center',
      width: 100,
      hidden: !columns.status.visible,
      render: (_, record) => (
        <Switch
          checked={record.status === '0'}
          onChange={(checked) => {
            const updatedRecord = { ...record, status: checked ? '0' : '1' }
            handleStatusChange(updatedRecord)
          }}
          checkedChildren="启用"
          unCheckedChildren="停用"
        />
      )
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      key: 'createTime',
      align: 'center',
      width: 160,
      hidden: !columns.createTime.visible,
      render: (text) => parseTime(text)
    },
    {
      title: '操作',
      key: 'action',
      align: 'center',
      width: 200,
      fixed: 'right',
      render: (_, record) => {
        if (record.userId === 1) return null
        return (
          <Space size="small">
            {auth.hasPermiOr(['system:user:edit']) && (
              <Tooltip title="修改">
                <Button
                  type="link"
                  icon={<EditOutlined />}
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleUpdate(record)
                  }}
                />
              </Tooltip>
            )}
            {auth.hasPermiOr(['system:user:remove']) && (
              <Tooltip title="删除">
                <Button
                  type="link"
                  danger
                  icon={<DeleteOutlined />}
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleDelete(record)
                  }}
                />
              </Tooltip>
            )}
            {auth.hasPermiOr(['system:user:resetPwd']) && (
              <Tooltip title="重置密码">
                <Button
                  type="link"
                  icon={<KeyOutlined />}
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleResetPwd(record)
                  }}
                />
              </Tooltip>
            )}
            {auth.hasPermiOr(['system:user:edit']) && (
              <Tooltip title="分配角色">
                <Button
                  type="link"
                  icon={<CheckCircleOutlined />}
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleAuthRole(record)
                  }}
                />
              </Tooltip>
            )}
          </Space>
        )
      }
    }
  ].filter(col => !col.hidden)

  const rowSelection = {
    selectedRowKeys,
    onChange: handleSelectionChange
  }

  return (
    <div className="app-container">
      <Row gutter={20}>
        <div style={{ display: 'flex', width: '100%', height: 'calc(100vh - 200px)' }}>
          {/* 部门数据 */}
          <div style={{ width: '16%', minWidth: '200px', borderRight: '1px solid #f0f0f0' }}>
            <div className="dept-search-container">
              <TreeInput
                placeholder="请输入部门名称"
                value={deptName}
                onChange={(e) => setDeptName(e.target.value)}
                allowClear
              />
            </div>
            <div className="dept-tree-container">
              <Tree
                ref={deptTreeRef}
                treeData={deptOptions}
                fieldNames={{ title: 'label', key: 'id', children: 'children' }}
                defaultExpandAll
                onSelect={handleNodeClick}
                filterTreeNode={filterNode}
                showLine
              />
            </div>
          </div>
          {/* 用户数据 */}
          <div className="user-content" style={{ flex: 1 }}>
            <Form
              form={queryForm}
              layout="inline"
              className="search-form"
              style={{ display: showSearch ? 'flex' : 'none', marginBottom: 16 }}
            >
              <Form.Item label="用户名称" name="userName">
                <Input
                  placeholder="请输入用户名称"
                  style={{ width: 240 }}
                  onPressEnter={handleQuery}
                  allowClear
                />
              </Form.Item>
              <Form.Item label="手机号码" name="phonenumber">
                <Input
                  placeholder="请输入手机号码"
                  style={{ width: 240 }}
                  onPressEnter={handleQuery}
                  allowClear
                />
              </Form.Item>
              <Form.Item label="状态" name="status">
                <Select
                  placeholder="用户状态"
                  style={{ width: 240 }}
                  allowClear
                >
                  {sys_normal_disable.sys_normal_disable?.map(dict => (
                    <Select.Option key={dict.value} value={dict.value}>
                      {dict.label}
                    </Select.Option>
                  ))}
                </Select>
              </Form.Item>
              <Form.Item label="创建时间">
                <RangePicker
                  value={dateRange.length ? [dayjs(dateRange[0]), dayjs(dateRange[1])] : null}
                  onChange={(dates) => {
                    setDateRange(dates ? [dates[0].format('YYYY-MM-DD'), dates[1].format('YYYY-MM-DD')] : [])
                  }}
                  format="YYYY-MM-DD"
                />
              </Form.Item>
              <Form.Item>
                <Button type="primary" icon={<SearchOutlined />} onClick={handleQuery}>
                  搜索
                </Button>
                <Button icon={<ReloadOutlined />} onClick={resetQuery} style={{ marginLeft: 8 }}>
                  重置
                </Button>
              </Form.Item>
            </Form>

            <Row gutter={10} style={{ marginBottom: 16 }}>
              <Col>
                {auth.hasPermiOr(['system:user:add']) && (
                  <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
                    新增
                  </Button>
                )}
              </Col>
              <Col>
                {auth.hasPermiOr(['system:user:edit']) && (
                  <Button
                    type="default"
                    icon={<EditOutlined />}
                    disabled={selectedRowKeys.length !== 1}
                    onClick={() => handleUpdate({ userId: selectedRowKeys[0] })}
                  >
                    修改
                  </Button>
                )}
              </Col>
              <Col>
                {auth.hasPermiOr(['system:user:remove']) && (
                  <Button
                    type="default"
                    danger
                    icon={<DeleteOutlined />}
                    disabled={!selectedRowKeys.length}
                    onClick={() => handleDelete()}
                  >
                    删除
                  </Button>
                )}
              </Col>
              <Col>
                {auth.hasPermiOr(['system:user:import']) && (
                  <Button type="default" icon={<UploadOutlined />} onClick={handleImport}>
                    导入
                  </Button>
                )}
              </Col>
              <Col>
                {auth.hasPermiOr(['system:user:export']) && (
                  <Button type="default" icon={<DownloadOutlined />} onClick={handleExport}>
                    导出
                  </Button>
                )}
              </Col>
              <Col flex="auto">
                <RightToolbar
                  showSearch={showSearch}
                  columns={columns}
                  onShowSearchChange={setShowSearch}
                  onQueryTable={getList}
                />
              </Col>
            </Row>

            <Table
              loading={loading}
              dataSource={userList}
              columns={tableColumns}
              className="user-table"
              rowSelection={rowSelection}
              rowKey="userId"
              onRow={(record) => ({
                onDoubleClick: () => handleRowDblClick(record)
              })}
              pagination={false}
            />

            <Pagination
              total={total}
              page={queryParams.pageNum}
              limit={queryParams.pageSize}
              onChange={handlePagination}
            />
          </div>
        </div>
      </Row>

      <UserFormModal
        open={open}
        title={title}
        isEdit={isEdit}
        onCancel={cancel}
        onOk={submitForm}
        form={form}
        enabledDeptOptions={enabledDeptOptions}
        postOptions={postOptions}
        roleOptions={roleOptions}
        sysNormalDisable={sys_normal_disable.sys_normal_disable}
        sysUserSex={sys_user_sex.sys_user_sex}
      />

      <UserImportModal
        open={uploadOpen}
        onCancel={() => {
          setUploadOpen(false)
          setSelectedFile(null)
        }}
        onOk={handleUpload}
        uploading={uploading}
        selectedFile={selectedFile}
        onFileChange={beforeUpload}
        onFileRemove={() => setSelectedFile(null)}
        updateSupport={updateSupport}
        onUpdateSupportChange={(e) => setUpdateSupport(e.target.checked ? 1 : 0)}
        onImportTemplate={importTemplate}
      />
    </div>
  )
}

export default User

// ruoyi-front/src/views/system/user/index.vue
<template>
  <div class="app-container">
    <el-row :gutter="20">
      <splitpanes :horizontal="appStore.device === 'mobile'" class="default-theme">
        <!--部门数据-->
        <pane size="16">
          <el-col>
            <div class="dept-search-container">
              <el-input v-model="deptName" placeholder="请输入部门名称" clearable prefix-icon="Search" />
            </div>
            <div class="dept-tree-container">
              <el-tree 
                 :data="deptOptions" 
                 :props="{ label: 'label', children: 'children' }" 
                 :expand-on-click-node="false" 
                 :filter-node-method="filterNode" 
                 ref="deptTreeRef" 
                 node-key="id" 
                 highlight-current 
                 default-expand-all 
                 @node-click="handleNodeClick"
                 class="dept-tree"
              />
            </div>
          </el-col>
        </pane>
        <!--用户数据-->
        <pane size="84">
          <el-col>
            <el-form :model="queryParams" ref="queryRef" :inline="true" v-show="showSearch" label-width="68px">
              <el-form-item label="用户名称" prop="userName">
                <el-input v-model="queryParams.userName" placeholder="请输入用户名称" clearable style="width: 240px" @keyup.enter="handleQuery" />
              </el-form-item>
              <el-form-item label="手机号码" prop="phonenumber">
                <el-input v-model="queryParams.phonenumber" placeholder="请输入手机号码" clearable style="width: 240px" @keyup.enter="handleQuery" />
              </el-form-item>
              <el-form-item label="状态" prop="status">
                <el-select v-model="queryParams.status" placeholder="用户状态" clearable style="width: 240px">
                  <el-option v-for="dict in sys_normal_disable" :key="dict.value" :label="dict.label" :value="dict.value" />
                </el-select>
              </el-form-item>
              <el-form-item label="创建时间" style="width: 308px">
                <el-date-picker v-model="dateRange" value-format="YYYY-MM-DD" type="daterange" range-separator="-" start-placeholder="开始日期" end-placeholder="结束日期"></el-date-picker>
              </el-form-item>
              <el-form-item>
                <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
                <el-button icon="Refresh" @click="resetQuery">重置</el-button>
              </el-form-item>
            </el-form>

            <el-row :gutter="10" class="mb8">
              <el-col :span="1.5">
                <el-button type="primary" plain icon="Plus" @click="handleAdd" v-hasPermi="['system:user:add']">新增</el-button>
              </el-col>
              <el-col :span="1.5">
                <el-button type="success" plain icon="Edit" :disabled="single" @click="handleUpdate" v-hasPermi="['system:user:edit']">修改</el-button>
              </el-col>
              <el-col :span="1.5">
                <el-button type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete" v-hasPermi="['system:user:remove']">删除</el-button>
              </el-col>
              <el-col :span="1.5">
                <el-button type="info" plain icon="Upload" @click="handleImport" v-hasPermi="['system:user:import']">导入</el-button>
              </el-col>
              <el-col :span="1.5">
                <el-button type="warning" plain icon="Download" @click="handleExport" v-hasPermi="['system:user:export']">导出</el-button>
              </el-col>
              <right-toolbar v-model:showSearch="showSearch" @queryTable="getList" :columns="columns"></right-toolbar>
            </el-row>

            <el-table 
               v-loading="loading" 
               :data="userList" 
               @selection-change="handleSelectionChange"
               @row-dblclick="handleRowDblClick"
               @row-click="handleRowClick"
               stripe
               style="width: 100%"
               class="user-table"
            >
              <el-table-column type="selection" width="50" align="center" />
              <el-table-column label="用户编号" align="center" key="userId" prop="userId" v-if="columns.userId.visible" />
              <el-table-column label="用户名称" align="center" key="userName" prop="userName" v-if="columns.userName.visible" :show-overflow-tooltip="true" />
              <el-table-column label="用户昵称" align="center" key="nickName" prop="nickName" v-if="columns.nickName.visible" :show-overflow-tooltip="true" />
              <el-table-column label="部门" align="center" key="deptName" prop="dept.deptName" v-if="columns.deptName.visible" :show-overflow-tooltip="true" />
              <el-table-column label="手机号码" align="center" key="phonenumber" prop="phonenumber" v-if="columns.phonenumber.visible" width="120" />
              <el-table-column label="状态" align="center" key="status" v-if="columns.status.visible">
                <template #default="scope">
                  <el-switch
                    v-model="scope.row.status"
                    active-value="0"
                    inactive-value="1"
                    @change="handleStatusChange(scope.row)"
                  ></el-switch>
                </template>
              </el-table-column>
              <el-table-column label="创建时间" align="center" prop="createTime" v-if="columns.createTime.visible" width="160">
                <template #default="scope">
                  <span>{{ parseTime(scope.row.createTime) }}</span>
                </template>
              </el-table-column>
              <el-table-column label="操作" align="center" width="200" fixed="right">
                <template #default="scope">
                  <div class="action-buttons" v-if="scope.row.userId !== 1">
                    <el-tooltip content="修改" placement="top">
                      <el-button 
                         link 
                         type="primary" 
                         icon="Edit" 
                         size="small"
                         @click.stop="handleUpdate(scope.row)" 
                         v-hasPermi="['system:user:edit']"
                      ></el-button>
                    </el-tooltip>
                    <el-tooltip content="删除" placement="top">
                      <el-button 
                         link 
                         type="danger" 
                         icon="Delete" 
                         size="small"
                         @click.stop="handleDelete(scope.row)" 
                         v-hasPermi="['system:user:remove']"
                      ></el-button>
                    </el-tooltip>
                    <el-tooltip content="重置密码" placement="top">
                      <el-button 
                         link 
                         type="primary" 
                         icon="Key" 
                         size="small"
                         @click.stop="handleResetPwd(scope.row)" 
                         v-hasPermi="['system:user:resetPwd']"
                      ></el-button>
                    </el-tooltip>
                    <el-tooltip content="分配角色" placement="top">
                      <el-button 
                         link 
                         type="primary" 
                         icon="CircleCheck" 
                         size="small"
                         @click.stop="handleAuthRole(scope.row)" 
                         v-hasPermi="['system:user:edit']"
                      ></el-button>
                    </el-tooltip>
                  </div>
                </template>
              </el-table-column>
            </el-table>
            <pagination v-show="total > 0" :total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList" />
          </el-col>
        </pane>
      </splitpanes>
    </el-row>

    <!-- 添加或修改用户配置对话框 -->
    <el-dialog :title="title" v-model="open" width="600px" append-to-body :close-on-click-modal="false">
      <el-form :model="form" :rules="rules" ref="userRef" label-width="80px">
        <el-row>
          <el-col :span="12">
            <el-form-item label="用户昵称" prop="nickName">
              <el-input v-model="form.nickName" placeholder="请输入用户昵称" maxlength="30" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="归属部门" prop="deptId">
              <el-tree-select v-model="form.deptId" :data="enabledDeptOptions" :props="{ value: 'id', label: 'label', children: 'children' }" value-key="id" placeholder="请选择归属部门" clearable check-strictly />
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12">
            <el-form-item label="手机号码" prop="phonenumber">
              <el-input v-model="form.phonenumber" placeholder="请输入手机号码" maxlength="11" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="邮箱" prop="email">
              <el-input v-model="form.email" placeholder="请输入邮箱" maxlength="50" />
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12">
            <el-form-item v-if="form.userId == undefined" label="用户名称" prop="userName">
              <el-input v-model="form.userName" placeholder="请输入用户名称" maxlength="30" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item v-if="form.userId == undefined" label="用户密码" prop="password">
              <el-input v-model="form.password" placeholder="请输入用户密码" type="password" maxlength="20" show-password />
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12">
            <el-form-item label="用户性别">
              <el-select v-model="form.sex" placeholder="请选择">
                <el-option v-for="dict in sys_user_sex" :key="dict.value" :label="dict.label" :value="dict.value"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="状态">
              <el-radio-group v-model="form.status">
                <el-radio v-for="dict in sys_normal_disable" :key="dict.value" :value="dict.value">{{ dict.label }}</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12">
            <el-form-item label="岗位">
              <el-select v-model="form.postIds" multiple placeholder="请选择">
                <el-option v-for="item in postOptions" :key="item.postId" :label="item.postName" :value="item.postId" :disabled="item.status == 1"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="角色">
              <el-select v-model="form.roleIds" multiple placeholder="请选择">
                <el-option v-for="item in roleOptions" :key="item.roleId" :label="item.roleName" :value="item.roleId" :disabled="item.status == 1"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="24">
            <el-form-item label="备注">
              <el-input v-model="form.remark" type="textarea" placeholder="请输入内容"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button @click="cancel">取 消</el-button>
          <el-button type="primary" @click="submitForm">确 定</el-button>
        </div>
      </template>
    </el-dialog>

    <!-- 用户导入对话框 -->
    <el-dialog :title="upload.title" v-model="upload.open" width="400px" append-to-body>
      <el-upload ref="uploadRef" :limit="1" accept=".xlsx, .xls" :headers="upload.headers" :action="upload.url + '?updateSupport=' + upload.updateSupport" :disabled="upload.isUploading" :on-progress="handleFileUploadProgress" :on-success="handleFileSuccess" :on-change="handleFileChange" :on-remove="handleFileRemove" :auto-upload="false" drag>
        <el-icon class="el-icon--upload"><upload-filled /></el-icon>
        <div class="el-upload__text">将文件拖到此处，或<em>点击上传</em></div>
        <template #tip>
          <div class="el-upload__tip text-center">
            <div class="el-upload__tip">
              <el-checkbox v-model="upload.updateSupport" />是否更新已经存在的用户数据
            </div>
            <span>仅允许导入xls、xlsx格式文件。</span>
            <el-link type="primary" :underline="false" style="font-size: 12px; vertical-align: baseline" @click="importTemplate">下载模板</el-link>
          </div>
        </template>
      </el-upload>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitFileForm">确 定</el-button>
          <el-button @click="upload.open = false">取 消</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup name="User">
import { getToken } from "@/utils/auth"
import useAppStore from '@/store/modules/app'
import { changeUserStatus, listUser, resetUserPwd, delUser, getUser, updateUser, addUser, deptTreeSelect } from "@/api/system/user"
import { Splitpanes, Pane } from "splitpanes"
import "splitpanes/dist/splitpanes.css"

const router = useRouter()
const appStore = useAppStore()
const { proxy } = getCurrentInstance()
const { sys_normal_disable, sys_user_sex } = proxy.useDict("sys_normal_disable", "sys_user_sex")

const userList = ref([])
const open = ref(false)
const loading = ref(true)
const showSearch = ref(true)
const ids = ref([])
const single = ref(true)
const multiple = ref(true)
const total = ref(0)
const title = ref("")
const dateRange = ref([])
const deptName = ref("")
const deptOptions = ref(undefined)
const enabledDeptOptions = ref(undefined)
const initPassword = ref(undefined)
const postOptions = ref([])
const roleOptions = ref([])
/*** 用户导入参数 */
const upload = reactive({
  // 是否显示弹出层（用户导入）
  open: false,
  // 弹出层标题（用户导入）
  title: "",
  // 是否禁用上传
  isUploading: false,
  // 是否更新已经存在的用户数据
  updateSupport: 0,
  // 设置上传的请求头部
  headers: { Authorization: "Bearer " + getToken() },
  // 上传的地址
  url: import.meta.env.VITE_APP_BASE_API + "/system/user/importData"
})
// 列显隐信息
const columns = ref({
  userId: { label: '用户编号', visible: true },
  userName: { label: '用户名称', visible: true },
  nickName: { label: '用户昵称', visible: true },
  deptName: { label: '部门', visible: true },
  phonenumber: { label: '手机号码', visible: true },
  status: { label: '状态', visible: true },
  createTime: { label: '创建时间', visible: true }
})

const data = reactive({
  form: {},
  queryParams: {
    pageNum: 1,
    pageSize: 10,
    userName: undefined,
    phonenumber: undefined,
    status: undefined,
    deptId: undefined
  },
  rules: {
    userName: [{ required: true, message: "用户名称不能为空", trigger: "blur" }, { min: 2, max: 20, message: "用户名称长度必须介于 2 和 20 之间", trigger: "blur" }],
    nickName: [{ required: true, message: "用户昵称不能为空", trigger: "blur" }],
    password: [{ required: true, message: "用户密码不能为空", trigger: "blur" }, { min: 5, max: 20, message: "用户密码长度必须介于 5 和 20 之间", trigger: "blur" }, { pattern: /^[^<>"'|\\]+$/, message: "不能包含非法字符：< > \" ' \\\ |", trigger: "blur" }],
    email: [{ type: "email", message: "请输入正确的邮箱地址", trigger: ["blur", "change"] }],
    phonenumber: [{ pattern: /^1[3|4|5|6|7|8|9][0-9]\d{8}$/, message: "请输入正确的手机号码", trigger: "blur" }]
  }
})

const { queryParams, form, rules } = toRefs(data)

/** 通过条件过滤节点  */
const filterNode = (value, data) => {
  if (!value) return true
  return data.label.indexOf(value) !== -1
}

/** 根据名称筛选部门树 */
watch(deptName, val => {
  proxy.$refs["deptTreeRef"].filter(val)
})

/** 查询用户列表 */
function getList() {
  loading.value = true
  listUser(proxy.addDateRange(queryParams.value, dateRange.value)).then(res => {
    loading.value = false
    userList.value = res.rows
    total.value = res.total
  })
}

/** 查询部门下拉树结构 */
function getDeptTree() {
  deptTreeSelect().then(response => {
    deptOptions.value = response.data
    enabledDeptOptions.value = filterDisabledDept(JSON.parse(JSON.stringify(response.data)))
  })
}

/** 过滤禁用的部门 */
function filterDisabledDept(deptList) {
  return deptList.filter(dept => {
    if (dept.disabled) {
      return false
    }
    if (dept.children && dept.children.length) {
      dept.children = filterDisabledDept(dept.children)
    }
    return true
  })
}

/** 节点单击事件 */
function handleNodeClick(data) {
  queryParams.value.deptId = data.id
  handleQuery()
}

/** 搜索按钮操作 */
function handleQuery() {
  queryParams.value.pageNum = 1
  getList()
}

/** 重置按钮操作 */
function resetQuery() {
  dateRange.value = []
  proxy.resetForm("queryRef")
  queryParams.value.deptId = undefined
  proxy.$refs.deptTreeRef.setCurrentKey(null)
  handleQuery()
}

/** 删除按钮操作 */
function handleDelete(row) {
  const userIds = row.userId || ids.value
  proxy.$modal.confirm('是否确认删除用户编号为"' + userIds + '"的数据项？').then(function () {
    return delUser(userIds)
  }).then(() => {
    getList()
    proxy.$modal.msgSuccess("删除成功")
  }).catch(() => {})
}

/** 导出按钮操作 */
function handleExport() {
  proxy.download("system/user/export", {
    ...queryParams.value,
  },`user_${new Date().getTime()}.xlsx`)
}

/** 用户状态修改  */
function handleStatusChange(row) {
  let text = row.status === "0" ? "启用" : "停用"
  proxy.$modal.confirm('确认要"' + text + '""' + row.userName + '"用户吗?').then(function () {
    return changeUserStatus(row.userId, row.status)
  }).then(() => {
    proxy.$modal.msgSuccess(text + "成功")
  }).catch(function () {
    row.status = row.status === "0" ? "1" : "0"
  })
}

/** 更多操作 */
function handleCommand(command, row) {
  switch (command) {
    case "handleResetPwd":
      handleResetPwd(row)
      break
    case "handleAuthRole":
      handleAuthRole(row)
      break
    default:
      break
  }
}

/** 跳转角色分配 */
function handleAuthRole(row) {
  const userId = row.userId
  router.push("/system/user-auth/role/" + userId)
}

/** 重置密码按钮操作 */
function handleResetPwd(row) {
  proxy.$prompt('请输入"' + row.userName + '"的新密码', "提示", {
    confirmButtonText: "确定",
    cancelButtonText: "取消",
    closeOnClickModal: false,
    inputPattern: /^.{5,20}$/,
    inputErrorMessage: "用户密码长度必须介于 5 和 20 之间",
    inputValidator: (value) => {
      if (/<|>|"|'|\||\\/.test(value)) {
        return "不能包含非法字符：< > \" ' \\\ |"
      }
    },
  }).then(({ value }) => {
    resetUserPwd(row.userId, value).then(response => {
      proxy.$modal.msgSuccess("修改成功，新密码是：" + value)
    })
  }).catch(() => {})
}

/** 选择条数  */
function handleSelectionChange(selection) {
  ids.value = selection.map(item => item.userId)
  single.value = selection.length != 1
  multiple.value = !selection.length
}

/** 导入按钮操作 */
function handleImport() {
  upload.title = "用户导入"
  upload.open = true
  upload.selectedFile = null
}

/** 下载模板操作 */
function importTemplate() {
  proxy.download("system/user/importTemplate", {
  }, `user_template_${new Date().getTime()}.xlsx`)
}

/**文件上传中处理 */
const handleFileUploadProgress = (event, file, fileList) => {
  upload.isUploading = true
}

/** 文件选择处理 */
const handleFileChange = (file, fileList) => {
  upload.selectedFile = file
}

/** 文件删除处理 */
const handleFileRemove = (file, fileList) => {
  upload.selectedFile = null
}

/** 文件上传成功处理 */
const handleFileSuccess = (response, file, fileList) => {
  upload.open = false
  upload.isUploading = false
  proxy.$refs["uploadRef"].handleRemove(file)
  proxy.$alert("<div style='overflow: auto;overflow-x: hidden;max-height: 70vh;padding: 10px 20px 0;'>" + response.msg + "</div>", "导入结果", { dangerouslyUseHTMLString: true })
  getList()
}

/** 提交上传文件 */
function submitFileForm() {
  const file = upload.selectedFile
  if (!file || file.length === 0 || !file.name.toLowerCase().endsWith('.xls') && !file.name.toLowerCase().endsWith('.xlsx')) {
    proxy.$modal.msgError("请选择后缀为 “xls”或“xlsx”的文件。")
    return
  }
  proxy.$refs["uploadRef"].submit()
}

/** 重置操作表单 */
function reset() {
  form.value = {
    userId: undefined,
    deptId: undefined,
    userName: undefined,
    nickName: undefined,
    password: undefined,
    phonenumber: undefined,
    email: undefined,
    sex: undefined,
    status: "0",
    remark: undefined,
    postIds: [],
    roleIds: []
  }
  proxy.resetForm("userRef")
}

/** 取消按钮 */
function cancel() {
  open.value = false
  reset()
}

/** 新增按钮操作 */
function handleAdd() {
  reset()
  getUser().then(response => {
    postOptions.value = response.posts
    roleOptions.value = response.roles
    open.value = true
    title.value = "添加用户"
    form.value.password = initPassword.value
  })
}

/** 单击行操作（用于选中） */
function handleRowClick(row, column, event) {
  if (event?.target?.closest('.action-buttons')) {
    return
  }
}

/** 双击行操作 */
function handleRowDblClick(row, column, event) {
  // 如果双击的是操作列，不处理（避免与按钮点击冲突）
  if (event?.target?.closest('.action-buttons')) {
    return
  }
  
  // 不允许修改管理员用户（userId === 1）
  if (row.userId === 1) {
    proxy.$modal.msgWarning("不允许修改管理员用户")
    return
  }
  
  // 双击直接打开修改对话框，权限控制由保存按钮处理
  handleUpdate(row)
}

/** 修改按钮操作 */
function handleUpdate(row) {
  reset()
  if (!row || typeof row !== 'object') {
    return
  }
  
  const userId = row.userId || (Array.isArray(ids.value) && ids.value.length === 1 ? ids.value[0] : null)
  
  if (!userId) {
    proxy.$modal.msgWarning("请选择要修改的用户")
    return
  }
  
  getUser(userId).then(response => {
    form.value = response.data
    postOptions.value = response.posts
    roleOptions.value = response.roles
    form.value.postIds = response.postIds
    form.value.roleIds = response.roleIds
    open.value = true
    title.value = "修改用户"
    form.password = ""
  }).catch(error => {
    console.error("获取用户信息失败:", error)
    proxy.$modal.msgError("获取用户信息失败")
  })
}

/** 提交按钮 */
function submitForm() {
  proxy.$refs["userRef"].validate(valid => {
    if (valid) {
      if (form.value.userId != undefined) {
        updateUser(form.value).then(response => {
          proxy.$modal.msgSuccess("修改成功")
          open.value = false
          getList()
        })
      } else {
        addUser(form.value).then(response => {
          proxy.$modal.msgSuccess("新增成功")
          open.value = false
          getList()
        })
      }
    }
  })
}

onMounted(() => {
  getDeptTree()
  getList()
  proxy.getConfigKey("sys.user.initPassword").then(response => {
    initPassword.value = response.msg
  })
})
</script>

<style scoped lang="scss">
.search-form {
  margin-bottom: 16px;
  
  .el-form-item {
    margin-bottom: 16px;
  }
}

// 左侧部门树容器样式
.dept-search-container {
  padding: 16px;
  padding-bottom: 12px;
  
  .el-input {
    width: 100%;
  }
}

.dept-tree-container {
  padding: 0 16px 16px;
  height: calc(100% - 60px);
  overflow-y: auto;
  
  .dept-tree {
    :deep(.el-tree-node) {
      margin-bottom: 4px;
      
      .el-tree-node__content {
        height: 36px;
        padding: 0 8px;
        margin-bottom: 2px;
        border-radius: 4px;
        transition: all 0.2s;
        
        &:hover {
          background-color: var(--el-tree-node-hover-bg-color, var(--el-fill-color-light));
        }
      }
      
      .el-tree-node__label {
        font-size: 14px;
        line-height: 36px;
        padding-left: 4px;
      }
      
      .el-tree-node__expand-icon {
        width: 20px;
        padding: 0;
        margin-right: 4px;
      }
    }
    
    :deep(.el-tree-node.is-current > .el-tree-node__content) {
      background-color: var(--el-color-primary-light-9);
      color: var(--el-color-primary);
      font-weight: 500;
    }
  }
}

.action-buttons {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  white-space: nowrap;
  
  .el-button {
    padding: 0 8px;
  }
}

.user-table {
  :deep(.el-table__row) {
    cursor: pointer;
    
    &:hover {
      background-color: var(--el-table-row-hover-bg-color);
    }
  }
}

.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
}

:deep(.el-table) {
  .el-table__header {
    th {
      background-color: var(--el-table-header-bg-color);
      font-weight: 500;
    }
  }
}

:deep(.el-dialog__body) {
  padding: 24px 28px;
}

:deep(.el-dialog__header) {
  padding: 20px 28px 16px;
  border-bottom: 1px solid var(--el-border-color-lighter);
}

:deep(.el-dialog__footer) {
  padding: 16px 28px 20px;
  border-top: 1px solid var(--el-border-color-lighter);
}
</style>
