// ruoyi-react-web/src/views/system/role/index.jsx
import { useState, useEffect, useRef } from 'react'
import { Form, Input, InputNumber, Select, DatePicker, Button, Table, Switch, Modal, Radio, Checkbox, Tree, Space, Tooltip } from 'antd'
import { PlusOutlined, EditOutlined, DeleteOutlined, DownloadOutlined, DatabaseOutlined, UserOutlined, QuestionCircleOutlined, SearchOutlined, ReloadOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import dayjs from 'dayjs'
import { 
  listRole, 
  getRole, 
  addRole, 
  updateRole, 
  delRole, 
  changeRoleStatus, 
  dataScope, 
  deptTreeSelect 
} from '@/api/system/role'
import { treeselect as menuTreeselect, roleMenuTreeselect } from '@/api/system/menu'
import { useDict } from '@/utils/dict'
import { parseTime, addDateRange } from '@/utils/ruoyi'
import { download } from '@/utils/request'
import modal from '@/plugins/modal'
import auth from '@/plugins/auth'
import Pagination from '@/components/Pagination'
import RightToolbar from '@/components/RightToolbar'
import './index.scss'

const { RangePicker } = DatePicker
const { TextArea } = Input

const Role = () => {
  const navigate = useNavigate()
  const [form] = Form.useForm()
  const [dataScopeForm] = Form.useForm()
  const [queryForm] = Form.useForm()
  const menuTreeRef = useRef(null)
  const deptTreeRef = useRef(null)

  // Tree 状态（受控），用于回显/全选/半选/展开折叠
  const [menuCheckedKeys, setMenuCheckedKeys] = useState([])
  const [menuHalfCheckedKeys, setMenuHalfCheckedKeys] = useState([])
  const [menuExpandedKeys, setMenuExpandedKeys] = useState([])
  const [deptCheckedKeys, setDeptCheckedKeys] = useState([])
  const [deptHalfCheckedKeys, setDeptHalfCheckedKeys] = useState([])
  const [deptExpandedKeys, setDeptExpandedKeys] = useState([])

  // 同步引用：避免“勾选后立即保存”读到旧 state
  const menuCheckedKeysRef = useRef([])
  const menuHalfCheckedKeysRef = useRef([])
  const deptCheckedKeysRef = useRef([])
  const deptHalfCheckedKeysRef = useRef([])

  const [roleList, setRoleList] = useState([])
  const [loading, setLoading] = useState(true)
  const [showSearch, setShowSearch] = useState(true)
  const [selectedRowKeys, setSelectedRowKeys] = useState([])
  const [total, setTotal] = useState(0)
  const [open, setOpen] = useState(false)
  const [openDataScope, setOpenDataScope] = useState(false)
  const [isEdit, setIsEdit] = useState(false)
  const [title, setTitle] = useState('')
  const [dateRange, setDateRange] = useState([])
  const [menuOptions, setMenuOptions] = useState([])
  const [menuExpand, setMenuExpand] = useState(false)
  const [menuNodeAll, setMenuNodeAll] = useState(false)
  const [deptExpand, setDeptExpand] = useState(true)
  const [deptNodeAll, setDeptNodeAll] = useState(false)
  const [deptOptions, setDeptOptions] = useState([])

  const sys_normal_disable = useDict('sys_normal_disable')

  // 监听表单字段（确保切换“父子联动/权限范围”时组件能及时刷新）
  const menuCheckStrictlyValue = Form.useWatch('menuCheckStrictly', form)
  const deptCheckStrictlyValue = Form.useWatch('deptCheckStrictly', dataScopeForm)
  const dataScopeValue = Form.useWatch('dataScope', dataScopeForm)

  const dataScopeOptions = [
    { value: '1', label: '全部数据权限' },
    { value: '2', label: '自定数据权限' },
    { value: '3', label: '本部门数据权限' },
    { value: '4', label: '本部门及以下数据权限' },
    { value: '5', label: '仅本人数据权限' }
  ]

  const [queryParams, setQueryParams] = useState({
    pageNum: 1,
    pageSize: 10,
    roleName: undefined,
    roleKey: undefined,
    status: undefined
  })

  useEffect(() => {
    getList()
  }, [queryParams, dateRange])

  // 查询角色列表
  const getList = async () => {
    setLoading(true)
    try {
      const params = addDateRange(queryParams, dateRange)
      const response = await listRole(params)
      setRoleList(response.rows || [])
      setTotal(response.total || 0)
    } catch (error) {
      console.error('Failed to get role list:', error)
    } finally {
      setLoading(false)
    }
  }

  // 搜索
  const handleQuery = () => {
    const values = queryForm.getFieldsValue()
    setQueryParams(prev => ({
      ...prev,
      ...values,
      pageNum: 1
    }))
  }

  // 重置
  const resetQuery = () => {
    setDateRange([])
    queryForm.resetFields()
    setQueryParams(prev => ({
      ...prev,
      roleName: undefined,
      roleKey: undefined,
      status: undefined,
      pageNum: 1
    }))
    getList()
  }

  // 分页变化
  const handlePagination = ({ page, limit }) => {
    setQueryParams(prev => ({
      ...prev,
      pageNum: page,
      pageSize: limit
    }))
  }

  // 表格选择变化
  const handleSelectionChange = (selectedRowKeys) => {
    setSelectedRowKeys(selectedRowKeys)
  }

  // 新增
  const handleAdd = async () => {
    reset()
    await getMenuTreeselect()
    setOpen(true)
    setTitle('添加角色')
    setIsEdit(false)
  }

  // 修改
  const handleUpdate = async (row) => {
    reset()
    const roleId = row?.roleId || (selectedRowKeys.length === 1 ? selectedRowKeys[0] : null)
    
    if (!roleId) {
      modal.msgWarning('请选择要修改的角色')
      return
    }

    try {
      const roleResponse = await getRole(roleId)
      const menuResponse = await roleMenuTreeselect(roleId)
      
      form.setFieldsValue({
        ...roleResponse.data,
        roleSort: Number(roleResponse.data.roleSort)
      })
      setMenuOptions(menuResponse.menus || [])
      // 关键：权限回显（Antd Tree 需要受控 checkedKeys）
      setMenuCheckedKeys(normalizeCascadeCheckedKeys(menuResponse.menus || [], menuResponse.checkedKeys || []))
      setMenuHalfCheckedKeys([])
      // 提交仍保留后端返回的原始 keys，避免“打开不改直接保存”丢权限
      menuCheckedKeysRef.current = menuResponse.checkedKeys || []
      menuHalfCheckedKeysRef.current = []
      
      setOpen(true)
      setTitle('修改角色')
      setIsEdit(true)
    } catch (error) {
      console.error('Failed to get role:', error)
      modal.msgError('获取角色信息失败')
    }
  }

  // 删除
  const handleDelete = (row) => {
    const roleIds = row?.roleId || selectedRowKeys
    Modal.confirm({
      title: '提示',
      content: `是否确认删除角色编号为"${roleIds}"的数据项?`,
      onOk: async () => {
        try {
          await delRole(roleIds)
          modal.msgSuccess('删除成功')
          getList()
        } catch (error) {
          console.error('Failed to delete role:', error)
        }
      }
    })
  }

  // 状态修改
  const handleStatusChange = (row) => {
    const text = row.status === '0' ? '启用' : '停用'
    Modal.confirm({
      title: '提示',
      content: `确认要"${text}""${row.roleName}"角色吗?`,
      onOk: async () => {
        try {
          await changeRoleStatus(row.roleId, row.status)
          modal.msgSuccess(`${text}成功`)
          getList()
        } catch (error) {
          row.status = row.status === '0' ? '1' : '0'
          console.error('Failed to change status:', error)
        }
      },
      onCancel: () => {
        row.status = row.status === '0' ? '1' : '0'
      }
    })
  }

  // 分配用户
  const handleAuthUser = (row) => {
    navigate(`/system/role-auth/user/${row.roleId}`)
  }

  // 数据权限
  const handleDataScope = async (row) => {
    resetDataScope()
    try {
      const roleResponse = await getRole(row.roleId)
      const deptResponse = await deptTreeSelect(row.roleId)
      
      dataScopeForm.setFieldsValue(roleResponse.data)
      setDeptOptions(deptResponse.depts || [])
      setDeptCheckedKeys(deptResponse.checkedKeys || [])
      setDeptHalfCheckedKeys([])
      deptCheckedKeysRef.current = deptResponse.checkedKeys || []
      deptHalfCheckedKeysRef.current = []
      setOpenDataScope(true)
      setTitle('分配数据权限')
    } catch (error) {
      console.error('Failed to get role data scope:', error)
    }
  }

  // 导出
  const handleExport = () => {
    download('system/role/export', queryParams, `role_${new Date().getTime()}.xlsx`)
  }

  // 查询菜单树结构
  const getMenuTreeselect = async () => {
    try {
      const response = await menuTreeselect()
      setMenuOptions(response.data || [])
    } catch (error) {
      console.error('Failed to get menu tree:', error)
    }
  }

  const collectTreeKeys = (nodes) => {
    const keys = []
    const walk = (list) => {
      ;(list || []).forEach((n) => {
        keys.push(n.id)
        if (n.children && n.children.length) walk(n.children)
      })
    }
    walk(nodes)
    return keys
  }

  /**
   * Normalize checked keys for Antd Tree in cascade mode:
   * If a parent key exists but not all descendants are selected,
   * do NOT keep the parent in `checkedKeys`, otherwise Antd will auto-check all children.
   */
  const normalizeCascadeCheckedKeys = (treeData, checkedKeys) => {
    const raw = Array.isArray(checkedKeys) ? checkedKeys : []
    const rawSet = new Set(raw)
    const result = []

    const dfs = (node) => {
      const children = node?.children || []
      const hasChildren = children.length > 0
      const selfChecked = rawSet.has(node.id)

      if (!hasChildren) {
        if (selfChecked) result.push(node.id)
        return selfChecked
      }

      let allChildrenFullyChecked = true
      for (const child of children) {
        const childFully = dfs(child)
        if (!childFully) allChildrenFullyChecked = false
      }

      const fullyChecked = selfChecked && allChildrenFullyChecked
      if (fullyChecked) result.push(node.id)
      return fullyChecked
    }

    ;(treeData || []).forEach(dfs)
    return Array.from(new Set(result))
  }

  // 表单重置
  const reset = () => {
    setMenuCheckedKeys([])
    setMenuHalfCheckedKeys([])
    setMenuExpandedKeys([])
    setDeptCheckedKeys([])
    setDeptHalfCheckedKeys([])
    setDeptExpandedKeys([])
    menuCheckedKeysRef.current = []
    menuHalfCheckedKeysRef.current = []
    deptCheckedKeysRef.current = []
    deptHalfCheckedKeysRef.current = []
    setMenuExpand(false)
    setMenuNodeAll(false)
    setDeptExpand(true)
    setDeptNodeAll(false)
    form.resetFields()
    form.setFieldsValue({
      roleId: undefined,
      roleName: undefined,
      roleKey: undefined,
      roleSort: 0,
      status: '0',
      menuIds: [],
      deptIds: [],
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      remark: undefined,
      dataScope: '1'
    })
  }

  // 数据权限表单重置
  const resetDataScope = () => {
    setDeptCheckedKeys([])
    setDeptHalfCheckedKeys([])
    setDeptExpandedKeys([])
    deptCheckedKeysRef.current = []
    deptHalfCheckedKeysRef.current = []
    setDeptExpand(true)
    setDeptNodeAll(false)
    dataScopeForm.resetFields()
    dataScopeForm.setFieldsValue({
      dataScope: '1'
    })
  }

  // 取消
  const cancel = () => {
    setOpen(false)
    reset()
  }

  // 取消数据权限
  const cancelDataScope = () => {
    setOpenDataScope(false)
    resetDataScope()
  }

  // 树权限（展开/折叠）
  const handleCheckedTreeExpand = (checked, type) => {
    if (type === 'menu') {
      setMenuExpand(checked)
      setMenuExpandedKeys(checked ? collectTreeKeys(menuOptions) : [])
    } else if (type === 'dept') {
      setDeptExpand(checked)
      setDeptExpandedKeys(checked ? collectTreeKeys(deptOptions) : [])
    }
  }

  // 树权限（全选/全不选）
  const handleCheckedTreeNodeAll = (checked, type) => {
    if (type === 'menu') {
      setMenuNodeAll(checked)
      setMenuCheckedKeys(checked ? collectTreeKeys(menuOptions) : [])
      setMenuHalfCheckedKeys([])
      menuCheckedKeysRef.current = checked ? collectTreeKeys(menuOptions) : []
      menuHalfCheckedKeysRef.current = []
    } else if (type === 'dept') {
      setDeptNodeAll(checked)
      setDeptCheckedKeys(checked ? collectTreeKeys(deptOptions) : [])
      setDeptHalfCheckedKeys([])
      deptCheckedKeysRef.current = checked ? collectTreeKeys(deptOptions) : []
      deptHalfCheckedKeysRef.current = []
    }
  }

  // 树权限（父子联动）
  const handleCheckedTreeConnect = (checked, type) => {
    if (type === 'menu') {
      // checked=true 表示开启“父子联动”(级联)：Antd Tree 需要 checkStrictly=false
      form.setFieldValue('menuCheckStrictly', checked)
    } else if (type === 'dept') {
      dataScopeForm.setFieldValue('deptCheckStrictly', checked)
    }
  }

  // 获取所有菜单节点数据
  const getMenuAllCheckedKeys = () => {
    return Array.from(new Set([...(menuCheckedKeysRef.current || []), ...(menuHalfCheckedKeysRef.current || [])]))
  }

  // 获取所有部门节点数据
  const getDeptAllCheckedKeys = () => {
    return Array.from(new Set([...(deptCheckedKeysRef.current || []), ...(deptHalfCheckedKeysRef.current || [])]))
  }

  // 提交表单
  const submitForm = async () => {
    try {
      const values = await form.validateFields()
      values.menuIds = getMenuAllCheckedKeys()
      
      if (values.roleId !== undefined && values.roleId !== null && values.roleId !== '') {
        await updateRole(values)
        modal.msgSuccess('修改成功')
      } else {
        await addRole(values)
        modal.msgSuccess('新增成功')
      }
      setOpen(false)
      getList()
    } catch (error) {
      console.error('Validation failed:', error)
    }
  }

  // 提交数据权限
  const submitDataScope = async () => {
    try {
      const values = dataScopeForm.getFieldsValue()
      if (values.dataScope === '2') {
        values.deptIds = getDeptAllCheckedKeys()
      } else {
        values.deptIds = []
      }
      
      await dataScope(values)
      modal.msgSuccess('修改成功')
      setOpenDataScope(false)
      getList()
    } catch (error) {
      console.error('Failed to submit data scope:', error)
    }
  }

  // 数据权限范围变化
  const dataScopeSelectChange = (value) => {
    if (value !== '2') {
      setDeptCheckedKeys([])
      setDeptHalfCheckedKeys([])
      deptCheckedKeysRef.current = []
      deptHalfCheckedKeysRef.current = []
    }
  }

  // 双击行
  const handleRowDblClick = (row) => {
    if (row.roleId !== 1 && auth.hasPermiOr(['system:role:edit'])) {
      handleUpdate(row)
    }
  }

  // 表格列定义
  const columns = [
    {
      title: '角色编号',
      dataIndex: 'roleId',
      key: 'roleId',
      width: 120
    },
    {
      title: '角色名称',
      dataIndex: 'roleName',
      key: 'roleName',
      ellipsis: true,
      width: 150
    },
    {
      title: '权限字符',
      dataIndex: 'roleKey',
      key: 'roleKey',
      ellipsis: true,
      width: 150
    },
    {
      title: '显示顺序',
      dataIndex: 'roleSort',
      key: 'roleSort',
      width: 100
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      align: 'center',
      width: 100,
      render: (_, record) => (
        <Switch
          checked={record.status === '0'}
          onChange={(checked) => {
            record.status = checked ? '0' : '1'
            handleStatusChange(record)
          }}
          checkedChildren="启用"
          unCheckedChildren="停用"
        />
      )
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      key: 'createTime',
      align: 'center',
      render: (text) => parseTime(text)
    },
    {
      title: '操作',
      key: 'action',
      align: 'center',
      fixed: 'right',
      width: 200,
      render: (_, record) => {
        if (record.roleId === 1) return null
        return (
          <Space size="small">
            {auth.hasPermiOr(['system:role:edit']) && (
              <Tooltip title="修改">
                <Button
                  type="link"
                  icon={<EditOutlined />}
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleUpdate(record)
                  }}
                />
              </Tooltip>
            )}
            {auth.hasPermiOr(['system:role:remove']) && (
              <Tooltip title="删除">
                <Button
                  type="link"
                  danger
                  icon={<DeleteOutlined />}
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleDelete(record)
                  }}
                />
              </Tooltip>
            )}
            {auth.hasPermiOr(['system:role:edit']) && (
              <Tooltip title="数据权限">
                <Button
                  type="link"
                  icon={<DatabaseOutlined />}
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleDataScope(record)
                  }}
                />
              </Tooltip>
            )}
            {auth.hasPermiOr(['system:role:edit']) && (
              <Tooltip title="分配用户">
                <Button
                  type="link"
                  icon={<UserOutlined />}
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleAuthUser(record)
                  }}
                />
              </Tooltip>
            )}
          </Space>
        )
      }
    }
  ]

  const rowSelection = {
    selectedRowKeys,
    onChange: handleSelectionChange
  }

  return (
    <div className="app-container">
      <Form
        form={queryForm}
        layout="inline"
        className="search-form"
        style={{ display: showSearch ? 'flex' : 'none', marginBottom: 16 }}
      >
        <Form.Item label="角色名称" name="roleName">
          <Input
            placeholder="请输入角色名称"
            style={{ width: 240 }}
            onPressEnter={handleQuery}
            allowClear
          />
        </Form.Item>
        <Form.Item label="权限字符" name="roleKey">
          <Input
            placeholder="请输入权限字符"
            style={{ width: 240 }}
            onPressEnter={handleQuery}
            allowClear
          />
        </Form.Item>
        <Form.Item label="状态" name="status">
          <Select
            placeholder="角色状态"
            style={{ width: 240 }}
            allowClear
          >
            {sys_normal_disable.sys_normal_disable?.map(dict => (
              <Select.Option key={dict.value} value={dict.value}>
                {dict.label}
              </Select.Option>
            ))}
          </Select>
        </Form.Item>
        <Form.Item label="创建时间">
          <RangePicker
            value={dateRange.length ? [dayjs(dateRange[0]), dayjs(dateRange[1])] : null}
            onChange={(dates) => {
              setDateRange(dates ? [dates[0].format('YYYY-MM-DD'), dates[1].format('YYYY-MM-DD')] : [])
            }}
            format="YYYY-MM-DD"
          />
        </Form.Item>
        <Form.Item>
          <Button type="primary" icon={<SearchOutlined />} onClick={handleQuery}>
            搜索
          </Button>
          <Button icon={<ReloadOutlined />} onClick={resetQuery} style={{ marginLeft: 8 }}>
            重置
          </Button>
        </Form.Item>
      </Form>

      <div style={{ marginBottom: 16 }}>
        <Space>
          {auth.hasPermiOr(['system:role:add']) && (
            <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
              新增
            </Button>
          )}
          {auth.hasPermiOr(['system:role:edit']) && (
            <Button
              type="default"
              icon={<EditOutlined />}
              disabled={selectedRowKeys.length !== 1}
              onClick={() => handleUpdate({ roleId: selectedRowKeys[0] })}
            >
              修改
            </Button>
          )}
          {auth.hasPermiOr(['system:role:remove']) && (
            <Button
              type="default"
              danger
              icon={<DeleteOutlined />}
              disabled={!selectedRowKeys.length}
              onClick={() => handleDelete()}
            >
              删除
            </Button>
          )}
          {auth.hasPermiOr(['system:role:export']) && (
            <Button type="default" icon={<DownloadOutlined />} onClick={handleExport}>
              导出
            </Button>
          )}
          <RightToolbar
            showSearch={showSearch}
            columns={{}}
            onShowSearchChange={setShowSearch}
            onQueryTable={getList}
          />
        </Space>
      </div>

      <Table
        loading={loading}
        dataSource={roleList}
        columns={columns}
        rowSelection={rowSelection}
        rowKey="roleId"
        onRow={(record) => ({
          onDoubleClick: () => handleRowDblClick(record)
        })}
        pagination={false}
      />

      <Pagination
        total={total}
        page={queryParams.pageNum}
        limit={queryParams.pageSize}
        onChange={handlePagination}
      />

      {/* 添加或修改角色对话框 */}
      <Modal
        title={title}
        open={open}
        onCancel={cancel}
        onOk={submitForm}
        width={500}
        destroyOnHidden
      >
        <Form
          form={form}
          labelCol={{ span: 6 }}
          wrapperCol={{ span: 18 }}
        >
          {/* 关键：编辑时需要带上 roleId，否则 submitForm 会误判为新增 */}
          <Form.Item name="roleId" hidden>
            <Input />
          </Form.Item>

          <Form.Item
            label="角色名称"
            name="roleName"
            rules={[{ required: true, message: '角色名称不能为空' }]}
          >
            <Input placeholder="请输入角色名称" />
          </Form.Item>
          <Form.Item
            label={
              <span>
                <Tooltip title="控制器中定义的权限字符，如：@PreAuthorize(`@ss.hasRole('admin')`)">
                  <QuestionCircleOutlined style={{ marginRight: 4 }} />
                </Tooltip>
                权限字符
              </span>
            }
            name="roleKey"
            rules={[{ required: true, message: '权限字符不能为空' }]}
          >
            <Input placeholder="请输入权限字符" />
          </Form.Item>
          <Form.Item
            label="角色顺序"
            name="roleSort"
            rules={[{ required: true, message: '角色顺序不能为空' }]}
          >
            <InputNumber min={0} style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item label="状态" name="status">
            <Radio.Group>
              {sys_normal_disable.sys_normal_disable?.map(dict => (
                <Radio key={dict.value} value={dict.value}>
                  {dict.label}
                </Radio>
              ))}
            </Radio.Group>
          </Form.Item>
          <Form.Item label="菜单权限">
            <Space style={{ marginBottom: 8 }}>
              <Checkbox
                checked={menuExpand}
                onChange={(e) => handleCheckedTreeExpand(e.target.checked, 'menu')}
              >
                展开/折叠
              </Checkbox>
              <Checkbox
                checked={menuNodeAll}
                onChange={(e) => handleCheckedTreeNodeAll(e.target.checked, 'menu')}
              >
                全选/全不选
              </Checkbox>
              <Checkbox
                checked={menuCheckStrictlyValue !== false}
                onChange={(e) => handleCheckedTreeConnect(e.target.checked, 'menu')}
              >
                父子联动
              </Checkbox>
            </Space>
            <Tree
              ref={menuTreeRef}
              checkable
              treeData={menuOptions}
              fieldNames={{ title: 'label', key: 'id', children: 'children' }}
              // menuCheckStrictlyValue=true 表示“父子联动(级联)”，因此 checkStrictly 要取反
              checkStrictly={!(menuCheckStrictlyValue !== false)}
              expandedKeys={menuExpandedKeys}
              onExpand={(keys) => setMenuExpandedKeys(keys)}
              checkedKeys={
                // 严格模式(checkStrictly=true) 需要对象；级联模式用数组即可
                !(menuCheckStrictlyValue !== false)
                  ? { checked: menuCheckedKeys, halfChecked: menuHalfCheckedKeys }
                  : menuCheckedKeys
              }
              onCheck={(checked, info) => {
                if (Array.isArray(checked)) {
                  setMenuCheckedKeys(checked)
                  setMenuHalfCheckedKeys(info?.halfCheckedKeys || [])
                  menuCheckedKeysRef.current = checked
                  menuHalfCheckedKeysRef.current = info?.halfCheckedKeys || []
                } else {
                  const nextChecked = checked?.checked || []
                  const nextHalf = checked?.halfChecked || info?.halfCheckedKeys || []
                  setMenuCheckedKeys(nextChecked)
                  setMenuHalfCheckedKeys(nextHalf)
                  menuCheckedKeysRef.current = nextChecked
                  menuHalfCheckedKeysRef.current = nextHalf
                }
              }}
              style={{ maxHeight: '300px', overflow: 'auto', border: '1px solid #d9d9d9', padding: '8px' }}
            />
          </Form.Item>
          <Form.Item label="备注" name="remark">
            <TextArea placeholder="请输入内容" rows={3} />
          </Form.Item>
        </Form>
      </Modal>

      {/* 分配数据权限对话框 */}
      <Modal
        title={title}
        open={openDataScope}
        onCancel={cancelDataScope}
        onOk={submitDataScope}
        width={500}
        destroyOnHidden
      >
        <Form
          form={dataScopeForm}
          labelCol={{ span: 6 }}
          wrapperCol={{ span: 18 }}
        >
          <Form.Item label="角色名称" name="roleName">
            <Input disabled />
          </Form.Item>
          <Form.Item label="权限字符" name="roleKey">
            <Input disabled />
          </Form.Item>
          <Form.Item label="权限范围" name="dataScope">
            <Select onChange={dataScopeSelectChange}>
              {dataScopeOptions.map(item => (
                <Select.Option key={item.value} value={item.value}>
                  {item.label}
                </Select.Option>
              ))}
            </Select>
          </Form.Item>
          {dataScopeValue === '2' && (
            <Form.Item label="数据权限">
              <Space style={{ marginBottom: 8 }}>
                <Checkbox
                  checked={deptExpand}
                  onChange={(e) => handleCheckedTreeExpand(e.target.checked, 'dept')}
                >
                  展开/折叠
                </Checkbox>
                <Checkbox
                  checked={deptNodeAll}
                  onChange={(e) => handleCheckedTreeNodeAll(e.target.checked, 'dept')}
                >
                  全选/全不选
                </Checkbox>
              <Checkbox
                checked={deptCheckStrictlyValue !== false}
                onChange={(e) => handleCheckedTreeConnect(e.target.checked, 'dept')}
              >
                父子联动
              </Checkbox>
              </Space>
              <Tree
                ref={deptTreeRef}
                checkable
                treeData={deptOptions}
                fieldNames={{ title: 'label', key: 'id', children: 'children' }}
                // deptCheckStrictlyValue=true 表示“父子联动(级联)”，因此 checkStrictly 要取反
                checkStrictly={!(deptCheckStrictlyValue !== false)}
                expandedKeys={deptExpandedKeys}
                onExpand={(keys) => setDeptExpandedKeys(keys)}
                checkedKeys={
                  !(deptCheckStrictlyValue !== false)
                    ? { checked: deptCheckedKeys, halfChecked: deptHalfCheckedKeys }
                    : deptCheckedKeys
                }
                onCheck={(checked, info) => {
                  if (Array.isArray(checked)) {
                    setDeptCheckedKeys(checked)
                    setDeptHalfCheckedKeys(info?.halfCheckedKeys || [])
                    deptCheckedKeysRef.current = checked
                    deptHalfCheckedKeysRef.current = info?.halfCheckedKeys || []
                  } else {
                    const nextChecked = checked?.checked || []
                    const nextHalf = checked?.halfChecked || info?.halfCheckedKeys || []
                    setDeptCheckedKeys(nextChecked)
                    setDeptHalfCheckedKeys(nextHalf)
                    deptCheckedKeysRef.current = nextChecked
                    deptHalfCheckedKeysRef.current = nextHalf
                  }
                }}
                style={{ maxHeight: '300px', overflow: 'auto', border: '1px solid #d9d9d9', padding: '8px' }}
              />
            </Form.Item>
          )}
        </Form>
      </Modal>
    </div>
  )
}

export default Role

// ruoyi-front/src/views/system/role/index.vue
<template>
   <div class="app-container">
      <el-form :model="queryParams" ref="queryRef" v-show="showSearch" :inline="true" label-width="68px" class="search-form">
         <el-form-item label="角色名称" prop="roleName">
            <el-input
               v-model="queryParams.roleName"
               placeholder="请输入角色名称"
               clearable
               style="width: 240px"
               @keyup.enter="handleQuery"
            />
         </el-form-item>
         <el-form-item label="权限字符" prop="roleKey">
            <el-input
               v-model="queryParams.roleKey"
               placeholder="请输入权限字符"
               clearable
               style="width: 240px"
               @keyup.enter="handleQuery"
            />
         </el-form-item>
         <el-form-item label="状态" prop="status">
            <el-select
               v-model="queryParams.status"
               placeholder="角色状态"
               clearable
               style="width: 240px"
            >
               <el-option
                  v-for="dict in sys_normal_disable"
                  :key="dict.value"
                  :label="dict.label"
                  :value="dict.value"
               />
            </el-select>
         </el-form-item>
         <el-form-item label="创建时间" style="width: 308px">
            <el-date-picker
               v-model="dateRange"
               value-format="YYYY-MM-DD"
               type="daterange"
               range-separator="-"
               start-placeholder="开始日期"
               end-placeholder="结束日期"
            ></el-date-picker>
         </el-form-item>
         <el-form-item>
            <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
            <el-button icon="Refresh" @click="resetQuery">重置</el-button>
         </el-form-item>
      </el-form>
      <el-row :gutter="10" class="mb8">
         <el-col :span="1.5">
            <el-button
               type="primary"
               plain
               icon="Plus"
               @click="handleAdd"
               v-hasPermi="['system:role:add']"
            >新增</el-button>
         </el-col>
         <el-col :span="1.5">
            <el-button
               type="success"
               plain
               icon="Edit"
               :disabled="single"
               @click="handleUpdate"
               v-hasPermi="['system:role:edit']"
            >修改</el-button>
         </el-col>
         <el-col :span="1.5">
            <el-button
               type="danger"
               plain
               icon="Delete"
               :disabled="multiple"
               @click="handleDelete"
               v-hasPermi="['system:role:remove']"
            >删除</el-button>
         </el-col>
         <el-col :span="1.5">
            <el-button
               type="warning"
               plain
               icon="Download"
               @click="handleExport"
               v-hasPermi="['system:role:export']"
            >导出</el-button>
         </el-col>
         <right-toolbar v-model:showSearch="showSearch" @queryTable="getList"></right-toolbar>
      </el-row>

      <!-- 表格数据 -->
      <el-table 
         v-loading="loading" 
         :data="roleList" 
         @selection-change="handleSelectionChange"
         @row-dblclick="handleRowDblClick"
         @row-click="handleRowClick"
         stripe
         style="width: 100%"
         class="role-table"
      >
         <el-table-column type="selection" width="55" align="center" />
         <el-table-column label="角色编号" prop="roleId" width="120" />
         <el-table-column label="角色名称" prop="roleName" :show-overflow-tooltip="true" width="150" />
         <el-table-column label="权限字符" prop="roleKey" :show-overflow-tooltip="true" width="150" />
         <el-table-column label="显示顺序" prop="roleSort" width="100" />
         <el-table-column label="状态" align="center" width="100">
            <template #default="scope">
               <el-switch
                  v-model="scope.row.status"
                  active-value="0"
                  inactive-value="1"
                  @change="handleStatusChange(scope.row)"
               ></el-switch>
            </template>
         </el-table-column>
         <el-table-column label="创建时间" align="center" prop="createTime">
            <template #default="scope">
               <span>{{ parseTime(scope.row.createTime) }}</span>
            </template>
         </el-table-column>
         <el-table-column label="操作" align="center" fixed="right" width="200">
            <template #default="scope">
              <div class="action-buttons" v-if="scope.row.roleId !== 1">
                <el-tooltip content="修改" placement="top">
                  <el-button 
                     link 
                     type="primary" 
                     icon="Edit" 
                     size="small"
                     @click.stop="handleUpdate(scope.row)" 
                     v-hasPermi="['system:role:edit']"
                  ></el-button>
                </el-tooltip>
                <el-tooltip content="删除" placement="top">
                  <el-button 
                     link 
                     type="danger" 
                     icon="Delete" 
                     size="small"
                     @click.stop="handleDelete(scope.row)" 
                     v-hasPermi="['system:role:remove']"
                  ></el-button>
                </el-tooltip>
                <el-tooltip content="数据权限" placement="top">
                  <el-button 
                     link 
                     type="primary" 
                     icon="CircleCheck" 
                     size="small"
                     @click.stop="handleDataScope(scope.row)" 
                     v-hasPermi="['system:role:edit']"
                  ></el-button>
                </el-tooltip>
                <el-tooltip content="分配用户" placement="top">
                  <el-button 
                     link 
                     type="primary" 
                     icon="User" 
                     size="small"
                     @click.stop="handleAuthUser(scope.row)" 
                     v-hasPermi="['system:role:edit']"
                  ></el-button>
                </el-tooltip>
              </div>
            </template>
         </el-table-column>
      </el-table>

      <pagination
         v-show="total > 0"
         :total="total"
         v-model:page="queryParams.pageNum"
         v-model:limit="queryParams.pageSize"
         @pagination="getList"
      />

      <!-- 添加或修改角色配置对话框 -->
      <el-dialog :title="title" v-model="open" width="500px" append-to-body :close-on-click-modal="false">
         <el-form ref="roleRef" :model="form" :rules="rules" label-width="100px">
            <el-form-item label="角色名称" prop="roleName">
               <el-input v-model="form.roleName" placeholder="请输入角色名称" />
            </el-form-item>
            <el-form-item prop="roleKey">
               <template #label>
                  <span>
                     <el-tooltip content="控制器中定义的权限字符，如：@PreAuthorize(`@ss.hasRole('admin')`)" placement="top">
                        <el-icon><question-filled /></el-icon>
                     </el-tooltip>
                     权限字符
                  </span>
               </template>
               <el-input v-model="form.roleKey" placeholder="请输入权限字符" />
            </el-form-item>
            <el-form-item label="角色顺序" prop="roleSort">
               <el-input-number v-model="form.roleSort" controls-position="right" :min="0" />
            </el-form-item>
            <el-form-item label="状态">
               <el-radio-group v-model="form.status">
                  <el-radio
                     v-for="dict in sys_normal_disable"
                     :key="dict.value"
                     :value="dict.value"
                  >{{ dict.label }}</el-radio>
               </el-radio-group>
            </el-form-item>
            <el-form-item label="菜单权限">
               <el-checkbox v-model="menuExpand" @change="handleCheckedTreeExpand($event, 'menu')">展开/折叠</el-checkbox>
               <el-checkbox v-model="menuNodeAll" @change="handleCheckedTreeNodeAll($event, 'menu')">全选/全不选</el-checkbox>
               <el-checkbox v-model="form.menuCheckStrictly" @change="handleCheckedTreeConnect($event, 'menu')">父子联动</el-checkbox>
               <el-tree
                  class="tree-border"
                  :data="menuOptions"
                  show-checkbox
                  ref="menuRef"
                  node-key="id"
                  :check-strictly="!form.menuCheckStrictly"
                  empty-text="加载中，请稍候"
                  :props="{ label: 'label', children: 'children' }"
               ></el-tree>
            </el-form-item>
            <el-form-item label="备注">
               <el-input v-model="form.remark" type="textarea" placeholder="请输入内容"></el-input>
            </el-form-item>
         </el-form>
         <template #footer>
            <div class="dialog-footer">
               <el-button @click="cancel">取 消</el-button>
               <el-button type="primary" @click="submitForm">确 定</el-button>
            </div>
         </template>
      </el-dialog>

      <!-- 分配角色数据权限对话框 -->
      <el-dialog :title="title" v-model="openDataScope" width="500px" append-to-body :close-on-click-modal="false">
         <el-form :model="form" label-width="80px">
            <el-form-item label="角色名称">
               <el-input v-model="form.roleName" :disabled="true" />
            </el-form-item>
            <el-form-item label="权限字符">
               <el-input v-model="form.roleKey" :disabled="true" />
            </el-form-item>
            <el-form-item label="权限范围">
               <el-select v-model="form.dataScope" @change="dataScopeSelectChange">
                  <el-option
                     v-for="item in dataScopeOptions"
                     :key="item.value"
                     :label="item.label"
                     :value="item.value"
                  ></el-option>
               </el-select>
            </el-form-item>
            <el-form-item label="数据权限" v-show="form.dataScope == 2">
               <el-checkbox v-model="deptExpand" @change="handleCheckedTreeExpand($event, 'dept')">展开/折叠</el-checkbox>
               <el-checkbox v-model="deptNodeAll" @change="handleCheckedTreeNodeAll($event, 'dept')">全选/全不选</el-checkbox>
               <el-checkbox v-model="form.deptCheckStrictly" @change="handleCheckedTreeConnect($event, 'dept')">父子联动</el-checkbox>
               <el-tree
                  class="tree-border"
                  :data="deptOptions"
                  show-checkbox
                  default-expand-all
                  ref="deptRef"
                  node-key="id"
                  :check-strictly="!form.deptCheckStrictly"
                  empty-text="加载中，请稍候"
                  :props="{ label: 'label', children: 'children' }"
               ></el-tree>
            </el-form-item>
         </el-form>
         <template #footer>
            <div class="dialog-footer">
               <el-button @click="cancelDataScope">取 消</el-button>
               <el-button type="primary" @click="submitDataScope">确 定</el-button>
            </div>
         </template>
      </el-dialog>
   </div>
</template>

<script setup name="Role">
import { addRole, changeRoleStatus, dataScope, delRole, getRole, listRole, updateRole, deptTreeSelect } from "@/api/system/role"
import { roleMenuTreeselect, treeselect as menuTreeselect } from "@/api/system/menu"

const router = useRouter()
const { proxy } = getCurrentInstance()
const { sys_normal_disable } = proxy.useDict("sys_normal_disable")

const roleList = ref([])
const open = ref(false)
const loading = ref(true)
const showSearch = ref(true)
const ids = ref([])
const single = ref(true)
const multiple = ref(true)
const total = ref(0)
const title = ref("")
const dateRange = ref([])
const menuOptions = ref([])
const menuExpand = ref(false)
const menuNodeAll = ref(false)
const deptExpand = ref(true)
const deptNodeAll = ref(false)
const deptOptions = ref([])
const openDataScope = ref(false)
const menuRef = ref(null)
const deptRef = ref(null)

/** 数据范围选项*/
const dataScopeOptions = ref([
  { value: "1", label: "全部数据权限" },
  { value: "2", label: "自定数据权限" },
  { value: "3", label: "本部门数据权限" },
  { value: "4", label: "本部门及以下数据权限" },
  { value: "5", label: "仅本人数据权限" }
])

const data = reactive({
  form: {},
  queryParams: {
    pageNum: 1,
    pageSize: 10,
    roleName: undefined,
    roleKey: undefined,
    status: undefined
  },
  rules: {
    roleName: [{ required: true, message: "角色名称不能为空", trigger: "blur" }],
    roleKey: [{ required: true, message: "权限字符不能为空", trigger: "blur" }],
    roleSort: [{ required: true, message: "角色顺序不能为空", trigger: "blur" }]
  },
})

const { queryParams, form, rules } = toRefs(data)

/** 查询角色列表 */
function getList() {
  loading.value = true
  listRole(proxy.addDateRange(queryParams.value, dateRange.value)).then(response => {
    roleList.value = response.rows
    total.value = response.total
    loading.value = false
  })
}

/** 搜索按钮操作 */
function handleQuery() {
  queryParams.value.pageNum = 1
  getList()
}

/** 重置按钮操作 */
function resetQuery() {
  dateRange.value = []
  proxy.resetForm("queryRef")
  handleQuery()
}

/** 删除按钮操作 */
function handleDelete(row) {
  const roleIds = row.roleId || ids.value
  proxy.$modal.confirm('是否确认删除角色编号为"' + roleIds + '"的数据项?').then(function () {
    return delRole(roleIds)
  }).then(() => {
    getList()
    proxy.$modal.msgSuccess("删除成功")
  }).catch(() => {})
}

/** 导出按钮操作 */
function handleExport() {
  proxy.download("system/role/export", {
    ...queryParams.value,
  }, `role_${new Date().getTime()}.xlsx`)
}

/** 多选框选中数据 */
function handleSelectionChange(selection) {
  ids.value = selection.map(item => item.roleId)
  single.value = selection.length != 1
  multiple.value = !selection.length
}

/** 角色状态修改 */
function handleStatusChange(row) {
  let text = row.status === "0" ? "启用" : "停用"
  proxy.$modal.confirm('确认要"' + text + '""' + row.roleName + '"角色吗?').then(function () {
    return changeRoleStatus(row.roleId, row.status)
  }).then(() => {
    proxy.$modal.msgSuccess(text + "成功")
  }).catch(function () {
    row.status = row.status === "0" ? "1" : "0"
  })
}

/** 更多操作 */
function handleCommand(command, row) {
  switch (command) {
    case "handleDataScope":
      handleDataScope(row)
      break
    case "handleAuthUser":
      handleAuthUser(row)
      break
    default:
      break
  }
}

/** 分配用户 */
function handleAuthUser(row) {
  router.push("/system/role-auth/user/" + row.roleId)
}

/** 查询菜单树结构 */
function getMenuTreeselect() {
  menuTreeselect().then(response => {
    menuOptions.value = response.data
  })
}

/** 所有部门节点数据 */
function getDeptAllCheckedKeys() {
  // 目前被选中的部门节点
  let checkedKeys = deptRef.value.getCheckedKeys()
  // 半选中的部门节点
  let halfCheckedKeys = deptRef.value.getHalfCheckedKeys()
  checkedKeys.unshift.apply(checkedKeys, halfCheckedKeys)
  return checkedKeys
}

/** 重置新增的表单以及其他数据  */
function reset() {
  if (menuRef.value != undefined) {
    menuRef.value.setCheckedKeys([])
  }
  menuExpand.value = false
  menuNodeAll.value = false
  deptExpand.value = true
  deptNodeAll.value = false
  form.value = {
    roleId: undefined,
    roleName: undefined,
    roleKey: undefined,
    roleSort: 0,
    status: "0",
    menuIds: [],
    deptIds: [],
    menuCheckStrictly: true,
    deptCheckStrictly: true,
    remark: undefined
  }
  proxy.resetForm("roleRef")
}

/** 添加角色 */
function handleAdd() {
  reset()
  getMenuTreeselect()
  open.value = true
  title.value = "添加角色"
}

/** 单击行操作（用于选中） */
function handleRowClick(row, column, event) {
  if (event?.target?.closest('.action-buttons')) {
    return
  }
}

/** 双击行操作 */
function handleRowDblClick(row, column, event) {
  if (event?.target?.closest('.action-buttons')) {
    return
  }
  if (row.roleId !== 1 && proxy.hasPermi(['system:role:edit'])) {
    handleUpdate(row)
  }
}

/** 修改角色 */
function handleUpdate(row) {
  reset()
  if (!row || typeof row !== 'object') {
    return
  }
  
  const roleId = row.roleId || (Array.isArray(ids.value) && ids.value.length === 1 ? ids.value[0] : null)
  
  if (!roleId) {
    proxy.$modal.msgWarning("请选择要修改的角色")
    return
  }
  
  const roleMenu = getRoleMenuTreeselect(roleId)
  getRole(roleId).then(response => {
    form.value = response.data
    form.value.roleSort = Number(form.value.roleSort)
    open.value = true
    nextTick(() => {
      roleMenu.then((res) => {
        let checkedKeys = res.checkedKeys
        checkedKeys.forEach((v) => {
          nextTick(() => {
            menuRef.value.setChecked(v, true, false)
          })
        })
      })
    })
  }).catch(error => {
    console.error("获取角色信息失败:", error)
    proxy.$modal.msgError("获取角色信息失败")
  })
  title.value = "修改角色"
}

/** 根据角色ID查询菜单树结构 */
function getRoleMenuTreeselect(roleId) {
  return roleMenuTreeselect(roleId).then(response => {
    menuOptions.value = response.menus
    return response
  })
}

/** 根据角色ID查询部门树结构 */
function getDeptTree(roleId) {
  return deptTreeSelect(roleId).then(response => {
    deptOptions.value = response.depts
    return response
  })
}

/** 树权限（展开/折叠）*/
function handleCheckedTreeExpand(value, type) {
  if (type == "menu") {
    let treeList = menuOptions.value
    for (let i = 0; i < treeList.length; i++) {
      menuRef.value.store.nodesMap[treeList[i].id].expanded = value
    }
  } else if (type == "dept") {
    let treeList = deptOptions.value
    for (let i = 0; i < treeList.length; i++) {
      deptRef.value.store.nodesMap[treeList[i].id].expanded = value
    }
  }
}

/** 树权限（全选/全不选） */
function handleCheckedTreeNodeAll(value, type) {
  if (type == "menu") {
    menuRef.value.setCheckedNodes(value ? menuOptions.value : [])
  } else if (type == "dept") {
    deptRef.value.setCheckedNodes(value ? deptOptions.value : [])
  }
}

/** 树权限（父子联动） */
function handleCheckedTreeConnect(value, type) {
  if (type == "menu") {
    form.value.menuCheckStrictly = value ? true : false
  } else if (type == "dept") {
    form.value.deptCheckStrictly = value ? true : false
  }
}

/** 所有菜单节点数据 */
function getMenuAllCheckedKeys() {
  // 目前被选中的菜单节点
  let checkedKeys = menuRef.value.getCheckedKeys()
  // 半选中的菜单节点
  let halfCheckedKeys = menuRef.value.getHalfCheckedKeys()
  checkedKeys.unshift.apply(checkedKeys, halfCheckedKeys)
  return checkedKeys
}

/** 提交按钮 */
function submitForm() {
  proxy.$refs["roleRef"].validate(valid => {
    if (valid) {
      if (form.value.roleId != undefined) {
        form.value.menuIds = getMenuAllCheckedKeys()
        updateRole(form.value).then(response => {
          proxy.$modal.msgSuccess("修改成功")
          open.value = false
          getList()
        })
      } else {
        form.value.menuIds = getMenuAllCheckedKeys()
        addRole(form.value).then(response => {
          proxy.$modal.msgSuccess("新增成功")
          open.value = false
          getList()
        })
      }
    }
  })
}

/** 取消按钮 */
function cancel() {
  open.value = false
  reset()
}

/** 选择角色权限范围触发 */
function dataScopeSelectChange(value) {
  if (value !== "2") {
    deptRef.value.setCheckedKeys([])
  }
}

/** 分配数据权限操作 */
function handleDataScope(row) {
  reset()
  const deptTreeSelect = getDeptTree(row.roleId)
  getRole(row.roleId).then(response => {
    form.value = response.data
    openDataScope.value = true
    nextTick(() => {
      deptTreeSelect.then(res => {
        nextTick(() => {
          if (deptRef.value) {
            deptRef.value.setCheckedKeys(res.checkedKeys)
          }
        })
      })
    })
  })
  title.value = "分配数据权限"
}

/** 提交按钮（数据权限） */
function submitDataScope() {
  if (form.value.roleId != undefined) {
    form.value.deptIds = getDeptAllCheckedKeys()
    dataScope(form.value).then(response => {
      proxy.$modal.msgSuccess("修改成功")
      openDataScope.value = false
      getList()
    })
  }
}

/** 取消按钮（数据权限）*/
function cancelDataScope() {
  openDataScope.value = false
  reset()
}

getList()
</script>

<style scoped lang="scss">
.search-form {
  margin-bottom: 16px;
  
  .el-form-item {
    margin-bottom: 16px;
  }
}

.action-buttons {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  white-space: nowrap;
  
  .el-button {
    padding: 0 8px;
  }
}

.role-table {
  :deep(.el-table__row) {
    cursor: pointer;
    
    &:hover {
      background-color: var(--el-table-row-hover-bg-color);
    }
  }
}

.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
}

:deep(.el-table) {
  .el-table__header {
    th {
      background-color: var(--el-table-header-bg-color);
      font-weight: 500;
    }
  }
}

:deep(.el-dialog__body) {
  padding: 24px 28px;
}

:deep(.el-dialog__header) {
  padding: 20px 28px 16px;
  border-bottom: 1px solid var(--el-border-color-lighter);
}

:deep(.el-dialog__footer) {
  padding: 16px 28px 20px;
  border-top: 1px solid var(--el-border-color-lighter);
}
</style>
