// ruoyi-front/src/views/login.vue
<template>
  <div class="login">
    <div class="login-overlay"></div>
    <el-form ref="loginRef" :model="loginForm" :rules="loginRules" class="login-form">
      <h3 class="title">{{ title }}</h3>
      <el-form-item prop="username">
        <el-input
          v-model="loginForm.username"
          type="text"
          size="large"
          auto-complete="off"
          placeholder="账号"
        >
          <template #prefix><el-icon class="el-input__icon input-icon"><User /></el-icon></template>
        </el-input>
      </el-form-item>
      <el-form-item prop="password">
        <el-input
          v-model="loginForm.password"
          type="password"
          size="large"
          auto-complete="off"
          placeholder="密码"
          @keyup.enter="handleLogin"
        >
          <template #prefix><el-icon class="el-input__icon input-icon"><Lock /></el-icon></template>
        </el-input>
      </el-form-item>
      <el-form-item prop="code" v-if="captchaEnabled">
        <el-input
          v-model="loginForm.code"
          size="large"
          auto-complete="off"
          placeholder="验证码"
          style="width: 63%"
          @keyup.enter="handleLogin"
        >
          <template #prefix><el-icon class="el-input__icon input-icon"><Key /></el-icon></template>
        </el-input>
        <div class="login-code">
          <img :src="codeUrl" @click="getCode" class="login-code-img"/>
        </div>
      </el-form-item>
      <el-checkbox v-model="loginForm.rememberMe" class="remember-me">记住密码</el-checkbox>
      <el-form-item style="width:100%;">
        <el-button
          :loading="loading"
          size="large"
          type="primary"
          style="width:100%;"
          @click.prevent="handleLogin"
        >
          <span v-if="!loading">登 录</span>
          <span v-else>登 录 中...</span>
        </el-button>
        <div style="float: right;" v-if="register">
          <router-link class="link-type" :to="'/register'">立即注册</router-link>
        </div>
      </el-form-item>
    </el-form>
    <!--  底部  -->
    <div class="el-login-footer">
      <span>{{ footerContent }}</span>
    </div>
  </div>
</template>

<script setup>
import { getCodeImg } from "@/api/login"
import Cookies from "js-cookie"
import { encrypt, decrypt } from "@/utils/jsencrypt"
import useUserStore from '@/store/modules/user'
import defaultSettings from '@/settings'
import { User, Lock, Key } from '@element-plus/icons-vue'

const title = import.meta.env.VITE_APP_TITLE
const footerContent = defaultSettings.footerContent
const userStore = useUserStore()
const route = useRoute()
const router = useRouter()
const { proxy } = getCurrentInstance()

const loginForm = ref({
  username: "admin",
  password: "admin123",
  rememberMe: false,
  code: "",
  uuid: ""
})

const loginRules = {
  username: [{ required: true, trigger: "blur", message: "请输入您的账号" }],
  password: [{ required: true, trigger: "blur", message: "请输入您的密码" }],
  code: [{ required: true, trigger: "change", message: "请输入验证码" }]
}

const codeUrl = ref("")
const loading = ref(false)
// 验证码开关
const captchaEnabled = ref(true)
// 注册开关
const register = ref(false)
const redirect = ref(undefined)

watch(route, (newRoute) => {
    redirect.value = newRoute.query && newRoute.query.redirect
}, { immediate: true })

function handleLogin() {
  proxy.$refs.loginRef.validate(valid => {
    if (valid) {
      loading.value = true
      // 勾选了需要记住密码设置在 cookie 中设置记住用户名和密码
      if (loginForm.value.rememberMe) {
        Cookies.set("username", loginForm.value.username, { expires: 30 })
        Cookies.set("password", encrypt(loginForm.value.password), { expires: 30 })
        Cookies.set("rememberMe", loginForm.value.rememberMe, { expires: 30 })
      } else {
        // 否则移除
        Cookies.remove("username")
        Cookies.remove("password")
        Cookies.remove("rememberMe")
      }
      // 调用action的登录方法
      userStore.login(loginForm.value).then(() => {
        const query = route.query
        const otherQueryParams = Object.keys(query).reduce((acc, cur) => {
          if (cur !== "redirect") {
            acc[cur] = query[cur]
          }
          return acc
        }, {})
        router.push({ path: redirect.value || "/", query: otherQueryParams })
      }).catch(() => {
        loading.value = false
        // 重新获取验证码
        if (captchaEnabled.value) {
          getCode()
        }
      })
    }
  })
}

function getCode() {
  getCodeImg().then(res => {
    captchaEnabled.value = res.captchaEnabled === undefined ? true : res.captchaEnabled
    if (captchaEnabled.value) {
      codeUrl.value = "data:image/gif;base64," + res.img
      loginForm.value.uuid = res.uuid
    }
  })
}

function getCookie() {
  const username = Cookies.get("username")
  const password = Cookies.get("password")
  const rememberMe = Cookies.get("rememberMe")
  loginForm.value = {
    username: username === undefined ? loginForm.value.username : username,
    password: password === undefined ? loginForm.value.password : decrypt(password),
    rememberMe: rememberMe === undefined ? false : Boolean(rememberMe)
  }
}

getCode()
getCookie()
</script>

<style lang='scss' scoped>
.login {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  width: 100%;
  position: relative;
  overflow: hidden;
  
  &::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    width: 100%;
    height: 100%;
    background-image: url("../assets/images/login-background.jpg");
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    filter: blur(3px);
    transform: scale(1.1);
    z-index: 0;
  }
}

.login-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.3);
  z-index: 1;
}

.title {
  margin: 0px auto 30px auto;
  text-align: center;
  color: #2c3e50;
  font-weight: 600;
  font-size: 24px;
}

.login-form {
  border-radius: 12px;
  background: rgba(255, 255, 255, 0.95);
  backdrop-filter: blur(10px);
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
  width: 400px;
  padding: 35px 35px 25px 35px;
  z-index: 2;
  position: relative;
  border: 1px solid rgba(255, 255, 255, 0.3);
  
  :deep(.el-input__wrapper) {
    background-color: rgba(255, 255, 255, 0.9);
    box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.1) inset;
    transition: all 0.3s ease;
    
    &:hover {
      box-shadow: 0 0 0 1px rgba(64, 158, 255, 0.3) inset;
    }
    
    &.is-focus {
      box-shadow: 0 0 0 1px rgba(64, 158, 255, 0.5) inset;
    }
  }
  
  :deep(.el-input__inner) {
    color: #2c3e50;
    
    &::placeholder {
      color: #a0a0a0;
    }
  }
  
  .el-input {
    height: 40px;
    input {
      height: 40px;
    }
  }
  .input-icon {
    height: 39px;
    width: 14px;
    margin-left: 0px;
    color: #606266;
  }
  
  :deep(.el-checkbox__label) {
    color: #606266;
  }
  
  :deep(.el-button--primary) {
    background: linear-gradient(135deg, #3d6db5 0%, #5ba3f0 100%);
    border: none;
    box-shadow: 0 4px 15px rgba(61, 109, 181, 0.5);
    transition: all 0.3s ease;
    
    &:hover {
      background: linear-gradient(135deg, #2c5aa0 0%, #4a90e2 100%);
      box-shadow: 0 6px 20px rgba(61, 109, 181, 0.7);
      transform: translateY(-2px);
    }
    
    &:active {
      transform: translateY(0);
      box-shadow: 0 2px 10px rgba(61, 109, 181, 0.5);
    }
  }
}
.login-tip {
  font-size: 13px;
  text-align: center;
  color: #bfbfbf;
}
.login-code {
  width: 33%;
  height: 40px;
  float: right;
  img {
    cursor: pointer;
    vertical-align: middle;
  }
}
.el-login-footer {
  height: 40px;
  line-height: 40px;
  position: fixed;
  bottom: 0;
  width: 100%;
  text-align: center;
  color: #fff;
  font-family: Arial;
  font-size: 12px;
  letter-spacing: 1px;
  z-index: 2;
}
.login-code-img {
  height: 40px;
  padding-left: 12px;
  border-radius: 4px;
}

.remember-me {
  margin: 0px 0px 25px 0px;
}
</style>

// ruoyi-front-react/src/views/login/index.jsx
import { useState, useEffect } from 'react'
import { Form, Input, Button, Checkbox, message } from 'antd'
import { UserOutlined, LockOutlined, KeyOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { useUserStore } from '@/store/userStore'
import { getCodeImg } from '@/api/login'
import { encrypt } from '@/utils/jsencrypt'
import defaultSettings from '@/settings'
import './index.scss'

const Login = () => {
  const navigate = useNavigate()
  const userStore = useUserStore()
  const [form] = Form.useForm()
  const [loading, setLoading] = useState(false)
  const [codeUrl, setCodeUrl] = useState('')
  const [captchaEnabled, setCaptchaEnabled] = useState(true)
  const [uuid, setUuid] = useState('')

  const title = import.meta.env.VITE_APP_TITLE
  const footerContent = defaultSettings.footerContent

  // 登录页禁止滚动（仅本页生效，离开后恢复）
  useEffect(() => {
    const prevBodyOverflow = document.body.style.overflow
    const prevHtmlOverflow = document.documentElement.style.overflow
    document.body.style.overflow = 'hidden'
    document.documentElement.style.overflow = 'hidden'
    return () => {
      document.body.style.overflow = prevBodyOverflow
      document.documentElement.style.overflow = prevHtmlOverflow
    }
  }, [])

  const getCode = async () => {
    try {
      const res = await getCodeImg()
      // 处理响应数据，可能是 res 或 res.data
      const data = res.data || res
      if (data && data.img) {
        // 判断图片格式：/9j/ 开头是 JPEG，iVBORw0KGgo 开头是 PNG，R0lGODlh 开头是 GIF
        let imgBase64 = data.img
        if (!imgBase64.startsWith('data:')) {
          if (imgBase64.startsWith('/9j/')) {
            imgBase64 = 'data:image/jpeg;base64,' + imgBase64
          } else if (imgBase64.startsWith('iVBORw0KGgo')) {
            imgBase64 = 'data:image/png;base64,' + imgBase64
          } else if (imgBase64.startsWith('R0lGODlh')) {
            imgBase64 = 'data:image/gif;base64,' + imgBase64
          } else {
            // 默认使用 JPEG
            imgBase64 = 'data:image/jpeg;base64,' + imgBase64
          }
        }
        setCodeUrl(imgBase64)
        setUuid(data.uuid || '')
        setCaptchaEnabled(data.captchaEnabled === undefined ? true : data.captchaEnabled)
      } else {
        console.error('验证码响应数据格式错误:', data)
        message.error('获取验证码失败，请刷新页面重试')
      }
    } catch (err) {
      console.error('获取验证码失败', err)
      const errorMsg = err.response?.data?.msg || err.message || '未知错误'
      message.error('获取验证码失败: ' + errorMsg)
    }
  }

  const handleLogin = async (values) => {
    setLoading(true)
    try {
      let password = values.password
      if (import.meta.env.VITE_APP_ENCRYPT === 'true') {
        password = encrypt(password)
      }
      
      await userStore.login({
        username: values.username,
        password: password,
        code: values.code,
        uuid: uuid
      })

      await userStore.getInfo()
      
      const redirect = new URLSearchParams(window.location.search).get('redirect')
      navigate(redirect || '/', { replace: true })
      message.success('登录成功')
    } catch (error) {
      console.error('登录失败', error)
      if (captchaEnabled) {
        getCode()
      }
    } finally {
      setLoading(false)
    }
  }

  // 初始化获取验证码
  useEffect(() => {
    getCode()
  }, [])

  return (
    <div className="login">
      <div className="login-overlay"></div>
      <Form
        form={form}
        className="login-form"
        onFinish={handleLogin}
        initialValues={{
          username: 'admin',
          password: 'admin123',
          rememberMe: false
        }}
      >
        <h3 className="title">{title}</h3>
        <Form.Item
          name="username"
          rules={[{ required: true, message: '请输入您的账号' }]}
        >
          <Input
            size="large"
            placeholder="账号"
            prefix={<UserOutlined className="input-icon" />}
          />
        </Form.Item>
        <Form.Item
          name="password"
          rules={[{ required: true, message: '请输入您的密码' }]}
        >
          <Input.Password
            size="large"
            placeholder="密码"
            prefix={<LockOutlined className="input-icon" />}
            onPressEnter={() => form.submit()}
          />
        </Form.Item>
        {captchaEnabled && (
          <Form.Item
            name="code"
            rules={[{ required: true, message: '请输入验证码' }]}
          >
            <div style={{ display: 'flex', gap: '10px' }}>
              <Input
                size="large"
                placeholder="验证码"
                prefix={<KeyOutlined className="input-icon" />}
                style={{ flex: 1 }}
                onPressEnter={() => form.submit()}
              />
              <div className="login-code" onClick={getCode}>
                {codeUrl ? (
                  <img 
                    src={codeUrl} 
                    className="login-code-img"
                    alt="验证码"
                    style={{ cursor: 'pointer' }}
                  />
                ) : (
                  <div 
                    className="login-code-img" 
                    style={{ 
                      display: 'flex', 
                      alignItems: 'center', 
                      justifyContent: 'center',
                      background: '#f5f5f5',
                      cursor: 'pointer',
                      fontSize: '12px',
                      color: '#999'
                    }}
                  >
                    点击获取验证码
                  </div>
                )}
              </div>
            </div>
          </Form.Item>
        )}
        <Form.Item name="rememberMe" valuePropName="checked">
          <Checkbox>记住密码</Checkbox>
        </Form.Item>
        <Form.Item>
          <Button
            type="primary"
            size="large"
            htmlType="submit"
            loading={loading}
            block
          >
            {loading ? '登 录 中...' : '登 录'}
          </Button>
          <div style={{ float: 'right', marginTop: '10px' }}>
            <a href="/register">立即注册</a>
          </div>
        </Form.Item>
      </Form>
      <div className="el-login-footer">
        <span>{footerContent}</span>
      </div>
    </div>
  )
}

export default Login
