// ruoyi-react-web/src/layout/components/TagsView/index.jsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { CloseOutlined, ReloadOutlined, CloseCircleOutlined, LeftOutlined, RightOutlined } from '@ant-design/icons'
import { useTagsViewStore } from '@/store/tagsViewStore'
import { useSettingsStore } from '@/store/settingsStore'
import { usePermissionStore } from '@/store/permissionStore'
import { getNormalPath } from '@/utils/ruoyi'
import { getIconComponent } from '@/utils/icon'
import { useTab } from '@/plugins/tab'
import ScrollPane from './ScrollPane'
import './index.scss'

const TagsView = () => {
  const location = useLocation()
  const navigate = useNavigate()
  const visitedViews = useTagsViewStore((state) => state.visitedViews)
  const routes = usePermissionStore((state) => state.routes)
  const theme = useSettingsStore((state) => state.theme)
  const tagsIcon = useSettingsStore((state) => state.tagsIcon)
  const { refreshPage, closePage, closeOthersPage, closeLeftPage, closeRightPage, closeAllPage } = useTab()
  
  const [visible, setVisible] = useState(false)
  const [top, setTop] = useState(0)
  const [left, setLeft] = useState(0)
  const [selectedTag, setSelectedTag] = useState({})
  const [affixTags, setAffixTags] = useState([])
  const scrollPaneRef = useRef(null)
  const containerRef = useRef(null)
  const initedRef = useRef(false)

  const isActive = (r) => {
    return r.path === location.pathname
  }

  const activeStyle = (tag) => {
    if (!isActive(tag)) return {}
    return {
      backgroundColor: theme,
      borderColor: theme
    }
  }

  const isAffix = (tag) => {
    return tag.meta && tag.meta.affix
  }

  const filterAffixTags = (routes, basePath = '') => {
    let tags = []
    routes.forEach(route => {
      const routeMeta = route.handle?.meta || route.meta
      const routePath = route.index ? '' : (route.path || '')
      if (routeMeta && routeMeta.affix) {
        const tagPath = getNormalPath(`${basePath}/${routePath}`) || '/'
        tags.push({
          fullPath: tagPath,
          path: tagPath,
          name: route.name || route.routeName || tagPath,
          meta: { ...routeMeta }
        })
      }
      if (route.children) {
        const nextBasePath = getNormalPath(`${basePath}/${routePath}`) || '/'
        const tempTags = filterAffixTags(route.children, nextBasePath)
        if (tempTags.length >= 1) {
          tags = [...tags, ...tempTags]
        }
      }
    })
    return tags
  }

  const initTags = () => {
    const res = filterAffixTags(routes)
    setAffixTags(res)
    res.forEach(tag => {
      if (tag.name) {
        useTagsViewStore.getState().addVisitedView(tag)
      }
    })
  }

  const findRouteByPath = useCallback((routeList, pathname, basePath = '') => {
    for (const route of routeList || []) {
      const routePath = route.index ? '' : (route.path || '')
      const fullPath = getNormalPath(`${basePath}/${routePath}`) || '/'
      if (fullPath === pathname) return route
      if (route.children?.length) {
        const found = findRouteByPath(route.children, pathname, fullPath)
        if (found) return found
      }
    }
    return null
  }, [])

  const addTags = useCallback(() => {
    // 不在 tags-view 中展示这些页面
    const ignore = ['/login', '/register', '/401']
    if (ignore.includes(location.pathname) || location.pathname.startsWith('/redirect')) return

    const route = findRouteByPath(routes, location.pathname)
    const meta = route?.handle?.meta || route?.meta || {}
    if (meta.hidden) return

    const fullPath = `${location.pathname}${location.search || ''}`
    const view = {
      path: location.pathname,
      fullPath,
      name: route?.name || route?.routeName || location.pathname,
      meta,
      title: meta.title
    }

    const store = useTagsViewStore.getState()
    // 已存在则更新（例如 query 变化）
    if (store.visitedViews.some(v => v.path === view.path)) {
      store.updateVisitedView(view)
      return
    }
    store.addView(view)
  }, [findRouteByPath, location.pathname, location.search, routes])

  const moveToCurrentTag = useCallback(() => {
    if (!scrollPaneRef.current) return
    const store = useTagsViewStore.getState()
    const current = store.visitedViews.find(v => v.path === location.pathname)
    if (!current) return

    // DOM 更新后滚动到当前标签
    setTimeout(() => {
      scrollPaneRef.current?.moveToTarget(current, store.visitedViews)
    }, 0)
  }, [location.pathname])

  useEffect(() => {
    if (!initedRef.current && routes?.length) {
      initTags()
      initedRef.current = true
    }
  }, [routes?.length])

  useEffect(() => {
    addTags()
    moveToCurrentTag()
  }, [location.pathname, location.search, addTags, moveToCurrentTag])

  useEffect(() => {
    if (visible) {
      document.body.addEventListener('click', closeMenu)
    } else {
      document.body.removeEventListener('click', closeMenu)
    }
    return () => {
      document.body.removeEventListener('click', closeMenu)
    }
  }, [visible])

  const openMenu = (tag, e) => {
    if (!containerRef.current) return

    const menuWidth = 140
    // 让菜单更贴近 tab（更左一点）
    const gap = 4

    const containerRect = containerRef.current.getBoundingClientRect()
    const tagRect = e.currentTarget?.getBoundingClientRect?.()

    const baseRight = tagRect?.right ?? e.clientX
    const baseTop = tagRect?.top ?? e.clientY
    const baseBottom = tagRect?.bottom ?? e.clientY

    // 默认显示在 tab 右侧
    let x = baseRight + gap
    // 右侧放不下则贴着 tab 的右侧向左展开
    if (x + menuWidth > containerRect.right) {
      x = baseRight - menuWidth
    }
    // 仍然超出则贴容器左边界
    if (x < containerRect.left) {
      x = containerRect.left + gap
    }

    // 默认与 tab 顶部对齐（再上一点）
    const estimatedMenuHeight = 220
    let y = baseTop - 2
    if (y + estimatedMenuHeight > window.innerHeight) {
      y = baseTop - estimatedMenuHeight - 2
    }
    if (y < 8) y = 8

    setLeft(Math.round(x))
    setTop(Math.round(y))
    setVisible(true)
    setSelectedTag(tag)
  }

  const closeMenu = () => {
    setVisible(false)
  }

  const handleScroll = () => {
    closeMenu()
  }

  const refreshSelectedTag = (view) => {
    refreshPage(view)
  }

  const closeSelectedTag = (view) => {
    closePage(view).then(({ visitedViews }) => {
      if (isActive(view)) {
        toLastView(visitedViews, view)
      }
    })
  }

  const closeRightTags = () => {
    closeRightPage(selectedTag).then(visitedViews => {
      if (!visitedViews.find(i => i.path === location.pathname)) {
        toLastView(visitedViews)
      }
    })
  }

  const closeLeftTags = () => {
    closeLeftPage(selectedTag).then(visitedViews => {
      if (!visitedViews.find(i => i.path === location.pathname)) {
        toLastView(visitedViews)
      }
    })
  }

  const closeOthersTags = () => {
    navigate(selectedTag.path)
    closeOthersPage(selectedTag).then(() => {
      moveToCurrentTag()
    })
  }

  const closeAllTags = (view) => {
    closeAllPage().then(({ visitedViews }) => {
      if (affixTags.some(tag => tag.path === location.pathname)) {
        return
      }
      toLastView(visitedViews, view)
    })
  }

  const toLastView = (visitedViews, view) => {
    const latestView = visitedViews.slice(-1)[0]
    if (latestView) {
      navigate(latestView.path)
    } else {
      if (view?.name === 'Dashboard') {
        navigate(`/redirect${view.fullPath}`, { replace: true })
      } else {
        navigate('/')
      }
    }
  }

  const hasNonAffixLeft = () => {
    const idx = visitedViews.findIndex(v => v.path === selectedTag.path)
    if (idx <= 0) return false
    return visitedViews.slice(0, idx).some(v => !v.meta?.affix)
  }

  const hasNonAffixRight = () => {
    const idx = visitedViews.findIndex(v => v.path === selectedTag.path)
    if (idx === -1 || idx >= visitedViews.length - 1) return false
    return visitedViews.slice(idx + 1).some(v => !v.meta?.affix)
  }

  return (
    <div id="tags-view-container" className="tags-view-container" ref={containerRef}>
      <ScrollPane ref={scrollPaneRef} onScroll={handleScroll} className="tags-view-wrapper">
        {visitedViews.map(tag => {
          const IconComponent = tagsIcon && tag.meta?.icon && tag.meta.icon !== '#' 
            ? getIconComponent(tag.meta.icon) 
            : null
          
          return (
            <Link
              key={tag.path}
              data-path={tag.path}
              to={tag.path}
              className={`tags-view-item ${isActive(tag) ? 'active' : ''} ${tagsIcon ? 'has-icon' : ''}`}
              style={activeStyle(tag)}
              onContextMenu={(e) => {
                e.preventDefault()
                openMenu(tag, e)
              }}
              onMouseDown={(e) => {
                if (e.button === 1 && !isAffix(tag)) {
                  e.preventDefault()
                  closeSelectedTag(tag)
                }
              }}
            >
              {IconComponent && <IconComponent />}
              <span className="tag-title">{tag.title || tag.meta?.title}</span>
              {!isAffix(tag) && (
                <span
                  onClick={(e) => {
                    e.preventDefault()
                    e.stopPropagation()
                    closeSelectedTag(tag)
                  }}
                >
                  <CloseOutlined className="el-icon-close" />
                </span>
              )}
            </Link>
          )
        })}
      </ScrollPane>
      {visible && (
        <ul className="contextmenu" style={{ left: `${left}px`, top: `${top}px` }}>
          <li onClick={() => refreshSelectedTag(selectedTag)}>
            <ReloadOutlined /> 刷新页面
          </li>
          {!isAffix(selectedTag) && (
            <li onClick={() => closeSelectedTag(selectedTag)}>
              <CloseOutlined /> 关闭当前
            </li>
          )}
          <li onClick={closeOthersTags}>
            <CloseCircleOutlined /> 关闭其他
          </li>
          {hasNonAffixLeft() && (
            <li onClick={closeLeftTags}>
              <LeftOutlined /> 关闭左侧
            </li>
          )}
          {hasNonAffixRight() && (
            <li onClick={closeRightTags}>
              <RightOutlined /> 关闭右侧
            </li>
          )}
          <li onClick={() => closeAllTags(selectedTag)}>
            <CloseCircleOutlined /> 全部关闭
          </li>
        </ul>
      )}
    </div>
  )
}

export default TagsView

// ruoyi-front/src/layout/components/TagsView/index.vue
<template>
  <div id="tags-view-container" class="tags-view-container">
    <scroll-pane ref="scrollPaneRef" class="tags-view-wrapper" @scroll="handleScroll">
      <router-link
        v-for="tag in visitedViews"
        :key="tag.path"
        :data-path="tag.path"
        :class="{ 'active': isActive(tag), 'has-icon': tagsIcon }"
        :to="{ path: tag.path, query: tag.query, fullPath: tag.fullPath }"
        class="tags-view-item"
        :style="activeStyle(tag)"
        @click.middle="!isAffix(tag) ? closeSelectedTag(tag) : ''"
        @contextmenu.prevent="openMenu(tag, $event)"
      >
        <el-icon v-if="tagsIcon && tag.meta && tag.meta.icon && tag.meta.icon !== '#'">
          <component :is="getIconComponent(tag.meta.icon)" />
        </el-icon>
        {{ tag.title }}
        <span v-if="!isAffix(tag)" @click.prevent.stop="closeSelectedTag(tag)">
          <close class="el-icon-close" style="width: 1em; height: 1em;vertical-align: middle;" />
        </span>
      </router-link>
    </scroll-pane>
    <ul v-show="visible" :style="{ left: left + 'px', top: top + 'px' }" class="contextmenu">
      <li @click="refreshSelectedTag(selectedTag)">
        <refresh-right style="width: 1em; height: 1em;" /> 刷新页面
      </li>
      <li v-if="!isAffix(selectedTag)" @click="closeSelectedTag(selectedTag)">
        <close style="width: 1em; height: 1em;" /> 关闭当前
      </li>
      <li @click="closeOthersTags">
        <circle-close style="width: 1em; height: 1em;" /> 关闭其他
      </li>
      <li v-if="!isFirstView()" @click="closeLeftTags">
        <back style="width: 1em; height: 1em;" /> 关闭左侧
      </li>
      <li v-if="!isLastView()" @click="closeRightTags">
        <right style="width: 1em; height: 1em;" /> 关闭右侧
      </li>
      <li @click="closeAllTags(selectedTag)">
        <circle-close style="width: 1em; height: 1em;" /> 全部关闭
      </li>
    </ul>
  </div>
</template>

<script setup>
import ScrollPane from './ScrollPane'
import { getNormalPath } from '@/utils/ruoyi'
import useTagsViewStore from '@/store/modules/tagsView'
import useSettingsStore from '@/store/modules/settings'
import usePermissionStore from '@/store/modules/permission'
import { getIconComponent } from '@/utils/icon'

const visible = ref(false)
const top = ref(0)
const left = ref(0)
const selectedTag = ref({})
const affixTags = ref([])
const scrollPaneRef = ref(null)

const { proxy } = getCurrentInstance()
const route = useRoute()
const router = useRouter()

const visitedViews = computed(() => useTagsViewStore().visitedViews)
const routes = computed(() => usePermissionStore().routes)
const theme = computed(() => useSettingsStore().theme)
const tagsIcon = computed(() => useSettingsStore().tagsIcon)

watch(route, () => {
  addTags()
  moveToCurrentTag()
})

watch(visible, (value) => {
  if (value) {
    document.body.addEventListener('click', closeMenu)
  } else {
    document.body.removeEventListener('click', closeMenu)
  }
})

onMounted(() => {
  initTags()
  addTags()
})

function isActive(r) {
  return r.path === route.path
}

function activeStyle(tag) {
  if (!isActive(tag)) return {}
  return {
    "background-color": theme.value,
    "border-color": theme.value
  }
}

function isAffix(tag) {
  return tag.meta && tag.meta.affix
}

function isFirstView() {
  try {
    return selectedTag.value.fullPath === '/index' || selectedTag.value.fullPath === visitedViews.value[1].fullPath
  } catch (err) {
    return false
  }
}

function isLastView() {
  try {
    return selectedTag.value.fullPath === visitedViews.value[visitedViews.value.length - 1].fullPath
  } catch (err) {
    return false
  }
}

function filterAffixTags(routes, basePath = '') {
  let tags = []
  routes.forEach(route => {
    if (route.meta && route.meta.affix) {
      const tagPath = getNormalPath(basePath + '/' + route.path)
      tags.push({
        fullPath: tagPath,
        path: tagPath,
        name: route.name,
        meta: { ...route.meta }
      })
    }
    if (route.children) {
      const tempTags = filterAffixTags(route.children, route.path)
      if (tempTags.length >= 1) {
        tags = [...tags, ...tempTags]
      }
    }
  })
  return tags
}

function initTags() {
  const res = filterAffixTags(routes.value)
  affixTags.value = res
  for (const tag of res) {
    // Must have tag name
    if (tag.name) {
       useTagsViewStore().addVisitedView(tag)
    }
  }
}

function addTags() {
  const { name } = route
  if (name) {
    useTagsViewStore().addView(route)
  }
}

function moveToCurrentTag() {
  nextTick(() => {
    for (const r of visitedViews.value) {
      if (r.path === route.path) {
        scrollPaneRef.value.moveToTarget(r)
        // when query is different then update
        if (r.fullPath !== route.fullPath) {
          useTagsViewStore().updateVisitedView(route)
        }
      }
    }
  })
}

function refreshSelectedTag(view) {
  proxy.$tab.refreshPage(view)
  if (route.meta.link) {
    useTagsViewStore().delIframeView(route)
  }
}

function closeSelectedTag(view) {
  proxy.$tab.closePage(view).then(({ visitedViews }) => {
    if (isActive(view)) {
      toLastView(visitedViews, view)
    }
  })
}

function closeRightTags() {
  proxy.$tab.closeRightPage(selectedTag.value).then(visitedViews => {
    if (!visitedViews.find(i => i.fullPath === route.fullPath)) {
      toLastView(visitedViews)
    }
  })
}

function closeLeftTags() {
  proxy.$tab.closeLeftPage(selectedTag.value).then(visitedViews => {
    if (!visitedViews.find(i => i.fullPath === route.fullPath)) {
      toLastView(visitedViews)
    }
  })
}

function closeOthersTags() {
  router.push(selectedTag.value).catch(() => { })
  proxy.$tab.closeOtherPage(selectedTag.value).then(() => {
    moveToCurrentTag()
  })
}

function closeAllTags(view) {
  proxy.$tab.closeAllPage().then(({ visitedViews }) => {
    if (affixTags.value.some(tag => tag.path === route.path)) {
      return
    }
    toLastView(visitedViews, view)
  })
}

function toLastView(visitedViews, view) {
  const latestView = visitedViews.slice(-1)[0]
  if (latestView) {
    router.push(latestView.fullPath)
  } else {
    // now the default is to redirect to the home page if there is no tags-view,
    // you can adjust it according to your needs.
    if (view.name === 'Dashboard') {
      // to reload home page
      router.replace({ path: '/redirect' + view.fullPath })
    } else {
      router.push('/')
    }
  }
}

function openMenu(tag, e) {
  const menuMinWidth = 105
  const offsetLeft = proxy.$el.getBoundingClientRect().left // container margin left
  const offsetWidth = proxy.$el.offsetWidth // container width
  const maxLeft = offsetWidth - menuMinWidth // left boundary
  const l = e.clientX - offsetLeft + 15 // 15: margin right

  if (l > maxLeft) {
    left.value = maxLeft
  } else {
    left.value = l
  }

  top.value = e.clientY
  visible.value = true
  selectedTag.value = tag
}

function closeMenu() {
  visible.value = false
}

function handleScroll() {
  closeMenu()
}
</script>

<style lang="scss" scoped>
.tags-view-container {
  height: 34px;
  width: 100%;
  background: var(--tags-bg, #fff);
  border-bottom: 1px solid var(--tags-item-border, #d8dce5);
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .12), 0 0 3px 0 rgba(0, 0, 0, .04);

  .tags-view-wrapper {
    .tags-view-item {
      display: inline-block;
      position: relative;
      cursor: pointer;
      height: 26px;
      line-height: 26px;
      border: 1px solid var(--tags-item-border, #d8dce5);
      color: var(--tags-item-text, #495060);
      background: var(--tags-item-bg, #fff);
      padding: 0 8px;
      font-size: 12px;
      margin-left: 5px;
      margin-top: 4px;

      &:first-of-type {
        margin-left: 15px;
      }

      &:last-of-type {
        margin-right: 15px;
      }

      &.active {
        background-color: #42b983;
        color: #fff;
        border-color: #42b983;

        &::before {
          content: '';
          background: #fff;
          display: inline-block;
          width: 8px;
          height: 8px;
          border-radius: 50%;
          position: relative;
          margin-right: 5px;
        }
      }
    }
  }

  .tags-view-item.active.has-icon::before {
    content: none !important;
  }

  .contextmenu {
    margin: 0;
    background: var(--el-bg-color-overlay, #fff);
    z-index: 3000;
    position: absolute;
    list-style-type: none;
    padding: 5px 0;
    border-radius: 4px;
    font-size: 12px;
    font-weight: 400;
    color: var(--tags-item-text, #333);
    box-shadow: 2px 2px 3px 0 rgba(0, 0, 0, .3);
    border: 1px solid var(--el-border-color-light, #e4e7ed);

    li {
      margin: 0;
      padding: 7px 16px;
      cursor: pointer;

      &:hover {
        background: var(--tags-item-hover, #eee);
      }
    }
  }
}
</style>

<style lang="scss">
//reset element css of el-icon-close
.tags-view-wrapper {
  .tags-view-item {
    .el-icon-close {
      width: 16px;
      height: 16px;
      vertical-align: 2px;
      border-radius: 50%;
      text-align: center;
      transition: all .3s cubic-bezier(.645, .045, .355, 1);
      transform-origin: 100% 50%;

      &:before {
        transform: scale(.6);
        display: inline-block;
        vertical-align: -3px;
      }

      &:hover {
        background-color: var(--tags-close-hover, #b4bccc);
        color: #fff;
        width: 12px !important;
        height: 12px !important;
      }
    }
  }
}
</style>
