// ruoyi-front-vue/src/layout/components/Navbar.vue
<template>
  <div class="navbar">
    <hamburger id="hamburger-container" :is-active="appStore.sidebar.opened" class="hamburger-container" @toggleClick="toggleSideBar" />
    <breadcrumb v-if="!settingsStore.topNav" id="breadcrumb-container" class="breadcrumb-container" />
    <top-nav v-if="settingsStore.topNav" id="topmenu-container" class="topmenu-container" />

    <div class="right-menu">
      <template v-if="appStore.device !== 'mobile'">
        <!-- 搜索功能 -->
        <header-search id="header-search" class="right-menu-item hover-effect" />

        <!-- 主题切换 -->
        <el-tooltip content="主题模式" effect="dark" placement="bottom">
          <div class="right-menu-item hover-effect theme-switch-wrapper" @click="toggleTheme">
            <el-icon v-if="settingsStore.isDark" class="theme-icon"><Sunny /></el-icon>
            <el-icon v-if="!settingsStore.isDark" class="theme-icon"><Moon /></el-icon>
          </div>
        </el-tooltip>

        <!-- 全屏 -->
        <screenfull id="screenfull" class="right-menu-item hover-effect" />

        <!-- 布局大小 -->
        <el-tooltip content="布局大小" effect="dark" placement="bottom">
          <size-select id="size-select" class="right-menu-item hover-effect" />
        </el-tooltip>

        <!-- 文档地址 -->
        <el-tooltip content="文档地址" effect="dark" placement="bottom">
          <ruo-yi-doc id="ruoyi-doc" class="right-menu-item hover-effect" />
        </el-tooltip>

        <!-- 源码地址 -->
        <el-tooltip content="源码地址" effect="dark" placement="bottom">
          <ruo-yi-git id="ruoyi-git" class="right-menu-item hover-effect" />
        </el-tooltip>
      </template>

      <!-- 用户信息（始终显示，放在最右边） -->
      <el-dropdown @command="handleCommand" class="avatar-container right-menu-item hover-effect" trigger="hover">
        <div class="avatar-wrapper">
          <img :src="userStore.avatar" class="user-avatar" />
          <div class="user-info">
            <span class="user-nickname">{{ userStore.nickName }}</span>
            <span class="user-dept" v-if="userStore.deptName">{{ userStore.deptName }}</span>
          </div>
        </div>
        <template #dropdown>
          <el-dropdown-menu>
            <router-link to="/user/profile">
              <el-dropdown-item>个人中心</el-dropdown-item>
            </router-link>
            <el-dropdown-item command="setLayout" v-if="settingsStore.showSettings">
                <span>布局设置</span>
              </el-dropdown-item>
            <el-dropdown-item divided command="logout">
              <span>退出登录</span>
            </el-dropdown-item>
          </el-dropdown-menu>
        </template>
      </el-dropdown>
    </div>
  </div>
</template>

<script setup>
import { ElMessageBox } from 'element-plus'
import Breadcrumb from '@/components/Breadcrumb'
import TopNav from '@/components/TopNav'
import Hamburger from '@/components/Hamburger'
import Screenfull from '@/components/Screenfull'
import SizeSelect from '@/components/SizeSelect'
import HeaderSearch from '@/components/HeaderSearch'
import RuoYiGit from '@/components/RuoYi/Git'
import RuoYiDoc from '@/components/RuoYi/Doc'
import useAppStore from '@/store/modules/app'
import useUserStore from '@/store/modules/user'
import useSettingsStore from '@/store/modules/settings'
import { Sunny, Moon } from '@element-plus/icons-vue'

const appStore = useAppStore()
const userStore = useUserStore()
const settingsStore = useSettingsStore()

function toggleSideBar() {
  appStore.toggleSideBar()
}

function handleCommand(command) {
  switch (command) {
    case "setLayout":
      setLayout()
      break
    case "logout":
      logout()
      break
    default:
      break
  }
}

function logout() {
  ElMessageBox.confirm('确定注销并退出系统吗？', '提示', {
    confirmButtonText: '确定',
    cancelButtonText: '取消',
    type: 'warning'
  }).then(() => {
    userStore.logOut().then(() => {
      location.href = '/index'
    })
  }).catch(() => { })
}

const emits = defineEmits(['setLayout'])
function setLayout() {
  emits('setLayout')
}

function toggleTheme() {
  settingsStore.toggleTheme()
}
</script>

<style lang='scss' scoped>
.navbar {
  height: 50px;
  overflow: hidden;
  position: relative;
  background: var(--navbar-bg);
  box-shadow: 0 1px 4px rgba(0, 21, 41, 0.08);

  .hamburger-container {
    line-height: 46px;
    height: 100%;
    float: left;
    cursor: pointer;
    transition: background 0.3s;
    -webkit-tap-highlight-color: transparent;

    &:hover {
      background: rgba(0, 0, 0, 0.025);
    }
  }

  .breadcrumb-container {
    float: left;
  }

  .topmenu-container {
    position: absolute;
    left: 50px;
  }

  .errLog-container {
    display: inline-block;
    vertical-align: top;
  }

  .right-menu {
    float: right;
    height: 100%;
    line-height: 50px;
    display: flex;

    &:focus {
      outline: none;
    }

    .right-menu-item {
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 0 8px;
      height: 100%;
      font-size: 18px;
      color: #5a5e66;

      &.hover-effect {
        cursor: pointer;
        transition: background 0.3s;

        &:hover {
          background: rgba(0, 0, 0, 0.025);
        }
      }

      &.theme-switch-wrapper {
        display: flex;
        align-items: center;
        justify-content: center;

        .theme-icon {
          font-size: 18px;
          transition: transform 0.2s ease;
        }

        &:hover .theme-icon {
          transform: scale(1.1);
        }
      }
      
      // Element Plus 图标样式统一
      .el-icon {
        font-size: 18px;
        transition: transform 0.2s ease;
      }
      
      &:hover .el-icon {
        transform: scale(1.1);
      }
    }

    .avatar-container {
      margin-right: 8px;
      padding-right: 0px;

      .avatar-wrapper {
        display: flex;
        align-items: center;
        gap: 10px;
        padding: 0 4px;

        .user-avatar {
          cursor: pointer;
          width: 32px;
          height: 32px;
          border-radius: 50%;
          flex-shrink: 0;
          border: 2px solid var(--el-border-color-lighter);
          transition: all 0.3s;
          
          &:hover {
            border-color: var(--el-color-primary);
          }
        }

        .user-info {
          display: flex;
          flex-direction: column;
          align-items: flex-start;
          justify-content: center;
          line-height: 1.4;
          min-width: 0;
          
          .user-nickname {
            font-size: 14px;
            font-weight: 600;
            color: var(--el-text-color-primary);
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            max-width: 120px;
          }

          .user-dept {
            font-size: 12px;
            color: var(--el-text-color-secondary);
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            max-width: 120px;
            margin-top: 2px;
          }
        }

        i {
          cursor: pointer;
          position: absolute;
          right: -20px;
          top: 25px;
          font-size: 12px;
        }
      }
    }
  }
}
</style>

// ruoyi-react-web/src/layout/components/Navbar/index.jsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Dropdown, Tooltip, Modal } from 'antd'
import { SunOutlined, MoonOutlined, FullscreenOutlined, FullscreenExitOutlined } from '@ant-design/icons'
import { useAppStore } from '@/store/appStore'
import { useUserStore } from '@/store/userStore'
import { useSettingsStore } from '@/store/settingsStore'
import Hamburger from '@/components/Hamburger'
import { navbarMenuConfig } from '@/config/routeMeta'
import './index.scss'

const Navbar = ({ onSetLayout }) => {
  const navigate = useNavigate()
  const appStore = useAppStore()
  const userStore = useUserStore()
  const settingsStore = useSettingsStore()
  const [isFullscreen, setIsFullscreen] = useState(false)

  const toggleSideBar = () => {
    appStore.toggleSideBar()
  }

  const handleCommand = (command) => {
    switch (command) {
      case 'setLayout':
        onSetLayout?.()
        break
      case 'logout':
        logout()
        break
      default:
        break
    }
  }

  const logout = () => {
    Modal.confirm({
      title: '提示',
      content: '确定注销并退出系统吗？',
      okText: '确定',
      cancelText: '取消',
      onOk: () => {
        userStore.logOut().then(() => {
          window.location.href = '/login'
        })
      }
    })
  }

  const toggleTheme = () => {
    settingsStore.toggleTheme()
  }

  const toggleFullscreen = () => {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen()
      setIsFullscreen(true)
    } else {
      document.exitFullscreen()
      setIsFullscreen(false)
    }
  }

  const menuItems = navbarMenuConfig.reduce((result, item) => {
    if (item.type === 'divider') {
      result.push({ type: 'divider' })
      return result
    }
    if (item.requiresSettings && !settingsStore.showSettings) {
      return result
    }
    const label = item.path ? (
      <a href={item.path} onClick={(e) => { e.preventDefault(); navigate(item.path) }}>
        {item.label}
      </a>
    ) : (
      <span>{item.label}</span>
    )
    result.push({ key: item.key, label })
    return result
  }, [])

  return (
    <div className="navbar">
      <Hamburger
        id="hamburger-container"
        isActive={appStore.sidebar.opened}
        onClick={toggleSideBar}
        className="hamburger-container"
      />
      
      <div className="right-menu">
        {appStore.device !== 'mobile' && (
          <>
            <Tooltip title="主题模式" placement="bottom">
              <div className="right-menu-item hover-effect theme-switch-wrapper" onClick={toggleTheme}>
                {settingsStore.isDark ? (
                  <SunOutlined className="theme-icon" />
                ) : (
                  <MoonOutlined className="theme-icon" />
                )}
              </div>
            </Tooltip>

            <Tooltip title="全屏" placement="bottom">
              <div className="right-menu-item hover-effect" onClick={toggleFullscreen}>
                {isFullscreen ? <FullscreenExitOutlined /> : <FullscreenOutlined />}
              </div>
            </Tooltip>
          </>
        )}

        <Dropdown
          menu={{
            items: menuItems,
            onClick: ({ key }) => handleCommand(key)
          }}
          trigger={['hover']}
          placement="bottomRight"
        >
          <div className="avatar-container right-menu-item hover-effect">
            <div className="avatar-wrapper">
              <img src={userStore.avatar} className="user-avatar" alt="avatar" />
              <div className="user-info">
                <span className="user-nickname">{userStore.nickName}</span>
                {userStore.deptName && (
                  <span className="user-dept">{userStore.deptName}</span>
                )}
              </div>
            </div>
          </div>
        </Dropdown>
      </div>
    </div>
  )
}

export default Navbar
